
//____________________________________________________________________________________
//____________________________________________________________________________________
//
//									PSIONICS SYSTEM
//____________________________________________________________________________________
//____________________________________________________________________________________

// ***** CHANGE TO TRACKING

// TO DO for v0.9: 
// - make the psion a wizard kit
// - give 2 powers per level?
// 	...and make level limits for sciences?
// 	...or give different learning abilities/dialogues for sciences?
// - make psi/th and psi/fi variants
// 	...make ONLY psi/th and psi/fi variants ??
// - eliminate the psi item
// - use innates removed and granted every time
// - figure out what to do about Object Reading 
// 	...use Bubb's Identify
// - figure out what to about clairvoyant channeling

// make a psplz spell with the 172 effects
// 	...and a distinct one with the 171 effects
// cast the latter a second later

// probably should make a .2da list like in multisorc

// - make inertial barrier improve with levels
// - remove precognition
// - remove tower of iron will
// - add sensory synchronization
// - add synaptic static
// 	...~65% casting failure for everyone
// 	...and thac0/damage penalty?  luck penalty?
// 	...and psion cannot use powers
// 	...(don't 171 powers in main spell, do it in the cancel spell)
// - psychic knife: spec at 1st level, mastery at 6th level, gm at 12th
// 	...and add chance of secondary effect?
// - give inertial barrier immunity to cloud projectiles
// - change free action to devotion, 
// 	...with chance of evasion instead of full immunity
// - add animate earth elemental as science
// 	...name: 
// - add otiluke's sphere as science
// 	...not sure if can make it maintainable...
// 	...unless, only do one at a time - that works!
// - change Repulsion to single-use
// 	...strong effect, with knockdown and zone of sweet air
// 	...and probably rename it
// - change solar flash to devotion
// 	...little/no damage, short-duration blindness
// - add energy modulation as science
// 	...less elemental damage from enemies, more from allies
// - add heightened senses
// 	...ranger's Tracking ability
// - add know opponent as devotion
// 	...-2 AC, -1 saves & luck
// 	...name: 'aura evaluation'
// - change life detection to devotion
// - add fate link as science
// 	...unlimited-range fire shield
// - add project mind as high science
// 	...image = zero APR; and immune to hp/point recovery spells
// 	...
// - rename 'stasis field' to 'temporal stasis field'
// - rename 'absorb infliction' to 'empathic biotransfer'
// - rename 'sensory dissociation' to 'clairvoyant observation'
// - add missile avoidance to danger sense
// - ~60% miscast chance for everyone, psi cannot use powers

// gonna have to figure out how to do unlimited-range powers
// existing system is, powers have no range, but wiz spells casting them do
// now, don't need wiz spells to cast powers.
// though, still could set up something similar...

// MAYBE, the thing to do is:
// - have four outer spells
// ... short-range PSP, short-range HP, long-range PSP, and long-range HP
// - these spells will handle the range and the point cost, and cast the main ability
// - and the main abilities will *only* have actual effects
// ... I foresee problems with cancellable abilities...

// NO: keep the PW/PV spells, just make them innate
// ... give the PW version in pspl71, the PV version in psplv1
// ... remove all of them in pspl72


// TO DO later:

DEFINE_ACTION_FUNCTION psionics_system BEGIN 

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_psionics.d5~ BEGIN

//COPY MARKER FILE____________________________________________________________________
//
COPY ~will_to_power/lib/markers/d5_psionics.d5~ ~override~
//____________________________________________________________________________________


//PREP SPLPROT.2DA____________________________________________________________________
//
APPEND ~splprot.2da~ ~D5_MXHP_GT%TAB%1%TAB%-1%TAB%3~						//	max HP > x
APPEND ~splprot.2da~ ~D5_MXHP_LT%TAB%1%TAB%-1%TAB%2~						//	max HP < x
APPEND ~splprot.2da~ ~D5_134_PSI%TAB%134%TAB%-1%TAB%8~
APPEND ~splprot.2da~ ~D5_MANA_PTS%TAB%109%TAB%-1%TAB%7~ UNLESS ~D5_MANA_PTS~
APPEND ~splprot.2da~ ~D5_MANA_LESS%TAB%109%TAB%-1%TAB%2~ UNLESS ~D5_MANA_LESS~
APPEND ~splprot.2da~ ~D5_MANA_MORE%TAB%109%TAB%-1%TAB%3~ UNLESS ~D5_MANA_MORE~
APPEND ~splprot.2da~ ~D5_FATIGUE_IS%TAB%30%TAB%-1%TAB%1~ UNLESS ~D5_FATIGUE_IS~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MXHP_GT~ BEGIN
	  SET maxhp_gt = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MXHP_LT~ BEGIN
	  SET maxhp_lt = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_134_PSI~ BEGIN
	  SET 134_psi = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MANA_PTS~ BEGIN
	  SET mana_points = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MANA_LESS~ BEGIN
	  SET mana_less = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MANA_MORE~ BEGIN
	  SET mana_more = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_IS~ BEGIN
	  SET fatigue_value = %row%
	END
  END
BUT_ONLY
//____________________________________________________________________________________


//make table for adding to clabs______________________________________________________
//
<<<<<<<< d5/d5_psi.2da
ABILITY     ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
>>>>>>>>
COPY ~d5/d5_psi.2da~ ~override/d5_psi.2da~
//____________________________________________________________________________________


//remove all mage spell slots_________________________________________________________
//
COPY ~will_to_power/data/d5_base.spl~ ~override/d50wslt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 511 timing = 9 END
BUT_ONLY

APPEND ~d5_psi.2da~ ~NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~
//____________________________________________________________________________________


//remove all mage known spells________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d50wspl.2da~) BEGIN
  OUTER_SET 0wspl = 1
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d50wspl.2da~) BEGIN
  OUTER_SET 0wspl = 0
  COPY ~will_to_power/data/d5_base.spl~ ~override/d50wspl.spl~
END
ACTION_IF 0wspl = 0 BEGIN
  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
	PATCH_IF FILE_EXISTS_IN_GAME ~%SOURCE_RES%.spl~ BEGIN
	  READ_SHORT 0x1c spell_type 
	  READ_LONG 0x34 spell_level
	  PATCH_IF (~%SOURCE_RES%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ww][Ii][1-9][0-5][0-9]~ = 0) && (spell_type = 1) BEGIN
		SPRINT ~spell_res~ ~%SOURCE_RES%~
		INNER_ACTION BEGIN
		  COPY_EXISTING ~d50wspl.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%spell_res%~ END
		END
	  END
	END
  BUT_ONLY
END

APPEND ~d5_psi.2da~ ~NO_WSPLS    AP_D50WSPL  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
//____________________________________________________________________________________


//assign stats for mana - I mean, 'psionic strength' points___________________________
//
// Points = (stat 109)
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp9a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ /*~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~*/ BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp9%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 9 parameter2 = (109 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5psp9%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp2a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp2%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 2 parameter2 = (109 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5psp2%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp1a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ ~u~ BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp1%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 1 parameter2 = (109 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5psp1%let%~ END
  END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-1.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 1) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 1) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 1 parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-2.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-2.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 2) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_2.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 2) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+2.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 2 parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-3.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-3.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 3) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_3.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 3) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+3.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 3 parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-4.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 4) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 4) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 4 parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-5.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-5.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 5) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_5.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 5) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+5.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 5 parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-6.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 6) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 6) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 6 parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-X.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-X.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 10) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_X.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 10) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+X.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 10 parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END

// maybe 10 + 2/level? (to level 20, the 1/level to 40)
APPEND ~d5_psi.2da~ ~PSI_PTS     AP_D5PSP2A  AP_D5PSP2B  AP_D5PSP2C  AP_D5PSP2D  AP_D5PSP2E  AP_D5PSP2F  AP_D5PSP2G  AP_D5PSP2H  AP_D5PSP2I  AP_D5PSP2J  AP_D5PSP2K  AP_D5PSP2L  AP_D5PSP2M  AP_D5PSP2N  AP_D5PSP2O  AP_D5PSP2P  AP_D5PSP2Q  AP_D5PSP2R  AP_D5PSP2S  AP_D5PSP2T  AP_D5PSP1B  AP_D5PSP1C  AP_D5PSP1D  AP_D5PSP1E  AP_D5PSP1F  AP_D5PSP1G  AP_D5PSP1H  AP_D5PSP1I  AP_D5PSP1J  AP_D5PSP1K  AP_D5PSP1L  AP_D5PSP1M  AP_D5PSP1N  AP_D5PSP1O  AP_D5PSP1P  AP_D5PSP1Q  AP_D5PSP1R  AP_D5PSP1S  AP_D5PSP1T  AP_D5PSP1U  ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
PSI_PTS     AP_D5PSP9A  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
PSI_PTS     AP_D5PSP1A  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~

// every power will cast d5psp-# and d5psp_#, where # is half the power's cost, if the player has enough points

// in the case of maintainable spells, they will just cast d5psp-# twice
// and give the PSP-variant cancel spell, if the player has enough points
// then that cancel spell will cast d5psp+# to get half the cost back

// the 'restorative meditation' ability will 321 cancel all d5ps_# spells

// sleeping will cancel all d5psp-#, d5psp_#, and d5psp+# spells, to get back to the baseline

//____________________________________________________________________________________


//hit point cost files________________________________________________________________
//
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst6.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 6 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx6~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst10.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 10 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 11 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx10~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst20.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 20 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx20~ END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 6) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx10.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 10) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx20.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 20) parameter2 = 3 timing = 4 duration = 1 END

COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt6.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 6 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx6~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt10.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 10 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 11 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx10~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt20.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 20 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx20~ END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 6) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx10.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 10) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx20.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 20) parameter2 = 3 timing = 4 duration = 1 END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 72 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx10.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 72 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 84 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 96 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 108 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 120 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx20.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 72 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 84 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 96 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 108 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 120 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 132 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 144 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 156 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 168 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 180 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 192 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 204 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 216 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 228 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 240 END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrz6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 6 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 18 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 30 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END

// instant powers will cast d5psst#, if the player does not have enough points

// maintainable powers will cast d5psnt#, and give the HP-variant cancel ability

//___________________________________________________________________________________


//add available spellstates__________________________________________________________
//
LAF d5_resolve_state STR_VAR new_state_id = ~D5_METAPSIONIC~ RET new_state_ind END

OUTER_SET metapsionic_state = %new_state_ind%

LAF d5_resolve_state STR_VAR new_state_id = ~D5_MIND_WARD~ RET new_state_ind END

OUTER_SET mind_ward_state = %new_state_ind%

APPEND ~splprot.2da~ ~D5_STATE_POISON%TAB%0x111%TAB%0x4000%TAB%8~
APPEND ~splprot.2da~ ~D5_STATE_DISEASE%TAB%0x111%TAB%0x80000%TAB%8~

COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols 
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_STATE_POISON~ BEGIN
	    SET state_poison = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_STATE_DISEASE~ BEGIN
	    SET state_disease = %row%
	  END
	END
BUT_ONLY
//__________________________________________________________________________________


//PSIONIC ABILITY FILES_____________________________________________________________
//
// ***** make abilities here, but keep a list and do some universal patches via the list...?

// ***** NOTE: all cancel abilities should be target = 7 to avoid miscast chance

/*
COPY ~will_to_power/data/d5ps100.bam~ ~override~
COPY ~will_to_power/data/d5ps200.bam~ ~override~
COPY ~will_to_power/data/d5ps300.bam~ ~override~
COPY ~will_to_power/data/d5ps400.bam~ ~override~
COPY ~will_to_power/data/d5ps500.bam~ ~override~
COPY ~will_to_power/data/d5ps900.bam~ ~override~
*/

// main power
COPY ~will_to_power/data/d5ps101.bam~ ~override~
COPY ~will_to_power/data/d5ps101_.spl~ ~override~   //  				mind ward 
													// 			prot. vs. fear/charm/sleep/hold
													// 			109 = + confusion/domination/feeblemind/stun/maze
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 328 parameter2 = %mind_ward_state% END
	SAY NAME1 @1011
	SAY UNIDENTIFIED_DESC @1012
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps101~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps101~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 1 STR_VAR resource = ~d5py101~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 1 STR_VAR resource = ~d5px101~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5py101~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psrz6~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5px101~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psp&3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 duration = 0 STR_VAR resource = ~D5PS101S~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps101_~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
COPY ~will_to_power/data/d5px101.bam~ ~override~
// cancel ability when used with PSPs
COPY ~will_to_power/data/d5ps_x_.eff~ ~override/d5px101.eff~
	WRITE_ASCII 0x30 ~d5px101~ #8
	WRITE_ASCII 0x94 ~d5px101~ #8
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5px101.spl~
	SAY NAME1 @1013
	SAY UNIDENTIFIED_DESC @1013
	WRITE_ASCII 0x3a ~d5px101~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5px101~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps101_~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5px101~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp+3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
// cancel ability when used with hit points
COPY ~will_to_power/data/d5ps_x_.eff~ ~override/d5py101.eff~
	WRITE_ASCII 0x30 ~d5py101~ #8
	WRITE_ASCII 0x94 ~d5py101~ #8
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5py101.spl~
	SAY NAME1 @1013
	SAY UNIDENTIFIED_DESC @1013
	WRITE_ASCII 0x3a ~d5px101~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5px101~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps101_~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5py101~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
// ***** maybe do this more efficiently
/*
COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  SNPRINT 3 ~spl_prefix~ ~%SOURCE_RES%~
  PATCH_IF NOT (~%spl_prefix%~ STRING_EQUAL_CASE ~#bo~) BEGIN
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 24 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps101x~ END 	//	panic
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 5 /*match_parameter1 = 1*/ opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps101x~ END	//	charm
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 39 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps101x~ END 	//	sleep
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 217 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps101x~ END 	//	PW sleep
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 175 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps101x~ END 	//	hold
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 185 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps101x~ END 	//	hold2
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 247 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps101x~ END 	//	berserk
  END
BUT_ONLY
*/
// I don't remember what this is... maybe the cancel ability when triggered by being hit with a mental attack?
COPY_EXISTING ~d5psp+3.spl~ ~override/d5psp&3.spl~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps101x.spl~
	SAY NAME1 @1013
	SAY UNIDENTIFIED_DESC @1013
	WRITE_ASCII 0x3a ~d5px101~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5px101~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 target = 2 STR_VAR resource = ~d5ps101_~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 target = 2 STR_VAR resource = ~d5px101~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 target = 2 STR_VAR resource = ~d5py101~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrz6~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp&3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
// this is the wrapper spell that you actually cast
COPY ~will_to_power/data/d5ps101_.spl~ ~override/d5ps101.spl~
	SAY NAME1 @1011
	SAY UNIDENTIFIED_DESC @1012
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps101~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 range = 30 STR_VAR icon = ~d5ps101~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps101_~ END
// this is the wizard spell... only needed for show in the spellbook
COPY ~will_to_power/data/d5ps101_.spl~ ~override/d5ps101w.spl~
	SAY NAME1 @1011
	SAY UNIDENTIFIED_DESC @1012
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~d5ps101~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps101~ END
	LPF DELETE_EFFECT END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps102.bam~ ~override~
COPY ~will_to_power/data/d5ps102_.spl~ ~override~ 		//			sensory synchronization
	SAY NAME1 @1021
	SAY UNIDENTIFIED_DESC @1022
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps102~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps102~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 1 STR_VAR resource = ~d5py102~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 1 STR_VAR resource = ~d5px102~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5py102~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5px102~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 duration = 0 STR_VAR resource = ~D5PS102S~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps102_~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
COPY ~will_to_power/data/d5ps102.eff~ ~override~
COPY ~will_to_power/data/d5ps102a.spl~ ~override~
COPY ~will_to_power/data/d5px102.bam~ ~override~
COPY ~will_to_power/data/d5ps_x_.eff~ ~override/d5px102.eff~
	WRITE_ASCII 0x30 ~d5px102~ #8
	WRITE_ASCII 0x94 ~d5px102~ #8
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5px102.spl~
	SAY NAME1 @1023
	SAY UNIDENTIFIED_DESC @1023
	WRITE_ASCII 0x3a ~d5px102~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5px102~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps102_~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5px102~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp+3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
COPY ~will_to_power/data/d5ps_x_.eff~ ~override/d5py102.eff~
	WRITE_ASCII 0x30 ~d5py102~ #8
	WRITE_ASCII 0x94 ~d5py102~ #8
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5py102.spl~
	SAY NAME1 @1023
	SAY UNIDENTIFIED_DESC @1023
	WRITE_ASCII 0x3a ~d5px102~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5px102~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps102_~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5py102~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
COPY ~will_to_power/data/d5ps102_.spl~ ~override/d5ps102.spl~
	SAY NAME1 @1021
	SAY UNIDENTIFIED_DESC @1022
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps102~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 range = 30 STR_VAR icon = ~d5ps102~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps102_~ END
COPY ~will_to_power/data/d5ps102_.spl~ ~override/d5ps102w.spl~
	SAY NAME1 @1021
	SAY UNIDENTIFIED_DESC @1022
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~d5ps102~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps102~ END
	LPF DELETE_EFFECT END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps103.bam~ ~override~
COPY ~will_to_power/data/d5ps103_.spl~ ~override~   //  				id insinuation
	SAY NAME1 @1031
	SAY UNIDENTIFIED_DESC @1032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps103~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps103~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
COPY ~will_to_power/data/d5ps103_.spl~ ~override/d5ps103.spl~
	SAY NAME1 @1031
	SAY UNIDENTIFIED_DESC @1032
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps103~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 range = 30 STR_VAR icon = ~d5ps103~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp_3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
COPY ~will_to_power/data/d5ps103a.spl~ ~override~
	SAY NAME1 @1031
	SAY UNIDENTIFIED_DESC @1032
	WRITE_ASCII 0x3a ~d5ps103~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps103~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 2 parameter2 = 55 timing = 0 duration = 1 STR_VAR resource = ~d5ps103a~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps103a~ END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps103a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps103a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps103a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps103_.spl~ ~override/d5pz103.spl~
	SAY NAME1 @1031
	SAY UNIDENTIFIED_DESC @1032
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x1c 5
	WRITE_ASCII 0x3a ~d5ps103~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 STR_VAR icon = ~d5ps103~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp_3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
COPY ~will_to_power/data/d5ps103_.spl~ ~override/d5ps103w.spl~
	SAY NAME1 @1031
	SAY UNIDENTIFIED_DESC @1032
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~d5ps103~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps103~ END
	LPF DELETE_EFFECT END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps104.bam~ ~override~
COPY ~will_to_power/data/d5ps104_.spl~ ~override~   //  					ego whip
	SAY NAME1 @1041
	SAY UNIDENTIFIED_DESC @1042
	WRITE_LONG 0x34 3
	WRITE_ASCII 0x3a ~d5ps104~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps104~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp_3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
COPY ~will_to_power/data/d5ps104a.spl~ ~override~
	SAY NAME1 @1041
	SAY UNIDENTIFIED_DESC @1042
	WRITE_ASCII 0x3a ~d5ps104~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps104~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 2 parameter2 = 55 timing = 0 duration = 1 STR_VAR resource = ~d5ps101a~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps101a~ END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps104a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps104a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps104a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps104_.spl~ ~override/d5ps104.spl~
	SAY NAME1 @1041
	SAY UNIDENTIFIED_DESC @1042
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps104~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 range = 30 STR_VAR icon = ~d5ps104~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps104_~ END
COPY ~will_to_power/data/d5ps104_.spl~ ~override/d5pz104.spl~
	SAY NAME1 @1041
	SAY UNIDENTIFIED_DESC @1042
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps104~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 STR_VAR icon = ~d5ps104~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps104_~ END
COPY ~will_to_power/data/d5ps104_.spl~ ~override/d5ps104w.spl~
	SAY NAME1 @1041
	SAY UNIDENTIFIED_DESC @1042
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~d5ps104~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps104~ END
	LPF DELETE_EFFECT END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps105.bam~ ~override~
COPY ~will_to_power/data/d5ps105_.spl~ ~override~   //  				cerebral repair
	SAY NAME1 @1051
	SAY UNIDENTIFIED_DESC @1052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps105~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps105~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp_3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
COPY ~will_to_power/data/d5ps105a.spl~ ~override~
	SAY NAME1 @1051
	SAY UNIDENTIFIED_DESC @1052
	WRITE_ASCII 0x3a ~d5ps105~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps105~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps105a~ END
COPY ~will_to_power/data/d5ps105_.spl~ ~override/d5ps105.spl~
	SAY NAME1 @1051
	SAY UNIDENTIFIED_DESC @1052
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps105~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 range = 30 STR_VAR icon = ~d5ps105~ END
	LPF DELETE_EFFECT END
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps105_~ END
COPY ~will_to_power/data/d5ps105_.spl~ ~override/d5pz105.spl~
	SAY NAME1 @1051
	SAY UNIDENTIFIED_DESC @1052
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps105~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 STR_VAR icon = ~d5ps105~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps105_~ END
COPY ~will_to_power/data/d5ps105_.spl~ ~override/d5ps105w.spl~
	SAY NAME1 @1051
	SAY UNIDENTIFIED_DESC @1052
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 1
	WRITE_ASCII 0x3a ~d5ps105~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps105~ END
	LPF DELETE_EFFECT END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps107.bam~ ~override~
COPY ~will_to_power/data/d5ps107_.spl~ ~override~   // 				domination
	SAY NAME1 @1071
	SAY UNIDENTIFIED_DESC @1072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps107~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps107~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 9 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 9 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp_5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 10 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psst10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
COPY ~will_to_power/data/d5ps107a.spl~ ~override~
	SAY NAME1 @1071
	SAY UNIDENTIFIED_DESC @1072
	WRITE_ASCII 0x3a ~d5ps107~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps107~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 2 parameter2 = 55 timing = 0 duration = 1 STR_VAR resource = ~d5ps107a~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps107a~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_savingthrow = 8 savingthrow = 16 END
COPY ~will_to_power/data/d5ps107b.spl~ ~override~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_savingthrow = 8 savingthrow = 16 END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107c.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107d~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107e~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107e.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107f~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107f.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107g~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107g.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107h~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107h.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107i~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107i.spl~
	LPF DELETE_EFFECT INT_VAR silent = 1 match_opcode = 146 END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps107a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps107a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps107a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps107_.spl~ ~override/d5ps107.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps107~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 range = 30 STR_VAR icon = ~d5ps107~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps107_~ END
COPY ~will_to_power/data/d5ps107_.spl~ ~override/d5pz107.spl~
	WRITE_SHORT 0x1c 8
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps107~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 STR_VAR icon = ~d5ps107~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps107_~ END
COPY ~will_to_power/data/d5ps107_.spl~ ~override/d5ps107w.spl~
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 2
	WRITE_ASCII 0x3a ~d5ps107~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps107~ END
	LPF DELETE_EFFECT END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps108.bam~ ~override~
COPY ~will_to_power/data/d5ps108_.spl~ ~override~   // 				intellect fortress
	SAY NAME1 @1081
	SAY UNIDENTIFIED_DESC @1082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps108~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps108~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 1 STR_VAR resource = ~d5py108~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 1 STR_VAR resource = ~d5px108~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 9 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 9 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 9 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5py108~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5px108~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 duration = 0 STR_VAR resource = ~D5PS108S~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps108_~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 10 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psnt10~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter2 = 110 parameter1 = %mind_ward_state% STR_VAR match_resource = ~d5ps101x~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
COPY ~will_to_power/data/d5px108.bam~ ~override~
COPY ~will_to_power/data/d5ps_x_.eff~ ~override/d5px108.eff~
	WRITE_ASCII 0x30 ~d5px108~ #8
	WRITE_ASCII 0x94 ~d5px108~ #8
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5px108.spl~
	SAY NAME1 @1083
	SAY UNIDENTIFIED_DESC @1083
	WRITE_ASCII 0x3a ~d5px108~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5px108~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps108_~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5px108~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp+5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
COPY ~will_to_power/data/d5ps_x_.eff~ ~override/d5py108.eff~
	WRITE_ASCII 0x30 ~d5py108~ #8
	WRITE_ASCII 0x94 ~d5py108~ #8
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5py108.spl~
	SAY NAME1 @1083
	SAY UNIDENTIFIED_DESC @1083
	WRITE_ASCII 0x3a ~d5px108~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5px108~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps108_~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5py108~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
COPY ~will_to_power/data/d5ps108_.spl~ ~override/d5ps108.spl~
	SAY NAME1 @1081
	SAY UNIDENTIFIED_DESC @1082
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps108~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 range = 30 STR_VAR icon = ~d5ps108~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps108_~ END
// this is the wizard spell... only needed for show in the spellbook
COPY ~will_to_power/data/d5ps108_.spl~ ~override/d5ps108w.spl~
	SAY NAME1 @1081
	SAY UNIDENTIFIED_DESC @1082
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 2
	WRITE_ASCII 0x3a ~d5ps108~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps108~ END
	LPF DELETE_EFFECT END

//__________________________________________________________________________________

// ***** have this cancel chaotic commands et al. (...maybe 50% chance?)
// ***** have this cancel intellect fortress on a failed save (? ... or maybe just 50%?)
COPY ~will_to_power/data/d5ps109.bam~ ~override~
COPY ~will_to_power/data/d5ps109_.spl~ ~override~   // 				psychic crush
	SAY NAME1 @1091
	SAY UNIDENTIFIED_DESC @1092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps109~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps109~ END
	PATCH_FOR_EACH mind_protection IN ~sppr508~ ~sppr330~ /*~d5f1508~ ~d5m1508~ ~d5f1330~ ~d5m1330~*/ ~WIZARD_MIND_BLANK~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~%mind_protection%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 4 duration = 1 probability1 = 50 STR_VAR resource = EVAL ~%mind_protection%~ END
	  END
	  PATCH_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~[ %TAB%]%mind_protection%[ %TAB%%LNL%%MNL%%WNL%]~)) BEGIN
	    LPF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = EVAL ~%mind_protection%~ RET spell_res END
		PATCH_IF (FILE_EXISTS_IN_GAME ~%mind_protection%.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 4 duration = 1 probability1 = 50 STR_VAR resource = EVAL ~%mind_protection%~ END
		END
	  END
	END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 9 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 9 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp_5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 10 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psst10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
COPY ~will_to_power/data/d5ps109a.spl~ ~override~
	SAY NAME1 @1091
	SAY UNIDENTIFIED_DESC @1092
	WRITE_ASCII 0x3a ~d5ps109~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps109~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 2 parameter2 = 55 timing = 0 duration = 1 STR_VAR resource = ~d5ps109a~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps109a~ END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps109a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps109a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
// ***** need to account for sr4b17+
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps109a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps109_.spl~ ~override/d5ps109.spl~
	SAY NAME1 @1091
	SAY UNIDENTIFIED_DESC @1092
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps109~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 range = 30 STR_VAR icon = ~d5ps109~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps109_~ END
COPY ~will_to_power/data/d5ps109_.spl~ ~override/d5pz109.spl~
	SAY NAME1 @1091
	SAY UNIDENTIFIED_DESC @1092
	WRITE_SHORT 0x1c 4
	WRITE_SHORT 0x1c 8
	WRITE_ASCII 0x3a ~d5ps109~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 STR_VAR icon = ~d5ps109~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps109_~ END
COPY ~will_to_power/data/d5ps109_.spl~ ~override/d5ps109w.spl~
	SAY NAME1 @1091
	SAY UNIDENTIFIED_DESC @1092
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 2
	WRITE_ASCII 0x3a ~d5ps109~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps109~ END
	LPF DELETE_EFFECT END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps111.bam~ ~override~
COPY ~will_to_power/data/d5ps111_.spl~ ~override~ 		//			synaptic static
	SAY NAME1 @1111
	SAY UNIDENTIFIED_DESC @1112
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps111~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps111~ END
	LPF ADD_SPELL_EFFECT INT_VAR silent = 1 opcode = 93 target = 1 parameter1 = 4 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 1 STR_VAR resource = ~d5py111~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 1 STR_VAR resource = ~d5px111~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-X~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5psp-X~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 5 parameter2 = %mana_more% timing = 1 duration = 0 STR_VAR resource = ~d5py111~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5px111~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 duration = 0 STR_VAR resource = ~D5PS111S~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps111_~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 188 target = 1 parameter2 = 1 timing = 0 duration = 0 END
COPY ~will_to_power/data/d5ps111.eff~ ~override~
// ***** add pro d5visr.pro
ADD_PROJECTILE ~will_to_power/data/d5visr.pro~
// ***** use it in d5ps111a
COPY ~will_to_power/data/d5ps111a.spl~ ~override~
	LPF ALTER_SPELL_HEADER INT_VAR projectile = %d5visr% END
COPY ~will_to_power/data/d5px111.bam~ ~override~
COPY ~will_to_power/data/d5ps_x_.eff~ ~override/d5px111.eff~
	WRITE_ASCII 0x30 ~d5px111~ #8
	WRITE_ASCII 0x94 ~d5px111~ #8
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5px111.spl~
	SAY NAME1 @1113
	SAY UNIDENTIFIED_DESC @1113
	WRITE_ASCII 0x3a ~d5px111~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5px111~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps111_~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5px111~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp+X~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
COPY ~will_to_power/data/d5ps_x_.eff~ ~override/d5py111.eff~
	WRITE_ASCII 0x30 ~d5py111~ #8
	WRITE_ASCII 0x94 ~d5py111~ #8
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5py111.spl~
	SAY NAME1 @1113
	SAY UNIDENTIFIED_DESC @1113
	WRITE_ASCII 0x3a ~d5px111~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5px111~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps111_~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5py111~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
COPY ~will_to_power/data/d5ps111_.spl~ ~override/d5ps111.spl~
	SAY NAME1 @1111
	SAY UNIDENTIFIED_DESC @1112
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps111~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 2 range = 30 STR_VAR icon = ~d5ps111~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps111_~ END
COPY ~will_to_power/data/d5ps111_.spl~ ~override/d5ps111w.spl~
	SAY NAME1 @1111
	SAY UNIDENTIFIED_DESC @1112
	WRITE_SHORT 0x1c 1
	WRITE_LONG 0x34 3
	WRITE_ASCII 0x3a ~d5ps111~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps111~ END
	LPF DELETE_EFFECT END

//__________________________________________________________________________________

// d5ps#  = wrapper spell, 30' range 			(must be 7 chars because 172)
// ... and icon
// d5pz#  = wrapper spell, unlimited range		(must be 7 chars because 172)
// d5ps#w = wizard spell, for spellbook only
// d5ps#_ = actual ability
// d5ps#a = subspell, repeated effects
// d5px#  = cancel and give back PSPs			(must be 7 chars because 172)
// ... and icon
// d5py#  = cancel and give back HPs			(must be 7 chars because 172)
// d5ps#s = add ability (EFF in pspls1)
// d5ps#z = add ability (EFF in psplz1)
// d5ps#v = cannot use (206 vs. _s and _z)
// d5pv#  = learn ability (cancel _v, give _w)	(must be 7 chars because applied by ApplySpellRES)


COPY ~will_to_power/data/d5ps201.bam~ ~override~
COPY ~will_to_power/data/d5ps201.spl~ ~override~   // 				project force
	SAY NAME1 @2011
	SAY UNIDENTIFIED_DESC @2012
	WRITE_LONG 0x34 3
	WRITE_ASCII 0x3a ~d5ps201~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps201~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps201a.spl~ ~override~
	SAY NAME1 @2011
	SAY UNIDENTIFIED_DESC @2012
	WRITE_ASCII 0x3a ~d5ps201~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps201~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps201a~ END
COPY ~will_to_power/data/d5ps201.spl~ ~override/d5pw201.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps201~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps201~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps201~ END
COPY ~will_to_power/data/d5ps201.spl~ ~override/d5pv201.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps201~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps201~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps201~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps203.bam~ ~override~
COPY ~will_to_power/data/d5ps203.spl~ ~override~   // 				immobilize
	SAY NAME1 @2031
	SAY UNIDENTIFIED_DESC @2032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps203~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps203~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps203a.spl~ ~override~
	SAY NAME1 @2031
	SAY UNIDENTIFIED_DESC @2032
	WRITE_ASCII 0x3a ~d5ps203~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps203~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps203a~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_savingthrow = 8 savingthrow = 16 END
COPY ~will_to_power/data/d5ps203b.spl~ ~override~
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203c.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203d~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203e~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203e.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203f~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203f.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203g~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203g.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203h~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203h.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203i~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203i.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203j~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203j.spl~
	LPF DELETE_EFFECT INT_VAR silent = 1 match_opcode = 146 END
COPY ~will_to_power/data/d5ps203.spl~ ~override/d5pw203.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps203~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps203~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps203~ END
COPY ~will_to_power/data/d5ps203.spl~ ~override/d5pv203.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps203~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps203~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps203~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps204.bam~ ~override~
COPY ~will_to_power/data/d5ps204.spl~ ~override~   // 				inertial barrier
	SAY NAME1 @2041
	SAY UNIDENTIFIED_DESC @2042
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps204~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps204~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps2x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps204~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps2x4.spl~
	SAY NAME1 @2043
	SAY UNIDENTIFIED_DESC @2043
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps2x4~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps204~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps2x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps2x4.bam~ ~override~
COPY ~will_to_power/data/d5ps204.spl~ ~override/d5pw204.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps204~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps204~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps204~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps205.bam~ ~override~
COPY ~will_to_power/data/d5ps205.spl~ ~override~   // 				psychic knife
	SAY NAME1 @2051
	SAY UNIDENTIFIED_DESC @2052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps205~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps205~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps2x5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps205~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps2x5.spl~
	SAY NAME1 @2053
	SAY UNIDENTIFIED_DESC @2053
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps2x5~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps205~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps2x5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5psibla~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps2x5.bam~ ~override~
COPY ~will_to_power/data/d5psibla.itm~ ~override~
	SAY NAME1 @2051
	SAY UNIDENTIFIED_DESC @2051
COPY ~will_to_power/data/d5psibla.bam~ ~override~
COPY ~will_to_power/data/d5ps205.spl~ ~override/d5pw205.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps205~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps205~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps205~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps207.bam~ ~override~
COPY ~will_to_power/data/d5ps207.spl~ ~override~   // 				repulsion
	SAY NAME1 @2071
	SAY UNIDENTIFIED_DESC @2072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps207~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 1 STR_VAR icon = ~d5ps207~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps2x7~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps207~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt10~ END
COPY ~will_to_power/data/d5ps207b.spl~ ~override~
COPY ~will_to_power/data/d5ps207.eff~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps2x7.spl~
	SAY NAME1 @2073
	SAY UNIDENTIFIED_DESC @2073
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps2x7~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps207~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps2x7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx10~ END
COPY ~will_to_power/data/d5ps2x7.bam~ ~override~
COPY ~will_to_power/data/d5ps207.spl~ ~override/d5pw207.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps207~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps207~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps207~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps208.bam~ ~override~
COPY ~will_to_power/data/d5ps208.spl~ ~override~   // 				free action
	SAY NAME1 @2081
	SAY UNIDENTIFIED_DESC @2082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps208~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps208~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps2x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps208~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt10~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps2x8.spl~
	SAY NAME1 @2083
	SAY UNIDENTIFIED_DESC @2083
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps2x8~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps208~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps2x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx10~ END
COPY ~will_to_power/data/d5ps2x8.bam~ ~override~
COPY ~will_to_power/data/d5ps208.spl~ ~override/d5pw208.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps208~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps208~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps208~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps209.bam~ ~override~
COPY ~will_to_power/data/d5ps209.spl~ ~override~   // 				mass immobilize
	SAY NAME1 @2091
	SAY UNIDENTIFIED_DESC @2092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps209~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps209~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst10~ END
COPY ~will_to_power/data/d5ps209a.spl~ ~override~
	SAY NAME1 @2091
	SAY UNIDENTIFIED_DESC @2092
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps209a~ END
COPY ~will_to_power/data/d5ps209.spl~ ~override/d5pw209.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps209~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps209~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps209~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps211.bam~ ~override~
//COPY_EXISTING ~sppr720.spl~ ~override/d5ps211.spl~ 		//			earthquake
COPY ~will_to_power/data/d5ps211.spl~ ~override~ 		//			earthquake
	SAY NAME1 @2111
	SAY UNIDENTIFIED_DESC @2112
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps211~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps211~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 power = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 4 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps211~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY211~ END
COPY ~will_to_power/data/d5ps211b.spl~ ~override~
COPY ~will_to_power/data/d5ps211c.spl~ ~override~
COPY ~will_to_power/data/d5ps211.spl~ ~override/d5pw211.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps211~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps211~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps211~ END
COPY ~will_to_power/data/d5ps211.spl~ ~override/d5pv211.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps211~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps211~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps211~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps301.bam~ ~override~
COPY ~will_to_power/data/d5ps301.spl~ ~override~   //  				static discharge
	SAY NAME1 @3011
	SAY UNIDENTIFIED_DESC @3012
	WRITE_LONG 0x34 3
	WRITE_ASCII 0x3a ~d5ps301~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps301~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps301~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps301.itm~ ~override~
	SAY NAME1 @3011
	SAY UNIDENTIFIED_DESC @3012
COPY ~will_to_power/data/d5ps301d.spl~ ~override~
	SAY NAME1 @3011
	SAY UNIDENTIFIED_DESC @3012
COPY ~will_to_power/data/d5ps301.spl~ ~override/d5pw301.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps301~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps301~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps301~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps303.bam~ ~override~
COPY ~will_to_power/data/d5ps303.spl~ ~override~   // 				molecular agitation
	SAY NAME1 @3031
	SAY UNIDENTIFIED_DESC @3032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps303~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps303~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps3x3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps303~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps303.eff~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps3x3.spl~
	SAY NAME1 @3033
	SAY UNIDENTIFIED_DESC @3033
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps3x3~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps303~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps3x3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps3x3.bam~ ~override~
COPY ~will_to_power/data/d5ps303.spl~ ~override/d5pw303.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps303~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps303~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps303~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps304.bam~ ~override~
COPY ~will_to_power/data/d5ps304.spl~ ~override~   // 				energy dispersion
	SAY NAME1 @3041
	SAY UNIDENTIFIED_DESC @3042
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps304~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps304~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps3x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps304~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps3x4.spl~
	SAY NAME1 @3043
	SAY UNIDENTIFIED_DESC @3043
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps3x4~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps304~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps3x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps3x4.bam~ ~override~
COPY ~will_to_power/data/d5ps304.spl~ ~override/d5pw304.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps304~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps304~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps304~ END

COPY ~will_to_power/data/d5ps305.bam~ ~override~
// Projectile
COPY ~will_to_power/data/d5pfira.bam~ ~override~
COPY ~will_to_power/data/d5pfirx.bam~ ~override~
COPY ~will_to_power/data/d5prfir.vvc~ ~override~
COPY ~will_to_power/data/d5ep45.wav~ ~override~
COPY ~will_to_power/data/d5arp03.wav~ ~override~
ADD_PROJECTILE ~will_to_power/data/d5ps305.pro~  	//				projectile
//

//__________________________________________________________________________________

/*
COPY ~will_to_power/data/d5ps305.spl~ ~override~   // 				psychic combustion
	SAY NAME1 @3051
	SAY UNIDENTIFIED_DESC @3052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps305~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps305~ END
	WRITE_SHORT 0x98 ~%d5ps305%~  //Projectile
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps305~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
*/
COPY ~will_to_power/data/d5ps305.spl~ ~override/d5pw305.spl~
	SAY NAME1 @3051
	SAY UNIDENTIFIED_DESC @3052
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps305~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps305~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5pw305~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps305b~ END
COPY ~will_to_power/data/d5ps305a.spl~ ~override/d5pw305b.spl~
	SAY NAME1 @3051
	SAY UNIDENTIFIED_DESC @3052
	WRITE_ASCII 0x3a ~d5ps305~ #8
	WRITE_SHORT 0x98 ~%d5ps305%~  //Projectile
	WRITE_SHORT 0xc0 ~%d5ps305%~  //Projectile
	WRITE_SHORT 0xe8 ~%d5ps305%~  //Projectile
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps201~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps305a~ END
COPY ~will_to_power/data/d5ps305.spl~ ~override/d5pv305.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps305~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps305~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 148 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps305~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps307.bam~ ~override~
COPY ~will_to_power/data/d5ps307.spl~ ~override~   // 				solar flash
	SAY NAME1 @3071
	SAY UNIDENTIFIED_DESC @3072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps307~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps307~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps307~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst10~ END
COPY ~will_to_power/data/d5ps307u.eff~ ~override~
COPY ~will_to_power/data/d5ps307.spl~ ~override/d5pw307.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps307~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps307~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps307~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps308.bam~ ~override~
COPY ~will_to_power/data/d5ps308.spl~ ~override~   // 				ice storm
	SAY NAME1 @3081
	SAY UNIDENTIFIED_DESC @3082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps308~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps308~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst10~ END
COPY ~will_to_power/data/d5ps308a.spl~ ~override~
	SAY NAME1 @3081
	SAY UNIDENTIFIED_DESC @3082
	WRITE_ASCII 0x3a ~d5ps308~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps308~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps308a~ END
COPY ~will_to_power/data/d5ps308.spl~ ~override/d5pw308.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps308~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps308~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps308~ END
COPY ~will_to_power/data/d5ps308.spl~ ~override/d5pv308.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps308~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps308~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps308~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps309.bam~ ~override~
COPY ~will_to_power/data/d5ps309.spl~ ~override~   // 				generate lightning
	SAY NAME1 @3091
	SAY UNIDENTIFIED_DESC @3092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps309~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps309~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst10~ END
COPY ~will_to_power/data/d5ps309a.spl~ ~override~
	SAY NAME1 @3091
	SAY UNIDENTIFIED_DESC @3092
	WRITE_ASCII 0x3a ~d5ps309~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps309~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps309a~ END
COPY ~will_to_power/data/d5ps309.spl~ ~override/d5pw309.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps309~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps309~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps309~ END
COPY ~will_to_power/data/d5ps309.spl~ ~override/d5pv309.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps309~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps309~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps309~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps311.bam~ ~override~
COPY ~will_to_power/data/d5ps311.spl~ ~override~ 		//			storm of energy
	SAY NAME1 @3111
	SAY UNIDENTIFIED_DESC @3112
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps311~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps311~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 power = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 4 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY311~ END
COPY ~will_to_power/data/d5ps311a.spl~ ~override~
	SAY NAME1 @3111
	SAY UNIDENTIFIED_DESC @3112
	WRITE_ASCII 0x3a ~d5ps311~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps311~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 2 STR_VAR resource = ~d5ps311a~ END
COPY ~will_to_power/data/d5ps311.spl~ ~override/d5pw311.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps311~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps311~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps311~ END
COPY ~will_to_power/data/d5ps311.spl~ ~override/d5pv311.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps311~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps311~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps311~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps401.bam~ ~override~
COPY ~will_to_power/data/d5ps401.spl~ ~override~   //  				adrenaline rush
	SAY NAME1 @4011
	SAY UNIDENTIFIED_DESC @4012
	WRITE_LONG 0x34 3
	WRITE_ASCII 0x3a ~d5ps401~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps401~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps401~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps401a.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~will_to_power/data/d5ps401.spl~ ~override/d5pw401.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps401~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps401~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps401~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps403.bam~ ~override~
COPY ~will_to_power/data/d5ps403.spl~ ~override~   //  				body purification
	SAY NAME1 @4031
	SAY UNIDENTIFIED_DESC @4032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps403~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 0 STR_VAR icon = ~d5ps403~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps403~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps403.spl~ ~override/d5pw403.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps403~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps403~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps403~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps404.bam~ ~override~
COPY ~will_to_power/data/d5ps404.spl~ ~override~   // 				bioregeneration
	SAY NAME1 @4041
	SAY UNIDENTIFIED_DESC @4042
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps404~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps404~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps4x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps404~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps4x4.spl~
	SAY NAME1 @4043
	SAY UNIDENTIFIED_DESC @4043
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps4x4~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps404~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps4x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps4x4.bam~ ~override~
COPY ~will_to_power/data/d5ps404.spl~ ~override/d5pw404.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps404~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps404~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps404~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps405.bam~ ~override~
COPY ~will_to_power/data/d5ps405.spl~ ~override~   //  				poison simulation
	SAY NAME1 @4051
	SAY UNIDENTIFIED_DESC @4052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps405~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps405~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps405a.spl~ ~override~
	SAY NAME1 @4051
	SAY UNIDENTIFIED_DESC @4052
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps405a~ END
COPY ~will_to_power/data/d5ps405a.eff~ ~override~
COPY ~will_to_power/data/d5ps405b.eff~ ~override~
COPY ~will_to_power/data/d5ps405c.eff~ ~override~
COPY ~will_to_power/data/d5ps405.spl~ ~override/d5pw405.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps405~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 5 STR_VAR icon = ~d5ps405~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps405~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps407.bam~ ~override~
COPY ~will_to_power/data/d5ps407.spl~ ~override~   //  				absorb infliction
	SAY NAME1 @4071
	SAY UNIDENTIFIED_DESC @4072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps407~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps407~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst10~ END
COPY ~will_to_power/data/d5ps407a.spl~ ~override~
	SAY NAME1 @4071
	SAY UNIDENTIFIED_DESC @4072
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps407a~ END
COPY ~will_to_power/data/d5ps407.spl~ ~override/d5pw407.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps407~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps407~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps407~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps408.bam~ ~override~
COPY ~will_to_power/data/d5ps408.spl~ ~override~   // 				camouflage
	SAY NAME1 @4081
	SAY UNIDENTIFIED_DESC @4082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps408~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps408~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps4x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps408~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt10~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps4x8.spl~
	SAY NAME1 @4083
	SAY UNIDENTIFIED_DESC @4083
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps4x8~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps408~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps4x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx10~ END
COPY ~will_to_power/data/d5ps4x8.bam~ ~override~
COPY ~will_to_power/data/d5ps408.spl~ ~override/d5pw408.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps408~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps408~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps408~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps409.bam~ ~override~
COPY ~will_to_power/data/d5ps409.spl~ ~override~   // 				carapace
	SAY NAME1 @4091
	SAY UNIDENTIFIED_DESC @4092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps409~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps409~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps4x9~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps409~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt10~ END
COPY ~will_to_power/data/d5ps409.eff~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps4x9.spl~
	SAY NAME1 @4093
	SAY UNIDENTIFIED_DESC @4093
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps4x9~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps409~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps4x9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx10~ END
COPY ~will_to_power/data/d5ps4x9.bam~ ~override~
COPY ~will_to_power/data/d5ps409.spl~ ~override/d5pw409.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps409~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps409~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps409~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps411.bam~ ~override~
COPY ~will_to_power/data/d5ps411.spl~ ~override~   // 				bestial transformation
	SAY NAME1 @4111
	SAY UNIDENTIFIED_DESC @4112
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps411~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps411~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps4y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps411~ END
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END // uncomment line to pay up-front
COPY ~will_to_power/data/d5ps411.cre~ ~override~
COPY ~will_to_power/data/d5ps411.itm~ ~override~
	SAY NAME1 @4111
	SAY UNIDENTIFIED_DESC @4111
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps4y1.spl~
	SAY NAME1 @4113
	SAY UNIDENTIFIED_DESC @4113
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps4y1~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps411~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps4y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx20~ END // or rx20 if pay up-front
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 0 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 1 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 2 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 3 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 4 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 5 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 7 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 14 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps411~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 135 target = 1 parameter1 = 0 parameter2 = 0 timing = 9 END
COPY ~will_to_power/data/d5ps4y1.bam~ ~override~
COPY ~will_to_power/data/d5ps411.spl~ ~override/d5pw411.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps411~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps411~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps411~ END

//__________________________________________________________________________________

/*
COPY ~will_to_power/data/d5ps501.bam~ ~override~
COPY ~will_to_power/data/d5ps501.spl~ ~override~   // 				object reading
*/

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps503.bam~ ~override~
COPY ~will_to_power/data/d5ps503.spl~ ~override~   // 				insightful strike
	SAY NAME1 @5031
	SAY UNIDENTIFIED_DESC @5032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps503~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps503~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps5x3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps503~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5x3.spl~
	SAY NAME1 @5033
	SAY UNIDENTIFIED_DESC @5033
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5x3~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps503~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5x3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps5x3.eff~ ~override~
/*
COPY_EXISTING ~d5ps5x3.spl~ ~override/d5ps5xx3.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_target = 1 target = 9 END
*/
COPY ~will_to_power/data/d5ps5x3.bam~ ~override~
COPY ~will_to_power/data/d5ps503.spl~ ~override/d5pw503.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps503~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps503~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps503~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps504.bam~ ~override~
COPY ~will_to_power/data/d5ps504.spl~ ~override~   // 				instinctive luck
	SAY NAME1 @5041
	SAY UNIDENTIFIED_DESC @5042
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps504~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps504~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps5x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps504~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5x4.spl~
	SAY NAME1 @5043
	SAY UNIDENTIFIED_DESC @5043
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5x4~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps504~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps5x4.bam~ ~override~
COPY ~will_to_power/data/d5ps504.spl~ ~override/d5pw504.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps504~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps504~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps504~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps505.bam~ ~override~
COPY ~will_to_power/data/d5ps505.spl~ ~override~   // 				clairvoyant sight
	SAY NAME1 @5051
	SAY UNIDENTIFIED_DESC @5052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps505~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps505~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 239 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps505~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY_EXISTING ~spwi424.spl~ ~override/d5pw505.spl~
//	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps505~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps505~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 174 END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 239 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps505~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps507.bam~ ~override~
COPY ~will_to_power/data/d5ps507.spl~ ~override~   // 				precognition
	SAY NAME1 @5071
	SAY UNIDENTIFIED_DESC @5072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps507~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 0 STR_VAR icon = ~d5ps507~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst10~ END
COPY ~will_to_power/data/d5ps507a.spl~ ~override~
	SAY NAME1 @5071
	SAY UNIDENTIFIED_DESC @5072
	WRITE_ASCII 0x3a ~d5ps507~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps507~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps507a~ END

COPY ~will_to_power/data/d5ps507.spl~ ~override/d5pw507.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps507~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps507~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps507~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps508.bam~ ~override~
COPY ~will_to_power/data/d5ps508.spl~ ~override~   //  				life detection
	SAY NAME1 @5081
	SAY UNIDENTIFIED_DESC @5082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps508~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps508~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps1x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps104~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt10~ END
COPY ~will_to_power/data/d5ps508b.spl~ ~override~
COPY ~will_to_power/data/d5ps508.eff~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5x8.spl~
	SAY NAME1 @5083
	SAY UNIDENTIFIED_DESC @5083
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5x8~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps508~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx10~ END
COPY ~will_to_power/data/d5ps5x8.bam~ ~override~
COPY ~will_to_power/data/d5ps508.spl~ ~override/d5pw508.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps508~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps508~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps508~ END

// add sanctuary to invisibility to make life detection work
INCLUDE ~%MOD_FOLDER%/lib/d5_insanctibility.tpa~
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_insanctibility.d5~ BEGIN
  LAM D5_INSANCTIBILITY
END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps509.bam~ ~override~
COPY ~will_to_power/data/d5ps509.spl~ ~override~   // 				danger sense
	SAY NAME1 @5091
	SAY UNIDENTIFIED_DESC @5092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps509~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps509~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps5x9~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps509~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt10~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5x9.spl~
	SAY NAME1 @5093
	SAY UNIDENTIFIED_DESC @5093
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5x9~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps509~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5x9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx10~ END
COPY ~will_to_power/data/d5ps5x9.bam~ ~override~
COPY ~will_to_power/data/d5ps509.spl~ ~override/d5pw509.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps509~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps509~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps509~ END

// process spells to make evasion work
OUTER_SET optional_evade = 1
INCLUDE ~%MOD_FOLDER%/lib/spell_evasion.tpa~
ACTION_PHP_EACH evade_spells AS evadable_spell => ind BEGIN 
  LAF add_evade_spell INT_VAR evasion_spellstate = 252 evasion_save = 2 STR_VAR evade_ext = ~spl~ evade_condition = ~spellstate~ evade_res = EVAL ~%evadable_spell%~ evade_prefix = ~D5EV~ END
END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps511.bam~ ~override~
COPY ~will_to_power/data/d5ps511.spl~ ~override~    	// 			clairvoyant channeling
	SAY NAME1 @5111
	SAY UNIDENTIFIED_DESC @5112
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps511~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps511~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps5y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps511~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = %metapsionic_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5ps511a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = %metapsionic_state% parameter2 = 110 timing = 1 STR_VAR resource = ~d5ps511b~ END
COPY ~will_to_power/data/d5ps511a.spl~ ~override~
COPY ~will_to_power/data/d5ps511b.spl~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5y1.spl~
	SAY NAME1 @5113
	SAY UNIDENTIFIED_DESC @5113
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5y1~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps511~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps500~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps5900~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = %metapsionic_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5ps511c~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = %metapsionic_state% parameter2 = 110 timing = 1 STR_VAR resource = ~d5ps511d~ END
COPY ~will_to_power/data/d5ps5y1.bam~ ~override~
COPY ~will_to_power/data/d5ps511c.spl~ ~override~
COPY ~will_to_power/data/d5ps511d.spl~ ~override~
COPY ~will_to_power/data/d5ps511.spl~ ~override/d5pw511.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps511~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps511~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps511~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps901.bam~ ~override~
COPY ~will_to_power/data/d5ps901.spl~ ~override~ 	//				ultrablast
	SAY NAME1 @9011
	SAY UNIDENTIFIED_DESC @9012
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps901~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps901~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY901~ END
COPY ~will_to_power/data/d5ps901a.spl~ ~override~
	SAY NAME1 @9011
	SAY UNIDENTIFIED_DESC @9012
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 2 STR_VAR resource = ~d5ps901a~ END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps901a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps901a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps901a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps901.spl~ ~override/d5pw901.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps901~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps901~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps901~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps902.bam~ ~override~
COPY ~will_to_power/data/d5ps902.spl~ ~override~ 		//			energy construct
	SAY NAME1 @9021
	SAY UNIDENTIFIED_DESC @9022
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps902~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps902~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps902~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY902~ END
COPY ~will_to_power/data/d5ps902.eff~ ~override~
COPY ~will_to_power/data/d5ps902.spl~ ~override/d5pw902.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps902~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps902~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 148 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps902~ END
COPY ~will_to_power/data/d5ps902.spl~ ~override/d5pv902.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps902~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps902~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 148 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps902~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps903.bam~ ~override~
COPY ~will_to_power/data/d5ps903.spl~ ~override~ 		//			fission
	SAY NAME1 @9031
	SAY UNIDENTIFIED_DESC @9032
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps903~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps903~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 4 duration = 2 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps903~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY903~ END
COPY ~will_to_power/data/d5ps903a.spl~ ~override~
	SAY NAME1 @9031
	SAY UNIDENTIFIED_DESC @9032
COPY ~will_to_power/data/d5ps903b.spl~ ~override~
	SAY NAME1 @9031
	SAY UNIDENTIFIED_DESC @9032
COPY ~will_to_power/data/d5ps903.spl~ ~override/d5pw903.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps903~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps903~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps903~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps904.bam~ ~override~
COPY ~will_to_power/data/d5ps904.spl~ ~override~ 		//			atomic disruption
	SAY NAME1 @9041
	SAY UNIDENTIFIED_DESC @9042
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps904~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps904~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 4 duration = 2 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY904~ END
COPY ~will_to_power/data/d5ps904a.spl~ ~override~
	SAY NAME1 @9041
	SAY UNIDENTIFIED_DESC @9042
	WRITE_ASCII 0x3a ~d5ps904~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps904~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 9 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps904a~ END
COPY ~will_to_power/data/d5ps904.spl~ ~override/d5pw904.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps904~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps904~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps904~ END
COPY ~will_to_power/data/d5ps904.spl~ ~override/d5pv904.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps904~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps904~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps904~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps905.bam~ ~override~
COPY ~will_to_power/data/d5ps905.spl~ ~override~   	// 				exoskeleton
	SAY NAME1 @9051
	SAY UNIDENTIFIED_DESC @9052
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps905~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps905~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps9x5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps905~ END
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END // uncomment line to pay up-front
COPY ~will_to_power/data/d5ps905.cre~ ~override~
COPY ~will_to_power/data/d5ps905.itm~ ~override~
	SAY NAME1 @9051
	SAY UNIDENTIFIED_DESC @9051
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps9x5.spl~
	SAY NAME1 @9053
	SAY UNIDENTIFIED_DESC @9053
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps9x5~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps905~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps9x5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx20~ END // or rx20 if pay up-front
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 0 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 1 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 2 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 3 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 4 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 5 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 7 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 14 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps905~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 135 target = 1 parameter1 = 0 parameter2 = 0 timing = 9 END
COPY ~will_to_power/data/d5ps9x5.bam~ ~override~
COPY ~will_to_power/data/d5ps905.spl~ ~override/d5pw905.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps905~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps905~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps905~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps906.bam~ ~override~
COPY ~will_to_power/data/d5ps906.spl~ ~override~   	// 				elemental composition
	SAY NAME1 @9061
	SAY UNIDENTIFIED_DESC @9052
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps906~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps906~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps9x6~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps906~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps9x6.spl~
	SAY NAME1 @9063
	SAY UNIDENTIFIED_DESC @9063
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps9x6~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps906~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps9x6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 0 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 1 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 2 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 3 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 4 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 5 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 7 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 14 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps906e~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps906f~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps906i~ END
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 135 target = 1 parameter1 = 0 parameter2 = 0 timing = 9 END
COPY ~will_to_power/data/d5ps9x6.bam~ ~override~
COPY ~will_to_power/data/d5_ps906.2da~ ~override~
COPY ~will_to_power/data/d5ps906e.spl~ ~override~
	SAY NAME1 @9066
	SAY UNIDENTIFIED_DESC @9066
	WRITE_ASCII 0x3a ~d5ps906e~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps906e~ END
COPY ~will_to_power/data/d5ps906e.cre~ ~override~
COPY ~will_to_power/data/d5ps906e.itm~ ~override~
	SAY NAME1 @9066
	SAY UNIDENTIFIED_DESC @9066
COPY ~will_to_power/data/d5ps906e.bam~ ~override~
COPY ~will_to_power/data/d5ps906f.spl~ ~override~
	SAY NAME1 @9067
	SAY UNIDENTIFIED_DESC @9066
	WRITE_ASCII 0x3a ~d5ps906f~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps906f~ END
COPY ~will_to_power/data/d5ps906f.cre~ ~override~
COPY ~will_to_power/data/d5ps906f.itm~ ~override~
	SAY NAME1 @9067
	SAY UNIDENTIFIED_DESC @9067
COPY ~will_to_power/data/d5ps906f.bam~ ~override~
COPY ~will_to_power/data/d5ps906i.spl~ ~override~
	SAY NAME1 @9068
	SAY UNIDENTIFIED_DESC @9068
	WRITE_ASCII 0x3a ~d5ps906i~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps906i~ END
COPY ~will_to_power/data/d5ps906i.cre~ ~override~
COPY ~will_to_power/data/d5ps906i.itm~ ~override~
	SAY NAME1 @9068
	SAY UNIDENTIFIED_DESC @9068
COPY ~will_to_power/data/d5ps906i.bam~ ~override~
COPY ~will_to_power/data/d5ps906.spl~ ~override/d5pw906.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps906~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps906~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps906~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps907.bam~ ~override~
COPY ~will_to_power/data/d5ps907.spl~ ~override~ 		//			project mind
	SAY NAME1 @9071
	SAY UNIDENTIFIED_DESC @9072
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps907~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps907~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 4 duration = 2 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps907~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps907b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = ~d5psrx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = ~d5psrx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = ~d5psrx10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 7 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 9 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 11 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 12 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 13 timing = 1 END
COPY ~will_to_power/data/d5ps907.spl~ ~override/d5pw907.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps907~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps907~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps907~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps908.bam~ ~override~
COPY ~will_to_power/data/d5ps908.spl~ ~override~    	// 			dimensional anchor
	SAY NAME1 @9081
	SAY UNIDENTIFIED_DESC @9082
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps908~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps908~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps9x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps908~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps9x8.spl~
	SAY NAME1 @9083
	SAY UNIDENTIFIED_DESC @9083
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps9x8~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps908~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps9x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
COPY ~will_to_power/data/d5ps9x8.bam~ ~override~
COPY ~will_to_power/data/d5ps908.spl~ ~override/d5pw908.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps908~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps908~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps908~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps909.bam~ ~override~
COPY ~will_to_power/data/d5ps909.spl~ ~override~ 		//			stasis field
	SAY NAME1 @9091
	SAY UNIDENTIFIED_DESC @9092
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps909~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 4 STR_VAR icon = ~d5ps909~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps909~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY909~ END
COPY ~will_to_power/data/d5ps909.spl~ ~override/d5pw909.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps909~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps909~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps909~ END

//__________________________________________________________________________________

COPY ~will_to_power/data/d5ps910.bam~ ~override~
COPY ~will_to_power/data/d5ps910.spl~ ~override~   	// 			body control/directed evolution
	SAY NAME1 @9101
	SAY UNIDENTIFIED_DESC @9102
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps910~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps910~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps3x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps304~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps910a.bam~ ~override~
COPY ~will_to_power/data/d5ps91a.spl~ ~override~
	SAY NAME1 @91001
	SAY UNIDENTIFIED_DESC @91001
	WRITE_ASCII 0x3a ~d5ps910a~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910b.bam~ ~override~
COPY ~will_to_power/data/d5ps91b.spl~ ~override~
	SAY NAME1 @91002
	SAY UNIDENTIFIED_DESC @91002
	WRITE_ASCII 0x3a ~d5ps910b~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910c.bam~ ~override~
COPY ~will_to_power/data/d5ps91c.spl~ ~override~
	SAY NAME1 @91003
	SAY UNIDENTIFIED_DESC @91003
	WRITE_ASCII 0x3a ~d5ps910c~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910c~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910d.bam~ ~override~
COPY ~will_to_power/data/d5ps91d.spl~ ~override~
	SAY NAME1 @91004
	SAY UNIDENTIFIED_DESC @91004
	WRITE_ASCII 0x3a ~d5ps910dd~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910e.bam~ ~override~
COPY ~will_to_power/data/d5ps91e.spl~ ~override~
	SAY NAME1 @91005
	SAY UNIDENTIFIED_DESC @91005
	WRITE_ASCII 0x3a ~d5ps910e~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910e~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910f.bam~ ~override~
COPY ~will_to_power/data/d5ps91f.spl~ ~override~
	SAY NAME1 @91006
	SAY UNIDENTIFIED_DESC @91006
	WRITE_ASCII 0x3a ~d5ps910f~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910f~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910g.bam~ ~override~
COPY ~will_to_power/data/d5ps91g.spl~ ~override~
	SAY NAME1 @91007
	SAY UNIDENTIFIED_DESC @91007
	WRITE_ASCII 0x3a ~d5ps910g~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910g~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910h.bam~ ~override~
COPY ~will_to_power/data/d5ps91h.spl~ ~override~
	SAY NAME1 @91008
	SAY UNIDENTIFIED_DESC @91008
	WRITE_ASCII 0x3a ~d5ps910h~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910h~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps9y0.spl~
	SAY NAME1 @9103
	SAY UNIDENTIFIED_DESC @9103
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps9y0~ END
//	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps910~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps9y0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	END
COPY ~will_to_power/data/d5ps9y0.bam~ ~override~
COPY ~will_to_power/data/d5ps910.spl~ ~override/d5pw910.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps910~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps910~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps910~ END

//end ability files_________________________________________________________________



//learning new powers________________________________________________________________
//
// d5ps#  = wrapper spell, 30' range 			(must be 7 chars because 172)
// ... and icon
// d5pz#  = wrapper spell, unlimited range		(must be 7 chars because 172)
// d5ps#w = wizard spell, for spellbook only
// d5ps#_ = actual ability
// d5ps#a = subspell, repeated effects
// d5px#  = cancel and give back PSPs			(must be 7 chars because 172)
// ... and icon
// d5py#  = cancel and give back HPs			(must be 7 chars because 172)
// d5ps#s = add ability (EFF in pspls1)
// d5ps#z = add ability (EFF in psplz1)
// d5ps#v = cannot use (206 vs. _s and _z)
// d5pv#  = learn ability (cancel _v, give _w)	(must be 7 chars because applied by ApplySpellRES)

ACTION_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
 ACTION_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
  CREATE EFF ~d5ps%disc%%abil%s~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 0
	WRITE_LONG 0x28 1
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~d5ps%disc%%abil%~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5PS%disc%%abil%S~ #8
// long-range version
  ACTION_IF FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~ BEGIN
	CREATE EFF ~d5ps%disc%%abil%z~
	 WRITE_LONG 0x10 171
	 WRITE_LONG 0x14 1
	 WRITE_LONG 0x24 0
	 WRITE_LONG 0x28 1
	 WRITE_SHORT 0x2c 100
	 WRITE_EVALUATED_ASCII 0x30 ~d5pz%disc%%abil%~ #8
	 WRITE_LONG 0x90 1
	 WRITE_EVALUATED_ASCII 0x94 ~D5PS%disc%%abil%Z~ #8
  END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%disc%%abil%v.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~D5PS%disc%%abil%S~ END
	PATCH_IF FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~D5PS%disc%%abil%Z~ END
	END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5pv%disc%%abil%.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%v~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%v~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%w~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 2 STR_VAR resource = ~d5pspls1~ END
 END
END

ACTION_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
  COPY_EXISTING ~d5pv%disc%01.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = ~d5pspls2~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = ~d5pspls1~ END
END

COPY ~will_to_power/data/d5ps000.spl~ ~override~
  SAY NAME1 ~initialize psionics~
  LPF DELETE_EFFECT INT_VAR match_opcode = 143 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5prptz~ END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%v.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%disc%%abil%v~ END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5pv%disc%01~ END
  END


// these will have 171 effects for every power, 2^(#-1) times each
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts1.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts2.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts3.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts4.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 8; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts5.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 16; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts6.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 32; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts7.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 64; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		END
	  END
	END
  END

// these will also have 171 effects for every power, but unlimited-range versions where possible
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pptz1.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && !(FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && (FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pptz2.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && !(FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && (FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pptz3.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && !(FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && (FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pptz4.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && !(FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 8; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && (FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 8; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
		END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pptz5.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && !(FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 16; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && (FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 16; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
		END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pptz6.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && !(FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 32; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && (FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 32; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
		END
	  END
	END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pptz7.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && (!FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 64; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
		END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) && (FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		FOR (pts_count = 1; pts_count < 64; ++pts_count) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
		END
	  END
	END
  END

// this will have 172 effects for all powers of every type and range
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pspls2.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~d5ps%disc%%abil%~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5pz%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~d5ps%disc%%abil%~ END
	  END
	END
  END

// this will give the normal-range 171 spells
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pspls1.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 1 parameter2 = %mana_less% timing = 1 STR_VAR resource = ~d5ppts1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 1 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5ppts1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 2 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5ppts2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 4 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5ppts3~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 8 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5ppts4~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 16 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5ppts5~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 32 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5ppts6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 64 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5ppts7~ END

// this will give the unlimited-range 171 spells
COPY ~will_to_power/data/d5_base.spl~ ~override/d5psplz1.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 1 parameter2 = %mana_less% timing = 1 STR_VAR resource = ~d5pptz1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 1 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5pptz1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 2 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5pptz2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 4 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5pptz3~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 8 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5pptz4~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 16 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5pptz5~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 32 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5pptz6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 64 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5pptz7~ END

// every power will cast d5pspls2, then d5pspls1 a second later
// cancel abilities too

// clairvoyant channeling will cast d5pspls2, then d5psplz1 a second later

// combine these. the 172 spell should use 326 to conditionally cast either the s1 spell or the z1 spell (with timing 4/duration 1)
// then powers only have to cast the 172 spell
// and it can be applied every level to update PSP counts

// WAIT... only do this ^^ if want the clairvoyant channeling power to be maintainable
// if it is for one-shot ranged use, then every ability should cast both s2 and s1
// and the clab table should apply both (but then need a wrapper spell to apply s1 on a delay)
// and only the channeling power needs to cast z1

COPY ~will_to_power/data/d5_base.spl~ ~override/d5pspls.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END // s2
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END // s1

APPEND ~d5_psi.2da~ ~PSI_PTS     AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

//____________________________________________________________________________________


// PSPs refresh after rest____________________________________________________________
//
COPY ~will_to_power/data/d5_base.spl~ ~override/d5prptz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5prpts~ END

//APPEND ~d5_psi.2da~ ~MANA_PTS    AP_D5PRPTZ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

CREATE EFF ~d5prpts~
  WRITE_LONG 0x10 232
  WRITE_LONG 0x14 1
  WRITE_LONG 0x1c 0
  WRITE_LONG 0x20 20
  WRITE_LONG 0x24 9
  WRITE_SHORT 0x2c 100
  WRITE_ASCII 0x30 ~d5prpt~ #8
  WRITE_LONG 0x48 102

COPY ~will_to_power/data/d5_base.spl~ ~override/d5prpt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_value% timing = 1 STR_VAR resource = ~d5prfrsh~ END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5prfrsh.spl~ BEGIN
 COPY ~will_to_power/data/d5_base.spl~ ~override/d5prfrsh.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
  PATCH_FOR_EACH points IN ~1~ ~2~ ~3~ ~4~ ~5~ ~6~ ~X~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp-%points%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp_%points%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp+%points%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp&%points%~ END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
END

COPY ~will_to_power/data/d5_base.spl~ ~override/d5prmed.spl~
  SAY NAME1 ~Restorative Meditation~ // ***** @__
  SAY UNIDENTIFIED_DESC ~This ability allows a psion to rest and meditate between combat encounters, recovering a portion of <PRO_HISHER> Psionic Strength Point.~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 location = 4 END
  WRITE_BYTE 0x1a (THIS BOR 0b00000001) 	//	set as non-combat ability
  PATCH_FOR_EACH points IN ~1~ ~2~ ~3~ ~4~ ~5~ ~6~ ~X~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp_%points%~ END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5prmed~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5prmed~ END
//____________________________________________________________________________________


//PSI FEAT FILES______________________________________________________________________
//
COPY ~will_to_power/data/d5psi1.spl~ ~override~
  SAY NAME1 @99
  SAY UNIDENTIFIED_DESC @96
  WRITE_ASCII 0x3a ~d5_feat~ #8
  LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_feat~ END

COPY ~will_to_power/data/d5_feat.bam~ ~override~
COPY ~will_to_power/data/d5_psion.eff~ ~override~ 
COPY ~will_to_power/data/d5_psion.cre~ ~override~ 
COMPILE ~will_to_power/data/d5_psi.baf~ 

COPY_EXISTING ~d5psi1.spl~ ~override/d5psj1.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = EVAL ~d5psj%ind%~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR resource = EVAL ~d5psj%ind%~ END

OUTER_FOR (ind = 2; ind < 50; ++ind) BEGIN
  COPY_EXISTING ~d5psi1.spl~ ~override/d5psi%ind%.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = EVAL ~d5psi%ind%~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR resource = EVAL ~d5psi%ind%~ END
  COPY_EXISTING ~d5psj1.spl~ ~override/d5psj%ind%.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = EVAL ~d5psj%ind%~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR resource = EVAL ~d5psj%ind%~ END
END
//____________________________________________________________________________________


//fix black pits______________________________________________________________________
//
COPY_EXISTING ~ohbantim.spl~ override
  LPF ALTER_EFFECT INT_VAR match_opcode = 144 match_parameter2 = 13 opcode = 145 parameter2 = 3 END
IF_EXISTS BUT_ONLY

// change BP1 to allow innates too
// EDIT - don't need to!

//____________________________________________________________________________________

END	//	end if not already installed

END	//	end function