
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PSIONICS
//__________________________________________________________________________________
//__________________________________________________________________________________



ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_psionics.d5~ BEGIN


//COPY MARKER FILE_________________________________________________________________
//
COPY ~will_to_power/lib/markers/d5_psionics.d5~ ~override~
//__________________________________________________________________________________


/*
//CHANGE CLASS TEXT_________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~THIEF~ BEGIN
	    SET patch_row = %row%
	  END
	END
	SET_2DA_ENTRY %patch_row% 4 cols RESOLVE_STR_REF (@20500)
  BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
  COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~THIEF~ BEGIN
	    SET patch_row = %row%
	  END
	END
	SET_2DA_ENTRY %patch_row% 4 cols RESOLVE_STR_REF (@20500)
  BUT_ONLY
END
//__________________________________________________________________________________
*/


//PREP SPLPROT.2DA__________________________________________________________________
//
APPEND ~splprot.2da~ ~D5_MXHP_GT%TAB%1%TAB%-1%TAB%3~		//	max HP > x
APPEND ~splprot.2da~ ~D5_MXHP_LT%TAB%1%TAB%-1%TAB%2~		//	max HP < x
APPEND ~splprot.2da~ ~D5_134_PSI%TAB%134%TAB%-1%TAB%8~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MXHP_GT~ BEGIN
	  SET maxhp_gt = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MXHP_LT~ BEGIN
	  SET maxhp_lt = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_134_PSI~ BEGIN
	  SET 134_psi = %row%
	END
  END
BUT_ONLY
//__________________________________________________________________________________

//PSIONIC ABILITY FILES_____________________________________________________________
//
COPY ~will_to_power/data/d5ssvbo.spl~ ~override~
	SAY NAME1 @7
COPY ~will_to_power/data/d51hpbo.spl~ ~override~
	SAY NAME1 @7
//
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst4.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 4 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx4~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst6.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 6 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx6~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst9.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 9 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx9~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst20.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 20 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx20~ END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 4) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 6) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx9.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 9) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx20.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 20) parameter2 = 3 timing = 4 duration = 1 END

COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt4.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 4 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx4~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt6.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 6 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx6~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt9.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 9 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx9~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt20.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 20 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx20~ END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 4) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 6) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx9.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 9) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx20.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 20) parameter2 = 3 timing = 4 duration = 1 END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 72 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx9.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 72 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 84 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 96 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 108 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx20.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 72 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 84 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 96 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 108 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 120 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 132 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 144 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 156 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 168 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 180 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 192 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 204 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 216 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 228 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 240 END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrz6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 6 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 18 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 30 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
//__________________________________________________________________________________


//add available spellstates__________________________________________________________
//
LAF d5_resolve_state STR_VAR new_state_id = ~D5_METAPSIONIC~ RET new_state_ind END

OUTER_SET metapsionic_state = %new_state_ind%

LAF d5_resolve_state STR_VAR new_state_id = ~D5_MIND_WARD~ RET new_state_ind END

OUTER_SET mind_ward_state = %new_state_ind%

APPEND ~splprot.2da~ ~D5_STATE_POISON%TAB%0x111%TAB%0x4000%TAB%8~
APPEND ~splprot.2da~ ~D5_STATE_DISEASE%TAB%0x111%TAB%0x80000%TAB%8~

COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols 
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_STATE_POISON~ BEGIN
	    SET state_poison = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_STATE_DISEASE~ BEGIN
	    SET state_disease = %row%
	  END
	END
BUT_ONLY
//__________________________________________________________________________________


//PSIONIC ABILITY FILES_____________________________________________________________
//
COPY ~will_to_power/data/d5ps100.bam~ ~override~
COPY ~will_to_power/data/d5ps200.bam~ ~override~
COPY ~will_to_power/data/d5ps300.bam~ ~override~
COPY ~will_to_power/data/d5ps400.bam~ ~override~
COPY ~will_to_power/data/d5ps500.bam~ ~override~
COPY ~will_to_power/data/d5ps900.bam~ ~override~

COPY ~will_to_power/data/d5ps101.bam~ ~override~
COPY ~will_to_power/data/d5ps101.spl~ ~override~   //  				mind ward 
													// 			prot. vs. fear/charm/sleep/hold
													// 			109 = + confusion/domination/feeblemind/stun/maze
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 328 parameter2 = %mind_ward_state% END
	SAY NAME1 @1011
	SAY UNIDENTIFIED_DESC @1012
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps101~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps101~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps1x1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps101~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt4~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps1x1.spl~
	SAY NAME1 @1013
	SAY UNIDENTIFIED_DESC @1013
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps1x1~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps101~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps1x1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx4~ END
COPY ~will_to_power/data/d5ps1x1.bam~ ~override~

COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  SNPRINT 3 ~spl_prefix~ ~%SOURCE_RES%~
  PATCH_IF NOT (~%spl_prefix%~ STRING_EQUAL_CASE ~#bo~) BEGIN
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 24 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps1z1~ END 	//	panic
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 5 /*match_parameter1 = 1*/ opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps1z1~ END	//	charm
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 39 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps1z1~ END 	//	sleep
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 217 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps1z1~ END 	//	PW sleep
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 175 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps1z1~ END 	//	hold
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 185 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps1z1~ END 	//	hold2
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_target = 2 match_opcode = 247 opcode = 326 target = 2 parameter1 = %mind_ward_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ps1z1~ END 	//	berserk
  END
BUT_ONLY
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps1z1.spl~
	SAY NAME1 @1013
	SAY UNIDENTIFIED_DESC @1013
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps1x1~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 target = 2 STR_VAR resource = ~d5ps101~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 target = 2 STR_VAR resource = ~d5ps1x1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrz4~ END
COPY ~will_to_power/data/d5ps101.spl~ ~override/d5pw101.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps101~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps101~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps101~ END

COPY ~will_to_power/data/d5ps103.bam~ ~override~
COPY ~will_to_power/data/d5ps103.spl~ ~override~   //  				id insinuation
	SAY NAME1 @1031
	SAY UNIDENTIFIED_DESC @1032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps103~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps103~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps103a.spl~ ~override~
	SAY NAME1 @1031
	SAY UNIDENTIFIED_DESC @1032
	WRITE_ASCII 0x3a ~d5ps103~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps103~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 2 parameter2 = 55 timing = 0 duration = 1 STR_VAR resource = ~d5ps103a~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps103a~ END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps103a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps103a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps103a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps103.spl~ ~override/d5pw103.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps103~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps103~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps103~ END
COPY ~will_to_power/data/d5ps103.spl~ ~override/d5pv103.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps103~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps103~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps103~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps104.bam~ ~override~
COPY ~will_to_power/data/d5ps104.spl~ ~override~   //  					ego whip
	SAY NAME1 @1041
	SAY UNIDENTIFIED_DESC @1042
	WRITE_LONG 0x34 3
	WRITE_ASCII 0x3a ~d5ps104~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps104~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps104a.spl~ ~override~
	SAY NAME1 @1041
	SAY UNIDENTIFIED_DESC @1042
	WRITE_ASCII 0x3a ~d5ps104~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps104~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 2 parameter2 = 55 timing = 0 duration = 1 STR_VAR resource = ~d5ps101a~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps101a~ END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps104a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps104a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps104a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps104.spl~ ~override/d5pw104.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps104~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps104~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps104~ END
COPY ~will_to_power/data/d5ps104.spl~ ~override/d5pv104.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps104~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps104~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps104~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps105.bam~ ~override~
COPY ~will_to_power/data/d5ps105.spl~ ~override~   //  				ego repair
	SAY NAME1 @1051
	SAY UNIDENTIFIED_DESC @1052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps105~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps105~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps105a.spl~ ~override~
	SAY NAME1 @1051
	SAY UNIDENTIFIED_DESC @1052
	WRITE_ASCII 0x3a ~d5ps105~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps105~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps105a~ END
COPY ~will_to_power/data/d5ps105.spl~ ~override/d5pw105.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps105~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps105~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps105~ END

COPY ~will_to_power/data/d5ps107.bam~ ~override~
COPY ~will_to_power/data/d5ps107.spl~ ~override~   // 				domination
	SAY NAME1 @1071
	SAY UNIDENTIFIED_DESC @1072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps107~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps107~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst9~ END
COPY ~will_to_power/data/d5ps107a.spl~ ~override~
	SAY NAME1 @1071
	SAY UNIDENTIFIED_DESC @1072
	WRITE_ASCII 0x3a ~d5ps107~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps107~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 2 parameter2 = 55 timing = 0 duration = 1 STR_VAR resource = ~d5ps107a~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps107a~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_savingthrow = 8 savingthrow = 16 END
COPY ~will_to_power/data/d5ps107b.spl~ ~override~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_savingthrow = 8 savingthrow = 16 END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107c.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107d~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107e~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107e.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107f~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107f.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107g~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107g.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107h~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107h.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps107i~ END
COPY ~will_to_power/data/d5ps107b.spl~ ~override/d5ps107i.spl~
	LPF DELETE_EFFECT INT_VAR silent = 1 match_opcode = 146 END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps107a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps107a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps107a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps107.spl~ ~override/d5pw107.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps107~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps107~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps107~ END
COPY ~will_to_power/data/d5ps107.spl~ ~override/d5pv107.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps107~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps107~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps107~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps108.bam~ ~override~
COPY ~will_to_power/data/d5ps108.spl~ ~override~   // 				intellect fortress
	SAY NAME1 @1081
	SAY UNIDENTIFIED_DESC @1082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps108~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps108~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps1x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps108~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt9~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter2 = 110 parameter1 = %mind_ward_state% STR_VAR match_resource = ~d5ps1x1~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps1x8.spl~
	SAY NAME1 @1081
	SAY UNIDENTIFIED_DESC @1082
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps1x8~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps108~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps1x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx9~ END
COPY ~will_to_power/data/d5ps1x8.bam~ ~override~
COPY ~will_to_power/data/d5ps108.spl~ ~override/d5pw108.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps108~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps108~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps108~ END

COPY ~will_to_power/data/d5ps109.bam~ ~override~
COPY ~will_to_power/data/d5ps109.spl~ ~override~   // 				psychic crush
	SAY NAME1 @1091
	SAY UNIDENTIFIED_DESC @1092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps109~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps109~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst9~ END
COPY ~will_to_power/data/d5ps109a.spl~ ~override~
	SAY NAME1 @1091
	SAY UNIDENTIFIED_DESC @1092
	WRITE_ASCII 0x3a ~d5ps109~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps109~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 2 parameter2 = 55 timing = 0 duration = 1 STR_VAR resource = ~d5ps109a~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps109a~ END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps109a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps109a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps109a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps109.spl~ ~override/d5pw109.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps109~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps109~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps109~ END
COPY ~will_to_power/data/d5ps109.spl~ ~override/d5pv109.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps109~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps109~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps109~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps111.bam~ ~override~
COPY ~will_to_power/data/d5ps111.spl~ ~override~ 		//			tower of iron will
	SAY NAME1 @1111
	SAY UNIDENTIFIED_DESC @1112
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps111~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps111~ END
	LPF ADD_SPELL_EFFECT INT_VAR silent = 1 opcode = 93 target = 1 parameter1 = 4 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps1y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps111~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter2 = 110 parameter1 = %mind_ward_state% STR_VAR match_resource = ~d5ps1x1~ END
COPY ~will_to_power/data/d5ps111a.spl~ ~override~
COPY ~will_to_power/data/d5ps111.eff~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps1y1.spl~
	SAY NAME1 @1113
	SAY UNIDENTIFIED_DESC @1113
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps1y1~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps111~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps1y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
COPY ~will_to_power/data/d5ps1y1.bam~ ~override~
COPY ~will_to_power/data/d5ps111.spl~ ~override/d5pw111.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps111~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps111~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps111~ END


COPY ~will_to_power/data/d5ps201.bam~ ~override~
COPY ~will_to_power/data/d5ps201.spl~ ~override~   // 				project force
	SAY NAME1 @2011
	SAY UNIDENTIFIED_DESC @2012
	WRITE_LONG 0x34 3
	WRITE_ASCII 0x3a ~d5ps201~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps201~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst4~ END
COPY ~will_to_power/data/d5ps201a.spl~ ~override~
	SAY NAME1 @2011
	SAY UNIDENTIFIED_DESC @2012
	WRITE_ASCII 0x3a ~d5ps201~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps201~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps201a~ END
COPY ~will_to_power/data/d5ps201.spl~ ~override/d5pw201.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps201~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps201~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps201~ END
COPY ~will_to_power/data/d5ps201.spl~ ~override/d5pv201.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps201~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps201~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps201~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps203.bam~ ~override~
COPY ~will_to_power/data/d5ps203.spl~ ~override~   // 				immobilize
	SAY NAME1 @2031
	SAY UNIDENTIFIED_DESC @2032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps203~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps203~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps203a.spl~ ~override~
	SAY NAME1 @2031
	SAY UNIDENTIFIED_DESC @2032
	WRITE_ASCII 0x3a ~d5ps203~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps203~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps203a~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_savingthrow = 8 savingthrow = 16 END
COPY ~will_to_power/data/d5ps203b.spl~ ~override~
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203c.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203d~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203e~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203e.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203f~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203f.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203g~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203g.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203h~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203h.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203i~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203i.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 STR_VAR resource = ~d5ps203j~ END
COPY ~will_to_power/data/d5ps203b.spl~ ~override/d5ps203j.spl~
	LPF DELETE_EFFECT INT_VAR silent = 1 match_opcode = 146 END
COPY ~will_to_power/data/d5ps203.spl~ ~override/d5pw203.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps203~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps203~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps203~ END
COPY ~will_to_power/data/d5ps203.spl~ ~override/d5pv203.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps203~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps203~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps203~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps204.bam~ ~override~
COPY ~will_to_power/data/d5ps204.spl~ ~override~   // 				inertial barrier
	SAY NAME1 @2041
	SAY UNIDENTIFIED_DESC @2042
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps204~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps204~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps2x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps204~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps2x4.spl~
	SAY NAME1 @2043
	SAY UNIDENTIFIED_DESC @2043
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps2x4~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps204~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps2x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps2x4.bam~ ~override~
COPY ~will_to_power/data/d5ps204.spl~ ~override/d5pw204.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps204~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps204~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps204~ END

COPY ~will_to_power/data/d5ps205.bam~ ~override~
COPY ~will_to_power/data/d5ps205.spl~ ~override~   // 				psychic knife
	SAY NAME1 @2051
	SAY UNIDENTIFIED_DESC @2052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps205~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps205~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps2x5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps205~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps2x5.spl~
	SAY NAME1 @2053
	SAY UNIDENTIFIED_DESC @2053
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps2x5~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps205~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps2x5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5psibla~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps2x5.bam~ ~override~
COPY ~will_to_power/data/d5psibla.itm~ ~override~
	SAY NAME1 @2051
	SAY UNIDENTIFIED_DESC @2051
COPY ~will_to_power/data/d5psibla.bam~ ~override~
COPY ~will_to_power/data/d5ps205.spl~ ~override/d5pw205.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps205~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps205~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps205~ END

COPY ~will_to_power/data/d5ps207.bam~ ~override~
COPY ~will_to_power/data/d5ps207.spl~ ~override~   // 				repulsion
	SAY NAME1 @2071
	SAY UNIDENTIFIED_DESC @2072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps207~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 1 STR_VAR icon = ~d5ps207~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps2x7~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps207~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt9~ END
COPY ~will_to_power/data/d5ps207b.spl~ ~override~
COPY ~will_to_power/data/d5ps207.eff~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps2x7.spl~
	SAY NAME1 @2073
	SAY UNIDENTIFIED_DESC @2073
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps2x7~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps207~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps2x7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx9~ END
COPY ~will_to_power/data/d5ps2x7.bam~ ~override~
COPY ~will_to_power/data/d5ps207.spl~ ~override/d5pw207.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps207~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps207~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps207~ END

COPY ~will_to_power/data/d5ps208.bam~ ~override~
COPY ~will_to_power/data/d5ps208.spl~ ~override~   // 				free action
	SAY NAME1 @2081
	SAY UNIDENTIFIED_DESC @2082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps208~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps208~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps2x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps208~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt9~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps2x8.spl~
	SAY NAME1 @2083
	SAY UNIDENTIFIED_DESC @2083
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps2x8~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps208~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps2x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx9~ END
COPY ~will_to_power/data/d5ps2x8.bam~ ~override~
COPY ~will_to_power/data/d5ps208.spl~ ~override/d5pw208.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps208~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps208~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps208~ END


COPY ~will_to_power/data/d5ps209.bam~ ~override~
COPY ~will_to_power/data/d5ps209.spl~ ~override~   // 				mass immobilize
	SAY NAME1 @2091
	SAY UNIDENTIFIED_DESC @2092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps209~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps209~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst9~ END
COPY ~will_to_power/data/d5ps209a.spl~ ~override~
	SAY NAME1 @2091
	SAY UNIDENTIFIED_DESC @2092
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps209a~ END
COPY ~will_to_power/data/d5ps209.spl~ ~override/d5pw209.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps209~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps209~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps209~ END

COPY ~will_to_power/data/d5ps211.bam~ ~override~
//COPY_EXISTING ~sppr720.spl~ ~override/d5ps211.spl~ 		//			earthquake
COPY ~will_to_power/data/d5ps211.spl~ ~override~ 		//			earthquake
	SAY NAME1 @2111
	SAY UNIDENTIFIED_DESC @2112
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps211~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps211~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 power = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 4 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps211~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY211~ END
COPY ~will_to_power/data/d5ps211b.spl~ ~override~
COPY ~will_to_power/data/d5ps211c.spl~ ~override~
COPY ~will_to_power/data/d5ps211.spl~ ~override/d5pw211.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps211~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps211~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps211~ END
COPY ~will_to_power/data/d5ps211.spl~ ~override/d5pv211.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps211~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps211~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps211~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END


COPY ~will_to_power/data/d5ps301.bam~ ~override~
COPY ~will_to_power/data/d5ps301.spl~ ~override~   //  				static discharge
	SAY NAME1 @3011
	SAY UNIDENTIFIED_DESC @3012
	WRITE_LONG 0x34 3
	WRITE_ASCII 0x3a ~d5ps301~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps301~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps301~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst4~ END
COPY ~will_to_power/data/d5ps301.itm~ ~override~
	SAY NAME1 @3011
	SAY UNIDENTIFIED_DESC @3012
COPY ~will_to_power/data/d5ps301d.spl~ ~override~
	SAY NAME1 @3011
	SAY UNIDENTIFIED_DESC @3012
COPY ~will_to_power/data/d5ps301.spl~ ~override/d5pw301.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps301~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps301~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps301~ END

COPY ~will_to_power/data/d5ps303.bam~ ~override~
COPY ~will_to_power/data/d5ps303.spl~ ~override~   // 				molecular agitation
	SAY NAME1 @3031
	SAY UNIDENTIFIED_DESC @3032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps303~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps303~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps3x3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps303~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps303.eff~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps3x3.spl~
	SAY NAME1 @3033
	SAY UNIDENTIFIED_DESC @3033
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps3x3~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps303~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps3x3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps3x3.bam~ ~override~
COPY ~will_to_power/data/d5ps303.spl~ ~override/d5pw303.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps303~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps303~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps303~ END

COPY ~will_to_power/data/d5ps304.bam~ ~override~
COPY ~will_to_power/data/d5ps304.spl~ ~override~   // 				energy dispersion
	SAY NAME1 @3041
	SAY UNIDENTIFIED_DESC @3042
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps304~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps304~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps3x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps304~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps3x4.spl~
	SAY NAME1 @3043
	SAY UNIDENTIFIED_DESC @3043
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps3x4~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps304~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps3x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps3x4.bam~ ~override~
COPY ~will_to_power/data/d5ps304.spl~ ~override/d5pw304.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps304~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps304~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps304~ END

COPY ~will_to_power/data/d5ps305.bam~ ~override~
// Projectile
COPY ~will_to_power/data/PFIREA.bam~ ~override~
COPY ~will_to_power/data/PFIREX.bam~ ~override~
COPY ~will_to_power/data/#PRFIRE.vvc~ ~override~
COPY ~will_to_power/data/#EFF_P45.WAV~ ~override~
COPY ~will_to_power/data/#ARE_P03.WAV~ ~override~
ADD_PROJECTILE ~will_to_power/data/d5ps305.pro~  	//				projectile
//
/*
COPY ~will_to_power/data/d5ps305.spl~ ~override~   // 				psychic combustion
	SAY NAME1 @3051
	SAY UNIDENTIFIED_DESC @3052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps305~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps305~ END
	WRITE_SHORT 0x98 ~%d5ps305%~  //Projectile
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps305~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
*/
COPY ~will_to_power/data/d5ps305.spl~ ~override/d5pw305.spl~
	SAY NAME1 @3051
	SAY UNIDENTIFIED_DESC @3052
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps305~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps305~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5pw305~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps305b~ END
COPY ~will_to_power/data/d5ps305a.spl~ ~override/d5pw305a.spl~
	SAY NAME1 @3051
	SAY UNIDENTIFIED_DESC @3052
	WRITE_ASCII 0x3a ~d5ps305~ #8
	WRITE_SHORT 0x98 ~%d5ps305%~  //Projectile
	WRITE_SHORT 0xc0 ~%d5ps305%~  //Projectile
	WRITE_SHORT 0xe8 ~%d5ps305%~  //Projectile
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps201~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps305a~ END
COPY ~will_to_power/data/d5ps305.spl~ ~override/d5pv305.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps305~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps305~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 148 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps305~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps307.bam~ ~override~
COPY ~will_to_power/data/d5ps307.spl~ ~override~   // 				solar flash
	SAY NAME1 @3071
	SAY UNIDENTIFIED_DESC @3072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps307~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps307~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps307~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst9~ END
COPY ~will_to_power/data/d5ps307u.eff~ ~override~
COPY ~will_to_power/data/d5ps307.spl~ ~override/d5pw307.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps307~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps307~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps307~ END

COPY ~will_to_power/data/d5ps308.bam~ ~override~
COPY ~will_to_power/data/d5ps308.spl~ ~override~   // 				ice storm
	SAY NAME1 @3081
	SAY UNIDENTIFIED_DESC @3082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps308~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps308~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst9~ END
COPY ~will_to_power/data/d5ps308a.spl~ ~override~
	SAY NAME1 @3081
	SAY UNIDENTIFIED_DESC @3082
	WRITE_ASCII 0x3a ~d5ps308~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps308~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps308a~ END
COPY ~will_to_power/data/d5ps308.spl~ ~override/d5pw308.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps308~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps308~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps308~ END
COPY ~will_to_power/data/d5ps308.spl~ ~override/d5pv308.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps308~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps308~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps308~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps309.bam~ ~override~
COPY ~will_to_power/data/d5ps309.spl~ ~override~   // 				generate lightning
	SAY NAME1 @3091
	SAY UNIDENTIFIED_DESC @3092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps309~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps309~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst9~ END
COPY ~will_to_power/data/d5ps309a.spl~ ~override~
	SAY NAME1 @3091
	SAY UNIDENTIFIED_DESC @3092
	WRITE_ASCII 0x3a ~d5ps309~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps309~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps309a~ END
COPY ~will_to_power/data/d5ps309.spl~ ~override/d5pw309.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps309~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps309~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps309~ END
COPY ~will_to_power/data/d5ps309.spl~ ~override/d5pv309.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps309~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps309~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps309~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps311.bam~ ~override~
COPY ~will_to_power/data/d5ps311.spl~ ~override~ 		//			storm of energy
	SAY NAME1 @3111
	SAY UNIDENTIFIED_DESC @3112
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps311~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps311~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 power = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 4 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY311~ END
COPY ~will_to_power/data/d5ps311a.spl~ ~override~
	SAY NAME1 @3111
	SAY UNIDENTIFIED_DESC @3112
	WRITE_ASCII 0x3a ~d5ps311~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps311~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 2 STR_VAR resource = ~d5ps311a~ END
COPY ~will_to_power/data/d5ps311.spl~ ~override/d5pw311.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps311~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps311~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps311~ END
COPY ~will_to_power/data/d5ps311.spl~ ~override/d5pv311.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps311~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps311~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps311~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END


COPY ~will_to_power/data/d5ps401.bam~ ~override~
COPY ~will_to_power/data/d5ps401.spl~ ~override~   //  				adrenaline rush
	SAY NAME1 @4011
	SAY UNIDENTIFIED_DESC @4012
	WRITE_LONG 0x34 3
	WRITE_ASCII 0x3a ~d5ps401~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps401~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 5 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps401~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst4~ END
COPY ~will_to_power/data/d5ps401a.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~will_to_power/data/d5ps401.spl~ ~override/d5pw401.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps401~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps401~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps401~ END

COPY ~will_to_power/data/d5ps403.bam~ ~override~
COPY ~will_to_power/data/d5ps403.spl~ ~override~   //  				body purification
	SAY NAME1 @4031
	SAY UNIDENTIFIED_DESC @4032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps403~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 0 STR_VAR icon = ~d5ps403~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps403~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps403.spl~ ~override/d5pw403.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps403~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps403~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps403~ END

COPY ~will_to_power/data/d5ps404.bam~ ~override~
COPY ~will_to_power/data/d5ps404.spl~ ~override~   // 				bioregeneration
	SAY NAME1 @4041
	SAY UNIDENTIFIED_DESC @4042
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps404~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps404~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps4x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps404~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps4x4.spl~
	SAY NAME1 @4043
	SAY UNIDENTIFIED_DESC @4043
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps4x4~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps404~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps4x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps4x4.bam~ ~override~
COPY ~will_to_power/data/d5ps404.spl~ ~override/d5pw404.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps404~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps404~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps404~ END

COPY ~will_to_power/data/d5ps405.bam~ ~override~
COPY ~will_to_power/data/d5ps405.spl~ ~override~   //  				poison simulation
	SAY NAME1 @4051
	SAY UNIDENTIFIED_DESC @4052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps405~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps405~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY ~will_to_power/data/d5ps405a.spl~ ~override~
	SAY NAME1 @4051
	SAY UNIDENTIFIED_DESC @4052
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps405a~ END
COPY ~will_to_power/data/d5ps405a.eff~ ~override~
COPY ~will_to_power/data/d5ps405b.eff~ ~override~
COPY ~will_to_power/data/d5ps405c.eff~ ~override~
COPY ~will_to_power/data/d5ps405.spl~ ~override/d5pw405.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps405~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 5 STR_VAR icon = ~d5ps405~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps405~ END

COPY ~will_to_power/data/d5ps407.bam~ ~override~
COPY ~will_to_power/data/d5ps407.spl~ ~override~   //  				absorb infliction
	SAY NAME1 @4071
	SAY UNIDENTIFIED_DESC @4072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps407~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps407~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst9~ END
COPY ~will_to_power/data/d5ps407a.spl~ ~override~
	SAY NAME1 @4071
	SAY UNIDENTIFIED_DESC @4072
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps407a~ END
COPY ~will_to_power/data/d5ps407.spl~ ~override/d5pw407.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps407~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps407~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps407~ END

COPY ~will_to_power/data/d5ps408.bam~ ~override~
COPY ~will_to_power/data/d5ps408.spl~ ~override~   // 				camouflage
	SAY NAME1 @4081
	SAY UNIDENTIFIED_DESC @4082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps408~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps408~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps4x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps408~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt9~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps4x8.spl~
	SAY NAME1 @4083
	SAY UNIDENTIFIED_DESC @4083
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps4x8~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps408~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps4x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx9~ END
COPY ~will_to_power/data/d5ps4x8.bam~ ~override~
COPY ~will_to_power/data/d5ps408.spl~ ~override/d5pw408.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps408~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps408~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps408~ END

COPY ~will_to_power/data/d5ps409.bam~ ~override~
COPY ~will_to_power/data/d5ps409.spl~ ~override~   // 				carapace
	SAY NAME1 @4091
	SAY UNIDENTIFIED_DESC @4092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps409~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps409~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps4x9~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps409~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt9~ END
COPY ~will_to_power/data/d5ps409.eff~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps4x9.spl~
	SAY NAME1 @4093
	SAY UNIDENTIFIED_DESC @4093
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps4x9~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps409~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps4x9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx9~ END
COPY ~will_to_power/data/d5ps4x9.bam~ ~override~
COPY ~will_to_power/data/d5ps409.spl~ ~override/d5pw409.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps409~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps409~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps409~ END

COPY ~will_to_power/data/d5ps411.bam~ ~override~
COPY ~will_to_power/data/d5ps411.spl~ ~override~   // 				bestial transformation
	SAY NAME1 @4111
	SAY UNIDENTIFIED_DESC @4112
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps411~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps411~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps4y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps411~ END
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END // uncomment line to pay up-front
COPY ~will_to_power/data/d5ps411.cre~ ~override~
COPY ~will_to_power/data/d5ps411.itm~ ~override~
	SAY NAME1 @4111
	SAY UNIDENTIFIED_DESC @4111
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps4y1.spl~
	SAY NAME1 @4113
	SAY UNIDENTIFIED_DESC @4113
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps4y1~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps411~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps4y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx20~ END // or rx20 if pay up-front
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 0 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 1 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 2 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 3 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 4 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 5 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 7 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 14 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps411~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 135 target = 1 parameter1 = 0 parameter2 = 0 timing = 9 END
COPY ~will_to_power/data/d5ps4y1.bam~ ~override~
COPY ~will_to_power/data/d5ps411.spl~ ~override/d5pw411.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps411~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps411~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps411~ END

/*
COPY ~will_to_power/data/d5ps501.bam~ ~override~
COPY ~will_to_power/data/d5ps501.spl~ ~override~   // 				object reading
*/
COPY ~will_to_power/data/d5ps503.bam~ ~override~
COPY ~will_to_power/data/d5ps503.spl~ ~override~   // 				insightful strike
	SAY NAME1 @5031
	SAY UNIDENTIFIED_DESC @5032
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps503~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps503~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps5x3~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps503~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5x3.spl~
	SAY NAME1 @5033
	SAY UNIDENTIFIED_DESC @5033
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5x3~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps503~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5x3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps5x3.eff~ ~override~
/*
COPY_EXISTING ~d5ps5x3.spl~ ~override/d5ps5xx3.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_target = 1 target = 9 END
*/
COPY ~will_to_power/data/d5ps5x3.bam~ ~override~
COPY ~will_to_power/data/d5ps503.spl~ ~override/d5pw503.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps503~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps503~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps503~ END

COPY ~will_to_power/data/d5ps504.bam~ ~override~
COPY ~will_to_power/data/d5ps504.spl~ ~override~   // 				instinctive luck
	SAY NAME1 @5041
	SAY UNIDENTIFIED_DESC @5042
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps504~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps504~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps5x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps504~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5x4.spl~
	SAY NAME1 @5043
	SAY UNIDENTIFIED_DESC @5043
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5x4~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps504~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
COPY ~will_to_power/data/d5ps5x4.bam~ ~override~
COPY ~will_to_power/data/d5ps504.spl~ ~override/d5pw504.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps504~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps504~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps504~ END


COPY ~will_to_power/data/d5ps505.bam~ ~override~
COPY ~will_to_power/data/d5ps505.spl~ ~override~   // 				clairvoyant sight
	SAY NAME1 @5051
	SAY UNIDENTIFIED_DESC @5052
	WRITE_LONG 0x34 5
	WRITE_ASCII 0x3a ~d5ps505~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps505~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 239 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps505~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END
COPY_EXISTING ~spwi424.spl~ ~override/d5pw505.spl~
//	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps505~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps505~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 174 END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 239 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps505~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst6~ END


COPY ~will_to_power/data/d5ps507.bam~ ~override~
COPY ~will_to_power/data/d5ps507.spl~ ~override~   // 				precognition
	SAY NAME1 @5071
	SAY UNIDENTIFIED_DESC @5072
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps507~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 0 STR_VAR icon = ~d5ps507~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst9~ END
COPY ~will_to_power/data/d5ps507a.spl~ ~override~
	SAY NAME1 @5071
	SAY UNIDENTIFIED_DESC @5072
	WRITE_ASCII 0x3a ~d5ps507~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps507~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps507a~ END

COPY ~will_to_power/data/d5ps507.spl~ ~override/d5pw507.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps507~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps507~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps507~ END


COPY ~will_to_power/data/d5ps508.bam~ ~override~
COPY ~will_to_power/data/d5ps508.spl~ ~override~   //  				life detection
	SAY NAME1 @5081
	SAY UNIDENTIFIED_DESC @5082
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps508~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps508~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps1x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps104~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt9~ END
COPY ~will_to_power/data/d5ps508b.spl~ ~override~
COPY ~will_to_power/data/d5ps508.eff~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5x8.spl~
	SAY NAME1 @5083
	SAY UNIDENTIFIED_DESC @5083
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5x8~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps508~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx9~ END
COPY ~will_to_power/data/d5ps5x8.bam~ ~override~
COPY ~will_to_power/data/d5ps508.spl~ ~override/d5pw508.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps508~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps508~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps508~ END

// add sanctuary to invisibility to make life detection work
INCLUDE ~%MOD_FOLDER%/lib/d5_insanctibility.tpa~
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_insanctibility.d5~ BEGIN
  LAM D5_INSANCTIBILITY
END

COPY ~will_to_power/data/d5ps509.bam~ ~override~
COPY ~will_to_power/data/d5ps509.spl~ ~override~   // 				danger sense
	SAY NAME1 @5091
	SAY UNIDENTIFIED_DESC @5092
	WRITE_LONG 0x34 8
	WRITE_ASCII 0x3a ~d5ps509~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps509~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps5x9~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 10 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps509~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt9~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5x9.spl~
	SAY NAME1 @5093
	SAY UNIDENTIFIED_DESC @5093
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5x9~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps509~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5x9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx9~ END
COPY ~will_to_power/data/d5ps5x9.bam~ ~override~
COPY ~will_to_power/data/d5ps509.spl~ ~override/d5pw509.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps509~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps509~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps509~ END

// process spells to make evasion work
OUTER_SET optional_evade = 1
INCLUDE ~%MOD_FOLDER%/lib/spell_evasion/spell_evasion.tpa~
ACTION_PHP_EACH evade_spells AS evadable_spell => ind BEGIN 
  LAF add_evade_spell INT_VAR evasion_spellstate = 252 evasion_save = 2 STR_VAR evade_spell = EVAL ~%evadable_spell%~ evade_prefix = ~D5EV~ END
END

COPY ~will_to_power/data/d5ps511.bam~ ~override~
COPY ~will_to_power/data/d5ps511.spl~ ~override~    	// 			clairvoyant channeling
	SAY NAME1 @5111
	SAY UNIDENTIFIED_DESC @5112
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps511~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps511~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps5y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps511~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = %metapsionic_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5ps511a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = %metapsionic_state% parameter2 = 110 timing = 1 STR_VAR resource = ~d5ps511b~ END
COPY ~will_to_power/data/d5ps511a.spl~ ~override~
COPY ~will_to_power/data/d5ps511b.spl~ ~override~
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps5y1.spl~
	SAY NAME1 @5113
	SAY UNIDENTIFIED_DESC @5113
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps5y1~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps511~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps5y1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps500~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps5900~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = %metapsionic_state% parameter2 = 111 timing = 1 STR_VAR resource = ~d5ps511c~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 parameter1 = %metapsionic_state% parameter2 = 110 timing = 1 STR_VAR resource = ~d5ps511d~ END
COPY ~will_to_power/data/d5ps5y1.bam~ ~override~
COPY ~will_to_power/data/d5ps511c.spl~ ~override~
COPY ~will_to_power/data/d5ps511d.spl~ ~override~
COPY ~will_to_power/data/d5ps511.spl~ ~override/d5pw511.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps511~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps511~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps511~ END


COPY ~will_to_power/data/d5ps901.bam~ ~override~
COPY ~will_to_power/data/d5ps901.spl~ ~override~ 	//				ultrablast
	SAY NAME1 @9011
	SAY UNIDENTIFIED_DESC @9012
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps901~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps901~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY901~ END
COPY ~will_to_power/data/d5ps901a.spl~ ~override~
	SAY NAME1 @9011
	SAY UNIDENTIFIED_DESC @9012
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 2 STR_VAR resource = ~d5ps901a~ END
ACTION_IF FILE_EXISTS_IN_GAME ~sppr508.spl~ BEGIN
  COPY_EXISTING ~sppr508.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps901a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ohtyr1.spl~ BEGIN
  COPY_EXISTING ~ohtyr1.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps901a~ END
  BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 ACTION_IF FILE_EXISTS_IN_GAME ~spwi802.spl~ BEGIN
  COPY_EXISTING ~spwi802.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 101 opcode = 206 STR_VAR resource = ~d5ps901a~ END
  BUT_ONLY
 END
END
COPY ~will_to_power/data/d5ps901.spl~ ~override/d5pw901.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps901~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps901~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps901~ END

COPY ~will_to_power/data/d5ps902.bam~ ~override~
COPY ~will_to_power/data/d5ps902.spl~ ~override~ 		//			energy construct
	SAY NAME1 @9021
	SAY UNIDENTIFIED_DESC @9022
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps902~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps902~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps902~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY902~ END
COPY ~will_to_power/data/d5ps902.eff~ ~override~
COPY ~will_to_power/data/d5ps902.spl~ ~override/d5pw902.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps902~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps902~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 148 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps902~ END
COPY ~will_to_power/data/d5ps902.spl~ ~override/d5pv902.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps902~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps902~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 148 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps902~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps903.bam~ ~override~
COPY ~will_to_power/data/d5ps903.spl~ ~override~ 		//			fission
	SAY NAME1 @9031
	SAY UNIDENTIFIED_DESC @9032
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps903~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps903~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 4 duration = 2 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps903~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY903~ END
COPY ~will_to_power/data/d5ps903a.spl~ ~override~
	SAY NAME1 @9031
	SAY UNIDENTIFIED_DESC @9032
COPY ~will_to_power/data/d5ps903b.spl~ ~override~
	SAY NAME1 @9031
	SAY UNIDENTIFIED_DESC @9032
COPY ~will_to_power/data/d5ps903.spl~ ~override/d5pw903.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps903~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps903~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps903~ END

COPY ~will_to_power/data/d5ps904.bam~ ~override~
COPY ~will_to_power/data/d5ps904.spl~ ~override~ 		//			atomic disruption
	SAY NAME1 @9041
	SAY UNIDENTIFIED_DESC @9042
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps904~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps904~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 4 duration = 2 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY904~ END
COPY ~will_to_power/data/d5ps904a.spl~ ~override~
	SAY NAME1 @9041
	SAY UNIDENTIFIED_DESC @9042
	WRITE_ASCII 0x3a ~d5ps904~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps904~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 9 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps904a~ END
COPY ~will_to_power/data/d5ps904.spl~ ~override/d5pw904.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps904~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps904~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps904~ END
COPY ~will_to_power/data/d5ps904.spl~ ~override/d5pv904.spl~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps904~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps904~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps904~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps5y1~ END

COPY ~will_to_power/data/d5ps905.bam~ ~override~
COPY ~will_to_power/data/d5ps905.spl~ ~override~   	// 				exoskeleton
	SAY NAME1 @9051
	SAY UNIDENTIFIED_DESC @9052
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps905~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps905~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps9x5~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps905~ END
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END // uncomment line to pay up-front
COPY ~will_to_power/data/d5ps905.cre~ ~override~
COPY ~will_to_power/data/d5ps905.itm~ ~override~
	SAY NAME1 @9051
	SAY UNIDENTIFIED_DESC @9051
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps9x5.spl~
	SAY NAME1 @9053
	SAY UNIDENTIFIED_DESC @9053
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps9x5~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps905~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps9x5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx20~ END // or rx20 if pay up-front
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 0 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 1 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 2 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 3 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 4 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 5 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 7 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 14 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps905~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 135 target = 1 parameter1 = 0 parameter2 = 0 timing = 9 END
COPY ~will_to_power/data/d5ps9x5.bam~ ~override~
COPY ~will_to_power/data/d5ps905.spl~ ~override/d5pw905.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps905~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps905~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps905~ END

COPY ~will_to_power/data/d5ps906.bam~ ~override~
COPY ~will_to_power/data/d5ps906.spl~ ~override~   	// 				elemental composition
	SAY NAME1 @9061
	SAY UNIDENTIFIED_DESC @9052
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps906~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps906~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps9x6~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps906~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps9x6.spl~
	SAY NAME1 @9063
	SAY UNIDENTIFIED_DESC @9063
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps9x6~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps906~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps9x6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 0 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 1 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 2 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 3 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 4 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 5 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 7 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 279 target = 1 parameter2 = 14 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps906e~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps906f~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5ps906i~ END
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 135 target = 1 parameter1 = 0 parameter2 = 0 timing = 9 END
COPY ~will_to_power/data/d5ps9x6.bam~ ~override~
COPY ~will_to_power/data/d5_ps906.2da~ ~override~
COPY ~will_to_power/data/d5ps906e.spl~ ~override~
	SAY NAME1 @9066
	SAY UNIDENTIFIED_DESC @9066
	WRITE_ASCII 0x3a ~d5ps906e~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps906e~ END
COPY ~will_to_power/data/d5ps906e.cre~ ~override~
COPY ~will_to_power/data/d5ps906e.itm~ ~override~
	SAY NAME1 @9066
	SAY UNIDENTIFIED_DESC @9066
COPY ~will_to_power/data/d5ps906e.bam~ ~override~
COPY ~will_to_power/data/d5ps906f.spl~ ~override~
	SAY NAME1 @9067
	SAY UNIDENTIFIED_DESC @9066
	WRITE_ASCII 0x3a ~d5ps906f~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps906f~ END
COPY ~will_to_power/data/d5ps906f.cre~ ~override~
COPY ~will_to_power/data/d5ps906f.itm~ ~override~
	SAY NAME1 @9067
	SAY UNIDENTIFIED_DESC @9067
COPY ~will_to_power/data/d5ps906f.bam~ ~override~
COPY ~will_to_power/data/d5ps906i.spl~ ~override~
	SAY NAME1 @9068
	SAY UNIDENTIFIED_DESC @9068
	WRITE_ASCII 0x3a ~d5ps906i~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps906i~ END
COPY ~will_to_power/data/d5ps906i.cre~ ~override~
COPY ~will_to_power/data/d5ps906i.itm~ ~override~
	SAY NAME1 @9068
	SAY UNIDENTIFIED_DESC @9068
COPY ~will_to_power/data/d5ps906i.bam~ ~override~
COPY ~will_to_power/data/d5ps906.spl~ ~override/d5pw906.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps906~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps906~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps906~ END

COPY ~will_to_power/data/d5ps907.bam~ ~override~
COPY ~will_to_power/data/d5ps907.spl~ ~override~ 		//			project mind
	SAY NAME1 @9071
	SAY UNIDENTIFIED_DESC @9072
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps907~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps907~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 4 duration = 2 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps907~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps907b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = ~d5psrx4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = ~d5psrx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = ~d5psrx9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 7 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 9 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 11 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 12 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 13 timing = 1 END
COPY ~will_to_power/data/d5ps907.spl~ ~override/d5pw907.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps907~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps907~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps907~ END

COPY ~will_to_power/data/d5ps908.bam~ ~override~
COPY ~will_to_power/data/d5ps908.spl~ ~override~    	// 			dimensional anchor
	SAY NAME1 @9081
	SAY UNIDENTIFIED_DESC @9082
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps908~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps908~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps9x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps908~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt20~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps9x8.spl~
	SAY NAME1 @9083
	SAY UNIDENTIFIED_DESC @9083
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps9x8~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps908~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps9x8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
COPY ~will_to_power/data/d5ps9x8.bam~ ~override~
COPY ~will_to_power/data/d5ps908.spl~ ~override/d5pw908.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps908~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps908~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps908~ END

COPY ~will_to_power/data/d5ps909.bam~ ~override~
COPY ~will_to_power/data/d5ps909.spl~ ~override~ 		//			stasis field
	SAY NAME1 @9091
	SAY UNIDENTIFIED_DESC @9092
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps909~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 4 STR_VAR icon = ~d5ps909~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps909~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 60 STR_VAR resource = EVAL ~D5PY909~ END
COPY ~will_to_power/data/d5ps909.spl~ ~override/d5pw909.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps909~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps909~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps909~ END

COPY ~will_to_power/data/d5ps910.bam~ ~override~
COPY ~will_to_power/data/d5ps910.spl~ ~override~   	// 			body control/directed evolution
	SAY NAME1 @9101
	SAY UNIDENTIFIED_DESC @9102
	WRITE_LONG 0x34 9
	WRITE_ASCII 0x3a ~d5ps910~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 2 STR_VAR icon = ~d5ps910~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 parameter1 = 0 parameter2 = 0 timing = 1 STR_VAR resource = ~d5ps3x4~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps304~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnt6~ END
COPY ~will_to_power/data/d5ps910a.bam~ ~override~
COPY ~will_to_power/data/d5ps91a.spl~ ~override~
	SAY NAME1 @91001
	SAY UNIDENTIFIED_DESC @91001
	WRITE_ASCII 0x3a ~d5ps910a~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910b.bam~ ~override~
COPY ~will_to_power/data/d5ps91b.spl~ ~override~
	SAY NAME1 @91002
	SAY UNIDENTIFIED_DESC @91002
	WRITE_ASCII 0x3a ~d5ps910b~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910c.bam~ ~override~
COPY ~will_to_power/data/d5ps91c.spl~ ~override~
	SAY NAME1 @91003
	SAY UNIDENTIFIED_DESC @91003
	WRITE_ASCII 0x3a ~d5ps910c~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910c~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910d.bam~ ~override~
COPY ~will_to_power/data/d5ps91d.spl~ ~override~
	SAY NAME1 @91004
	SAY UNIDENTIFIED_DESC @91004
	WRITE_ASCII 0x3a ~d5ps910dd~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910e.bam~ ~override~
COPY ~will_to_power/data/d5ps91e.spl~ ~override~
	SAY NAME1 @91005
	SAY UNIDENTIFIED_DESC @91005
	WRITE_ASCII 0x3a ~d5ps910e~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910e~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910f.bam~ ~override~
COPY ~will_to_power/data/d5ps91f.spl~ ~override~
	SAY NAME1 @91006
	SAY UNIDENTIFIED_DESC @91006
	WRITE_ASCII 0x3a ~d5ps910f~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910f~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910g.bam~ ~override~
COPY ~will_to_power/data/d5ps91g.spl~ ~override~
	SAY NAME1 @91007
	SAY UNIDENTIFIED_DESC @91007
	WRITE_ASCII 0x3a ~d5ps910g~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910g~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps910h.bam~ ~override~
COPY ~will_to_power/data/d5ps91h.spl~ ~override~
	SAY NAME1 @91008
	SAY UNIDENTIFIED_DESC @91008
	WRITE_ASCII 0x3a ~d5ps910h~ #8
	LPF ALTER_SPELL_HEADER INT_VAR STR_VAR icon = ~d5ps910h~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = EVAL ~%subspell%~ END
	END
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%SOURCE_RES%~ END
COPY ~will_to_power/data/d5ps_x_.spl~ ~override/d5ps9y0.spl~
	SAY NAME1 @9103
	SAY UNIDENTIFIED_DESC @9103
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5ps9y0~ END
//	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 321 STR_VAR resource = ~d5ps910~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = ~d5ps9y0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	PATCH_FOR_EACH subspell IN ~d5ps91a~ ~d5ps91b~ ~d5ps91c~ ~d5ps91d~ ~d5ps91e~ ~d5ps91f~ ~d5ps91g~ ~d5ps91h~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%subspell%~ END
	END
COPY ~will_to_power/data/d5ps9y0.bam~ ~override~
COPY ~will_to_power/data/d5ps910.spl~ ~override/d5pw910.spl~
	WRITE_BYTE 0x19 (THIS BAND 0b11110111)
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x3a ~d5ps910~ #8
	LPF ALTER_SPELL_HEADER INT_VAR range = 30 STR_VAR icon = ~d5ps910~ END
	LPF DELETE_EFFECT END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 2 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5ps910~ END

//end ability files_________________________________________________________________


//PSI ITEM FILES____________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~itemspec.2da~ BEGIN
  APPEND ~itemspec.2da~ ~d5ps000	1~
  APPEND ~itemspec.2da~ ~d5ps500	1~
  APPEND ~itemspec.2da~ ~d5ps900	1~
  APPEND ~itemspec.2da~ ~d5ps5900	1~
END

COPY ~will_to_power/data/d5ps000.spl~ ~override~

COPY ~will_to_power/data/d5ps000.itm~ ~override~
//COPY ~will_to_power/data/d5ps900.itm~ ~override/d5ps000.itm~
//	LPF ALTER_ITEM_HEADER INT_VAR target = 7 END
//	LPF ALTER_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 177 timing = 1 STR_VAR match_resource = ~d5py101~ END
  PATCH_FOR_EACH ind IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
   PATCH_FOR_EACH abil IN ~01~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pw%ind%%abil%~ END
	PATCH_IF FILE_EXISTS_IN_GAME ~d5pv%ind%%abil%~ BEGIN
	  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pv%ind%%abil%~ END
	END
   END
  END
  LPF DELETE_EFFECT INT_VAR header = 0 match_opcode = 172 END
  PATCH_FOR_EACH abil IN ~01~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 2 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY1%abil%~ END
	LPF ADD_ITEM_EFFECT INT_VAR header = 3 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY2%abil%~ END
	LPF ADD_ITEM_EFFECT INT_VAR header = 4 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY3%abil%~ END
	LPF ADD_ITEM_EFFECT INT_VAR header = 5 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY4%abil%~ END
	LPF ADD_ITEM_EFFECT INT_VAR header = 6 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY5%abil%~ END
  END
  PATCH_FOR_EACH hla IN ~01~ ~02~ ~03~ ~04~ ~05~ ~06~ ~07~ ~08~ ~09~ ~10~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 7 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY9%hla%~ END
  END
  LPF ADD_ITEM_EFFECT INT_VAR header = 2 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 3 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 4 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 5 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 6 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 7 opcode = 214 target = 1 parameter2 = 1 timing = 1 END

COPY ~will_to_power/data/d5ps5900.itm~ ~override/d5ps500.itm~
  LPF DELETE_EFFECT INT_VAR match_opcode = 335 END
//	LPF ALTER_ITEM_HEADER INT_VAR target = 7 END
//	LPF ALTER_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 177 timing = 1 STR_VAR match_resource = ~d5py101~ END
  PATCH_FOR_EACH ind IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
   PATCH_FOR_EACH abil IN ~01~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pw%ind%%abil%~ END
	PATCH_IF FILE_EXISTS_IN_GAME ~d5pv%ind%%abil%~ BEGIN
	  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pv%ind%%abil%~ END
	END
   END
  END
  LPF DELETE_EFFECT INT_VAR header = 0 match_opcode = 172 END
  PATCH_FOR_EACH abil IN ~01~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
   PATCH_IF FILE_EXISTS_IN_GAME ~d5pv1%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 2 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PU1%abil%~ END
   END
   PATCH_IF NOT FILE_EXISTS_IN_GAME ~d5pv1%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 2 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY1%abil%~ END
   END
   PATCH_IF FILE_EXISTS_IN_GAME ~d5pv2%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 3 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PU2%abil%~ END
   END
   PATCH_IF NOT FILE_EXISTS_IN_GAME ~d5pv2%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 3 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY2%abil%~ END
   END
   PATCH_IF FILE_EXISTS_IN_GAME ~d5pv3%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 4 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PU3%abil%~ END
   END
   PATCH_IF NOT FILE_EXISTS_IN_GAME ~d5pv3%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 4 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY3%abil%~ END
   END
   PATCH_IF FILE_EXISTS_IN_GAME ~d5pv4%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 5 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PU4%abil%~ END
   END
   PATCH_IF NOT FILE_EXISTS_IN_GAME ~d5pv4%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 5 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY4%abil%~ END
   END
   PATCH_IF FILE_EXISTS_IN_GAME ~d5pv5%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 6 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PU5%abil%~ END
   END
   PATCH_IF NOT FILE_EXISTS_IN_GAME ~d5pv5%abil%~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 6 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY5%abil%~ END
   END
  END
  PATCH_FOR_EACH hla IN ~01~ ~02~ ~03~ ~04~ ~05~ ~06~ ~07~ ~08~ ~09~ ~10~ BEGIN
	LPF ADD_ITEM_EFFECT INT_VAR header = 7 opcode = 177 target = 1 parameter2 = 2 timing = 0 STR_VAR resource = EVAL ~D5PY9%hla%~ END
  END
  LPF ADD_ITEM_EFFECT INT_VAR header = 2 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 3 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 4 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 5 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 6 opcode = 214 target = 1 parameter2 = 1 timing = 1 END
  LPF ADD_ITEM_EFFECT INT_VAR header = 7 opcode = 214 target = 1 parameter2 = 1 timing = 1 END

/*
COPY ~will_to_power/data/d5ps500.itm~ ~override~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = ~d5pw101~ resource = ~d5pv101~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3680 STR_VAR resource = ~d5pv103~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3681 STR_VAR resource = ~d5pw104~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3682 STR_VAR resource = ~d5pw105~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3683 STR_VAR resource = ~d5pv107~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3684 STR_VAR resource = ~d5pw108~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3685 STR_VAR resource = ~d5pv109~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3686 STR_VAR resource = ~d5pw111~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = ~d5pw201~ resource = ~d5pv201~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3688 STR_VAR resource = ~d5pv203~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3689 STR_VAR resource = ~d5pw204~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3690 STR_VAR resource = ~d5pw205~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3691 STR_VAR resource = ~d5pw207~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3692 STR_VAR resource = ~d5pw208~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3693 STR_VAR resource = ~d5pw209~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3694 STR_VAR resource = ~d5pv211~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3696 STR_VAR resource = ~d5pw303~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3697 STR_VAR resource = ~d5pw304~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3698 STR_VAR resource = ~d5pv305~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3699 STR_VAR resource = ~d5pw307~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3700 STR_VAR resource = ~d5pv308~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3701 STR_VAR resource = ~d5pv309~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3702 STR_VAR resource = ~d5pv311~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3616 STR_VAR resource = ~d5pw403~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3617 STR_VAR resource = ~d5pw404~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3618 STR_VAR resource = ~d5pw405~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3619 STR_VAR resource = ~d5pw407~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3620 STR_VAR resource = ~d5pw408~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3621 STR_VAR resource = ~d5pw409~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3622 STR_VAR resource = ~d5pw411~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3624 STR_VAR resource = ~d5pw503~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3625 STR_VAR resource = ~d5pw504~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3626 STR_VAR resource = ~d5pw505~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3627 STR_VAR resource = ~d5pw507~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3628 STR_VAR resource = ~d5pw508~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3629 STR_VAR resource = ~d5pw509~ END
//	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3630 STR_VAR resource = ~d5pw511~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 335 header = 6 STR_VAR match_resource = ~d5pw101~ END

COPY ~will_to_power/data/d5ps900.itm~ ~override~
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3680 STR_VAR resource = ~d5pw103~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3681 STR_VAR resource = ~d5pw104~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3682 STR_VAR resource = ~d5pw105~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3683 STR_VAR resource = ~d5pw107~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3684 STR_VAR resource = ~d5pw108~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3685 STR_VAR resource = ~d5pw109~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3686 STR_VAR resource = ~d5pw111~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3688 STR_VAR resource = ~d5pw203~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3689 STR_VAR resource = ~d5pw204~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3690 STR_VAR resource = ~d5pw205~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3691 STR_VAR resource = ~d5pw207~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3692 STR_VAR resource = ~d5pw208~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3693 STR_VAR resource = ~d5pw209~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3694 STR_VAR resource = ~d5pw211~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3696 STR_VAR resource = ~d5pw303~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3697 STR_VAR resource = ~d5pw304~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3698 STR_VAR resource = ~d5pw305~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3699 STR_VAR resource = ~d5pw307~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3700 STR_VAR resource = ~d5pw308~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3701 STR_VAR resource = ~d5pw309~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3702 STR_VAR resource = ~d5pw311~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3616 STR_VAR resource = ~d5pw403~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3617 STR_VAR resource = ~d5pw404~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3618 STR_VAR resource = ~d5pw405~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3619 STR_VAR resource = ~d5pw407~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3620 STR_VAR resource = ~d5pw408~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3621 STR_VAR resource = ~d5pw409~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3622 STR_VAR resource = ~d5pw411~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3624 STR_VAR resource = ~d5pw503~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3625 STR_VAR resource = ~d5pw504~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3626 STR_VAR resource = ~d5pw505~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3627 STR_VAR resource = ~d5pw507~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3628 STR_VAR resource = ~d5pw508~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3629 STR_VAR resource = ~d5pw509~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3630 STR_VAR resource = ~d5pw511~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3632 STR_VAR resource = ~d5pw901~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3633 STR_VAR resource = ~d5pw902~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3634 STR_VAR resource = ~d5pw903~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3635 STR_VAR resource = ~d5pw904~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3636 STR_VAR resource = ~d5pw905~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3637 STR_VAR resource = ~d5pw906~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3638 STR_VAR resource = ~d5pw907~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3640 STR_VAR resource = ~d5pw908~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3641 STR_VAR resource = ~d5pw909~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3642 STR_VAR resource = ~d5pw910~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 335 header = 6 STR_VAR match_resource = ~d5pw101~ END

COPY ~will_to_power/data/d5ps5900.itm~ ~override~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = ~d5pw101~ resource = ~d5pv101~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3680 STR_VAR resource = ~d5pv103~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3681 STR_VAR resource = ~d5pw104~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3682 STR_VAR resource = ~d5pw105~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3683 STR_VAR resource = ~d5pv107~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3684 STR_VAR resource = ~d5pw108~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3685 STR_VAR resource = ~d5pv109~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 1 match_opcode = 335 parameter1 = 3686 STR_VAR resource = ~d5pw111~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR match_resource = ~d5pw201~ resource = ~d5pv201~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3688 STR_VAR resource = ~d5pv203~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3689 STR_VAR resource = ~d5pw204~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3690 STR_VAR resource = ~d5pw205~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3691 STR_VAR resource = ~d5pw207~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3692 STR_VAR resource = ~d5pw208~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3693 STR_VAR resource = ~d5pw209~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 2 match_opcode = 335 parameter1 = 3694 STR_VAR resource = ~d5pv211~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3696 STR_VAR resource = ~d5pw303~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3697 STR_VAR resource = ~d5pw304~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3698 STR_VAR resource = ~d5pv305~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3699 STR_VAR resource = ~d5pw307~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3700 STR_VAR resource = ~d5pv308~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3701 STR_VAR resource = ~d5pv309~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 3 match_opcode = 335 parameter1 = 3702 STR_VAR resource = ~d5pv311~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3616 STR_VAR resource = ~d5pw403~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3617 STR_VAR resource = ~d5pw404~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3618 STR_VAR resource = ~d5pw405~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3619 STR_VAR resource = ~d5pw407~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3620 STR_VAR resource = ~d5pw408~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3621 STR_VAR resource = ~d5pw409~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 4 match_opcode = 335 parameter1 = 3622 STR_VAR resource = ~d5pw411~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3624 STR_VAR resource = ~d5pw503~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3625 STR_VAR resource = ~d5pw504~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3626 STR_VAR resource = ~d5pw505~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3627 STR_VAR resource = ~d5pw507~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3628 STR_VAR resource = ~d5pw508~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3629 STR_VAR resource = ~d5pw509~ END
//	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 5 match_opcode = 335 parameter1 = 3630 STR_VAR resource = ~d5pw511~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3632 STR_VAR resource = ~d5pw901~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3633 STR_VAR resource = ~d5pv902~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3634 STR_VAR resource = ~d5pw903~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3635 STR_VAR resource = ~d5pv904~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3636 STR_VAR resource = ~d5pw905~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3637 STR_VAR resource = ~d5pw906~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3638 STR_VAR resource = ~d5pw907~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3640 STR_VAR resource = ~d5pw908~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3641 STR_VAR resource = ~d5pw909~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 header = 6 match_opcode = 335 parameter1 = 3642 STR_VAR resource = ~d5pw910~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 335 header = 6 STR_VAR match_resource = ~d5pw101~ END
*/
//end item files____________________________________________________________________


//LEARN NEW ABILITIES_______________________________________________________________
//
// d5py = add ability at time of use (EFF with 171)
// d5pz = cannot use ("unlearn" at level 1 - 206 vs. d5py)
// d5px = learn ability (cancel d5pz)
COPY ~will_to_power/data/d5pz000.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz104~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz105~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz107~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz108~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz109~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz111~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz203~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz204~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz205~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz207~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz208~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz209~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz211~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz303~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz304~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz305~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz307~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz308~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz309~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz311~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz403~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz404~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz405~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz407~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz408~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz409~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz411~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz503~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz504~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz505~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz507~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz508~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz509~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz511~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz901~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz902~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz903~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz904~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz905~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz906~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz907~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz908~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz909~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 146 STR_VAR resource = ~d5pz910~ END

ACTION_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
 ACTION_FOR_EACH abil IN ~01~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
  CREATE EFF ~d5py%disc%%abil%~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 0
	WRITE_LONG 0x28 1
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~d5pw%disc%%abil%~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5PY%disc%%abil%~ #8
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5pz%disc%%abil%.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~D5PY%disc%%abil%~ END
	PATCH_IF FILE_EXISTS_IN_GAME ~d5pv%disc%%abil%.spl~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~D5PU%disc%%abil%~ END
	END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5px%disc%%abil%.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pz%disc%%abil%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5pz%disc%%abil%~ END
// handle long-range versions
  ACTION_IF FILE_EXISTS_IN_GAME ~d5pv%disc%%abil%.spl~ BEGIN
	CREATE EFF ~d5pu%disc%%abil%~
	 WRITE_LONG 0x10 171
	 WRITE_LONG 0x14 1
	 WRITE_LONG 0x24 0
	 WRITE_LONG 0x28 1
	 WRITE_SHORT 0x2c 100
	 WRITE_EVALUATED_ASCII 0x30 ~d5pv%disc%%abil%~ #8
	 WRITE_LONG 0x90 1
	 WRITE_EVALUATED_ASCII 0x94 ~D5PU%disc%%abil%~ #8
  END
 END
END
//
ACTION_FOR_EACH hla IN ~01~ ~02~ ~03~ ~04~ ~05~ ~06~ ~07~ ~08~ ~09~ ~10~ BEGIN
  CREATE EFF ~d5py9%hla%~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 0
	WRITE_LONG 0x28 1
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~d5pw9%hla%~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5PY9%hla%~ #8
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5pz9%hla%.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~D5PY9%hla%~ END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5px9%hla%.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pz9%hla%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5pz9%hla%~ END
//	LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 parameter2 = %metapsionic_state% timing = 9 special = 1 END
END
//__________________________________________________________________________________


//PSI FEAT FILES____________________________________________________________________
//
COPY ~will_to_power/data/d5psi1.spl~ ~override~
  SAY NAME1 @99
  SAY UNIDENTIFIED_DESC @96
  WRITE_ASCII 0x3a ~d5_feat~ #8
  LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_feat~ END

COPY ~will_to_power/data/d5_feat.bam~ ~override~
COPY ~will_to_power/data/d5_psion.eff~ ~override~ 
COPY ~will_to_power/data/d5_psion.cre~ ~override~ 
COMPILE ~will_to_power/data/d5_psi.baf~ 

OUTER_FOR (ind = 2; ind < 50; ++ind) BEGIN
  COPY_EXISTING ~d5psi1.spl~ ~override/d5psi%ind%.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
END
//__________________________________________________________________________________




/*
//PSIONIC HLAS______________________________________________________________________
//
COPY ~will_to_power/data/d5psifz.spl~ ~override~ 		//			more psionic feats
	SAY NAME1 @20099
	SAY UNIDENTIFIED_DESC @20600
  WRITE_ASCII 0x3a ~d5_feat~ #8
  LPF ALTER_SPELL_HEADER INT_VAR speed = 2 location = 4 STR_VAR icon = ~d5_feat~ END

COPY ~will_to_power/data/d5_ps408.bam~ ~override~
COPY ~will_to_power/data/d5ps408.spl~ ~override~ 		//			monstrous evolution
	SAY NAME1 @20593
	SAY UNIDENTIFIED_DESC @20594
	WRITE_ASCII 0x3a ~d5_ps408~ #8
	LPF ALTER_SPELL_HEADER INT_VAR speed = 4 STR_VAR icon = ~d5_ps408~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 power = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 324 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5ps408~ END
COPY ~will_to_power/data/d5_sham.cre~ ~override~
	SAY NAME1 @20595
COPY ~will_to_power/data/d5_clsha.itm~ ~override~
	SAY NAME1 @20596
	SAY UNIDENTIFIED_DESC @20596
COPY ~will_to_power/data/d5psinf.spl~ ~override~
	SAY NAME1 @20597
	SAY UNIDENTIFIED_DESC @20597
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 8 parameter2 = 0 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psst20~ END

//__________________________________________________________________________________

*/


END
