
//____________________________________________________________________________________
//____________________________________________________________________________________
//
//									PSIONICS SYSTEM
//____________________________________________________________________________________
//____________________________________________________________________________________

// ***** Wild Talent stuff:
// -- make new versions of each wrapper spell, with location = innates
// -- make new 206 spells work with these as well as _s/_r
// -- make new 171 _s/_r spells, geared for these (no long-range _q/_t variants, though)
// -- add these to ppts# spells

// -- have d5ps000 confer immunity to these WT 171 spells
// -- GA_ a WT0 ability in every clab
// -- WT0: confers immunity to the base psion _s/_q/_t spells
// -- WT0: Pr100 = cast WT3; Pr99 = cast WT1; Pr96-99 = cast WT0
// -- WT1: randomly applies the learn spell for one devotion
// -- WT2: randomly applies the learn spell for one science
// -- PSPs... 10 at 1st level? then +2/lvl til level 6 (20), then +1/lvl until level 16 (30)
// -- OR, just give flat 20 PSPs (in WT1 and WT2)
// -- that would be easier, and more compatible with making a WT feat in MnG


DEFINE_ACTION_FUNCTION psionics_system BEGIN 

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_psionics.d5~ BEGIN

//COPY MARKER FILE____________________________________________________________________
//
COPY ~will_to_power/lib/markers/d5_psionics.d5~ ~override~
//____________________________________________________________________________________


//PREP SPLPROT.2DA____________________________________________________________________
//
APPEND ~splprot.2da~ ~D5_MXHP_GT%TAB%1%TAB%-1%TAB%3~						//	max HP > x
APPEND ~splprot.2da~ ~D5_MXHP_LT%TAB%1%TAB%-1%TAB%2~						//	max HP < x
APPEND ~splprot.2da~ ~D5_134_PSI%TAB%134%TAB%-1%TAB%8~
APPEND ~splprot.2da~ ~D5_TRKNG_PTS%TAB%33%TAB%-1%TAB%7~ UNLESS ~D5_TRKNG_PTS~
APPEND ~splprot.2da~ ~D5_TRKNG_LESS%TAB%33%TAB%-1%TAB%2~ UNLESS ~D5_TRKNG_LESS~
APPEND ~splprot.2da~ ~D5_TRKNG_MORE%TAB%33%TAB%-1%TAB%3~ UNLESS ~D5_TRKNG_MORE~
APPEND ~splprot.2da~ ~D5_FATIGUE_IS%TAB%30%TAB%-1%TAB%1~ UNLESS ~D5_FATIGUE_IS~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MXHP_GT~ BEGIN
	  SET maxhp_gt = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MXHP_LT~ BEGIN
	  SET maxhp_lt = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_134_PSI~ BEGIN
	  SET 134_psi = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_TRKNG_PTS~ BEGIN
	  SET tracking_points = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_TRKNG_LESS~ BEGIN
	  SET tracking_less = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_TRKNG_MORE~ BEGIN
	  SET tracking_more = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_IS~ BEGIN
	  SET fatigue_value = %row%
	END
  END
BUT_ONLY
//____________________________________________________________________________________


//make table for adding to clabs______________________________________________________
//
<<<<<<<< d5/d5_psi.2da

>>>>>>>>
COPY ~d5/d5_psi.2da~ ~override/d5_psi.2da~
//____________________________________________________________________________________


/* 
// IF PSION = WIZARD:

//remove all mage spell slots_________________________________________________________
//
COPY ~will_to_power/data/d5_base.spl~ ~override/d50wslt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 511 timing = 9 END
BUT_ONLY

APPEND ~d5_psi.2da~ ~NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~
//____________________________________________________________________________________

//remove all mage known spells________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d50wspl.2da~) BEGIN
  OUTER_SET 0wspl = 1
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d50wspl.2da~) BEGIN
  OUTER_SET 0wspl = 0
  COPY ~will_to_power/data/d5_base.spl~ ~override/d50wspl.spl~
END
ACTION_IF 0wspl = 0 BEGIN
  COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
	PATCH_IF FILE_EXISTS_IN_GAME ~%SOURCE_RES%.spl~ BEGIN
	  READ_SHORT 0x1c spell_type 
	  READ_LONG 0x34 spell_level
	  PATCH_IF (~%SOURCE_RES%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ww][Ii][1-9][0-5][0-9]~ = 0) && (spell_type = 1) BEGIN
		SPRINT ~spell_res~ ~%SOURCE_RES%~
		INNER_ACTION BEGIN
		  COPY_EXISTING ~d50wspl.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%spell_res%~ END
		END
	  END
	END
  BUT_ONLY
END

APPEND ~d5_psi.2da~ ~NO_WSPLS    AP_D50WSPL  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
//____________________________________________________________________________________
*/


// IF PSION = CLERIC:

//remove all mage spell slots_________________________________________________________
//
COPY ~will_to_power/data/d5_base.spl~ ~override/d50cslt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 62 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
BUT_ONLY

APPEND ~d5_psi.2da~ ~NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50CSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~
//____________________________________________________________________________________

//remove cleric spells every level____________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^SPPR[1-7]\(0[1-9]\|[1-4][0-9]\|50\)\.spl$~ ~override~
  READ_SHORT 0x1c spell_type
  READ_BYTE 0x21 divine
  PATCH_IF (spell_type = 2) && ((%divine% BOR 0b10111111) = 0b10111111) && !(FILE_CONTAINS_EVALUATED (~hidespl.2da~ ~%SOURCE_RES%~)) BEGIN	//	cleric-valid spells
	SPRINT $cleric_valid_spells(~%SOURCE_RES%~) ~valid~
  END
BUT_ONLY
 
COPY ~will_to_power/data/d5_base.spl~ ~override/d5psncl.spl~
  PHP_EACH cleric_valid_spells AS cl_res => type BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~%cl_res%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 4 duration = 1 STR_VAR resource = EVAL ~%cl_res%~ END
  END
// disable turn undead
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 6 timing = 9 END

APPEND ~d5_psi.2da~ ~NO_SPELLS   AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL  AP_D5PSNCL ~
//____________________________________________________________________________________


//assign stats for mana - I mean, 'psionic strength' points___________________________
//
// Points = (stat 133)
//
COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp01.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 15 parameter2 = 1 timing = 9 /*0 duration = 126144000*/ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5psp01~ END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp1w.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 18 parameter2 = 1 timing = 9 /*0 duration = 126144000*/ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5psp0w~ END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp2w.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 20 parameter2 = 1 timing = 9 /*0 duration = 126144000*/ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5psp0w~ END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp1a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ ~u~ BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp1%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 /*0 duration = 126144000*/ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5psp1%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp2a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp2%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 2 parameter2 = 0 timing = 9 /*0 duration = 126144000*/ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5psp2%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp5a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ ~u~ BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp5%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 5 parameter2 = 0 timing = 9 /*0 duration = 126144000*/ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5psp5%let%~ END
  END
END

// maybe 15 + ...5/level? (to level 20, then 2/level to 40)
APPEND ~d5_psi.2da~ ~PSI_PTS     AP_D5PSP01  AP_D5PSP5A  AP_D5PSP5B  AP_D5PSP5C  AP_D5PSP5D  AP_D5PSP5E  AP_D5PSP5F  AP_D5PSP5G  AP_D5PSP5H  AP_D5PSP5I  AP_D5PSP5J  AP_D5PSP5K  AP_D5PSP5L  AP_D5PSP5M  AP_D5PSP5N  AP_D5PSP5O  AP_D5PSP5P  AP_D5PSP5Q  AP_D5PSP5R  AP_D5PSP5S  AP_D5PSP2B  AP_D5PSP2C  AP_D5PSP2D  AP_D5PSP2E  AP_D5PSP2F  AP_D5PSP2G  AP_D5PSP2H  AP_D5PSP2I  AP_D5PSP2J  AP_D5PSP2K  AP_D5PSP2L  AP_D5PSP2M  AP_D5PSP2N  AP_D5PSP2O  AP_D5PSP2P  AP_D5PSP2Q  AP_D5PSP2R  AP_D5PSP2S  AP_D5PSP2T  AP_D5PSP2U  ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-1.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 1) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 1) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 1 parameter2 = 0 timing = 0 duration = 126144000 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-2.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-2.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 2) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_2.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 2) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+2.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 2 parameter2 = 0 timing = 0 duration = 126144000 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-3.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-3.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 3) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_3.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 3) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+3.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 3 parameter2 = 0 timing = 0 duration = 126144000 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-4.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 4) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 4) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 4 parameter2 = 0 timing = 0 duration = 126144000 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-5.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-5.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 5) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_5.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 5) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+5.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 5 parameter2 = 0 timing = 0 duration = 126144000 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-6.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 6) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 6) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 6 parameter2 = 0 timing = 0 duration = 126144000 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5psp-X.spl~ BEGIN
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp-X.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 10) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp_X.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = (0 - 10) parameter2 = 0 timing = 0 duration = 126144000 END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5psp+X.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 10 parameter2 = 0 timing = 0 duration = 126144000 END
END

// every power will cast d5psp-# and d5psp_#, where # is half the power's cost, if the player has enough points

// in the case of maintainable spells, they will just cast d5psp-# twice
// and give the PSP-variant cancel spell, if the player has enough points
// then that cancel spell will cast d5psp+# to get half the cost back

// the 'restorative meditation' ability will 321 cancel all d5ps_# spells

// sleeping will cancel all d5psp-#, d5psp_#, and d5psp+# spells, to get back to the baseline

//____________________________________________________________________________________


//hit point cost files________________________________________________________________
//
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst6.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 6 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx6~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst10.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 10 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 11 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx10~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psst20.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 20 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psmx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psrx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psmx20~ END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 6) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx10.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 10) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psmx20.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 20) parameter2 = 3 timing = 4 duration = 1 END

COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt6.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 6 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx6~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt10.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 10 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 11 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx10~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx10~ END
COPY ~will_to_power/data/d5psst.spl~ ~override/d5psnt20.spl~
	LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 21 opcode = 12 target = 1 parameter1 = 20 parameter2 = (0 + (2048 << 16)) timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 21 parameter2 = %maxhp_lt% timing = 0 duration = 1 STR_VAR resource = ~d5psnx20~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psnx20~ END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 6) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx10.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 10) parameter2 = 3 timing = 4 duration = 1 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psnx20.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = (0 - 20) parameter2 = 3 timing = 4 duration = 1 END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 72 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx10.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 72 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 84 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 96 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 108 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 120 END
COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrx20.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 48 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 60 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 72 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 84 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 96 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 108 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 120 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 132 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 144 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 156 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 168 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 180 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 192 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 204 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 216 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 228 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 1 parameter1 = 1 parameter2 = 0 timing = 4 duration = 240 END

COPY ~will_to_power/data/d5psmx.spl~ ~override/d5psrz6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 6 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 12 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 18 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 24 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 30 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 18 target = 2 parameter1 = 1 parameter2 = 0 timing = 4 duration = 36 END

// instant powers will cast d5psst#, if the player does not have enough points

// maintainable powers will cast d5psnt#, and give the HP-variant cancel ability

//___________________________________________________________________________________


//add needed spellstates etc.________________________________________________________
//
LAF d5_resolve_state STR_VAR new_state_id = ~D5_METAPSIONIC~ RET new_state_ind END

OUTER_SET metapsionic_state = %new_state_ind%

LAF d5_resolve_state STR_VAR new_state_id = ~D5_MIND_WARD~ RET new_state_ind END

OUTER_SET mind_ward_state = %new_state_ind%

LAF d5_resolve_state STR_VAR new_state_id = ~D5_HOLDS_BARRED~ RET new_state_ind END

OUTER_SET hold_evasion_state = %new_state_ind%

APPEND ~splprot.2da~ ~D5_STATE_POISON%TAB%0x111%TAB%0x4000%TAB%8~
APPEND ~splprot.2da~ ~D5_STATE_DISEASE%TAB%0x111%TAB%0x80000%TAB%8~

COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols 
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_STATE_POISON~ BEGIN
	    SET state_poison = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_STATE_DISEASE~ BEGIN
	    SET state_disease = %row%
	  END
	END
BUT_ONLY

LAF d5_resolve_state STR_VAR new_state_id = ~D5_SNAREARROW~ RET new_state_ind END
OUTER_SET missile_snaring_state = %new_state_ind%
OUTER_SET nada = RESOLVE_STR_REF (~ ~)
ACTION_IF NOT FILE_EXISTS_IN_GAME ~7eyes.2da~ BEGIN
	COPY ~will_to_power/misc/7eyes.2da~ ~override~
END
APPEND ~7eyes.2da~ ~SNARE_ARROW  %missile_snaring_state%         %nada%         12*0x800000 *           *           *            *            *          *          *          * ~ UNLESS ~SNARE_ARROW~

OUTER_SET optional_evade = 1
INCLUDE ~%MOD_FOLDER%/lib/spell_evasion.tpa~

APPEND ~splprot.2da~ ~D5_KIT_IS%TAB%152%TAB%-1%TAB%1~ UNLESS ~D5_KIT_IS~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_IS~ BEGIN
	    SET kit_is_row = %row%
	  END
	END
BUT_ONLY
//__________________________________________________________________________________


//CLEAR AURA EFF____________________________________________________________________
//
CREATE EFF ~d5psaura~
  WRITE_LONG 0x10 188
  WRITE_LONG 0x14 1
  WRITE_LONG 0x18 0
  WRITE_LONG 0x20 1
  WRITE_LONG 0x24 0
  WRITE_LONG 0x28 5
  WRITE_SHORT 0x2c 100
//__________________________________________________________________________________


//PSIONIC ABILITY FILES_____________________________________________________________
//
INCLUDE ~will_to_power/lib/psionic_powers.tpa~
//__________________________________________________________________________________


//learning new powers________________________________________________________________
//
// d5ps__  = psp spell, 30' range 				(must be 7 chars because 172)
// ... and icon
// d5pr__  = hp spell, 30' range 				(must be 7 chars because 172)
// d5pt__  = psp spell, unlimited range			(must be 7 chars because 172)
// d5pq__  = hp spell, unlimited range			(must be 7 chars because 172)
// d5pw__  = psp spell, 30' range, innate loc 	(must be 7 chars because 172)
// d5pu__  = hp spell, 30' range, innate loc 	(must be 7 chars because 172)
// d5ps__p = spellbook spell, for display only
// d5ps__a = subspell, repeated effects
// d5px__  = cancel and give back PSPs			(must be 7 chars because 172)
// ... and icon
// d5py__  = cancel and give back HPs			(must be 7 chars because 172)
// d5ps__s = add psp ability (in pspls1)
// d5ps__r = add hp ability (in pspls1)
// d5ps__t = add psp ability (long-range)
// d5ps__q = add hp ability (long-range)
// d5ps__w = add psp WT ability
// d5ps__u = add hp WT ability
// d5ps__v = cannot use (206 vs. _q and _r and _s and _t)
// d5pv__  = learn ability (cancel _v, give _p)	(must be 7 chars because applied by ApplySpellRES)

// d5ps__z = cannot use wt (206 vs. _w and _u)
// d5pz__  = learn ability (cancel _y)	(must be 7 chars because applied by ApplySpellRES)


// d5ps000 = immunity vs. d5ps#w
// d5pswt0 = immunity vs. d5ps#s, d5ps#t, d5ps#q, d5ps#y

ACTION_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
  ACTION_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ /*~11~*/ BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%disc%%abil%s.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%~ END
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%disc%%abil%r.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pr%disc%%abil%~ END
	ACTION_IF (FILE_EXISTS_IN_GAME ~d5pt%disc%%abil%.spl~) BEGIN
	  COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%disc%%abil%t.spl~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pt%disc%%abil%~ END
	END
	ACTION_IF (FILE_EXISTS_IN_GAME ~d5pq%disc%%abil%.spl~) BEGIN
	  COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%disc%%abil%q.spl~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pq%disc%%abil%~ END
	END
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%disc%%abil%w.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pw%disc%%abil%~ END
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%disc%%abil%u.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pu%disc%%abil%~ END
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%disc%%abil%v.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%r~ END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5pt%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%t~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5pq%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%q~ END
	  END
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5pv%disc%%abil%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%v~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%v~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%disc%%abil%p~ END
//	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pv000~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls2~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 2 STR_VAR resource = ~d5pspls1~ END
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%disc%%abil%z.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%w~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%u~ END
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5pz%disc%%abil%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls2~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 2 STR_VAR resource = ~d5pspls1~ END
  END
END
ACTION_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%~) BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%hisci%s.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%~ END
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5pr%hisci%~) BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%hisci%r.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pr%hisci%~ END
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5pt%hisci%~) BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%hisci%t.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pt%hisci%~ END
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5pq%hisci%~) BEGIN
	COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%hisci%q.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5pq%hisci%~ END
  END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%hisci%v.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~D5PS%hisci%s~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~D5PS%hisci%r~ END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5ps%hisci%y.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%z~ END
  COPY ~will_to_power/data/d5_base.spl~ ~override/d5pv%hisci%.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%v~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%v~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%y~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 2 STR_VAR resource = ~d5pspls1~ END
END

ACTION_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
  COPY_EXISTING ~d5pv%disc%01.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = ~d5pspls2~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 146 STR_VAR match_resource = ~d5pspls1~ END
END

COPY ~will_to_power/data/d5ps000.spl~ ~override~
  SAY NAME1 @101
  SAY UNIDENTIFIED_DESC @102
  LPF DELETE_EFFECT INT_VAR match_opcode = 143 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5prptz~ END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%v.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%disc%%abil%v~ END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%v.spl~) BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%hisci%v~ END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%z.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
	  END
	END
  END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5spm3m~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 12 STR_VAR resource = ~d5spmem~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5pswt0~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 12 STR_VAR resource = ~d5pswt_~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pv000~ END

COPY ~will_to_power/data/d5_base.spl~ ~override/d5pv000.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%01v~ END
//	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5pv%disc%01~ END
	PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%01p.spl~) BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5ps%disc%01p~ END
	END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5ps000~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5pv000~ END

//___________________________________________________________________________________


//wild talents_______________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_mana.2da~) BEGIN
  COPY_EXISTING ~kit.ids~ ~override~
	COUNT_2DA_ROWS 2 rows
	FOR (row = 2 ; row < rows ; ++row) BEGIN
	  READ_2DA_ENTRY %row% 1 2 modname
	  READ_2DA_ENTRY %row% 0 2 mod_ids
	  PATCH_IF (~%modname%~ STRING_EQUAL_CASE ~D5_MANA_SORCERER~) BEGIN
		SET manasorc_ids = mod_ids
	  END
	END
  BUT_ONLY
END

COPY ~will_to_power/data/d5_base.spl~ ~override/d5pswt_.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5pswt0~ END
  PATCH_IF (VARIABLE_IS_SET %manasorc_ids%) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %manasorc_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5pswt_~ END
  END

COPY ~will_to_power/data/d5pswt0.bam~ ~override~
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pswt0.spl~
  SAY NAME1 @111
  SAY UNIDENTIFIED_DESC @112
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5pswt0~ END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%z.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%v.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%disc%%abil%v~ END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%v.spl~) BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%hisci%v~ END
	END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 98 probability2 = 94 timing = 4 duration = 1 STR_VAR resource = ~d5pswt1~ END	//	devotion
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 99 probability2 = 98 timing = 4 duration = 1 STR_VAR resource = ~d5pswt2~ END	//	2nd devotion
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 100 probability2 = 99 timing = 4 duration = 1 STR_VAR resource = ~d5pswt3~ END	//	science
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5pswt0~ END
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5_mana.2da~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %manasorc_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5pswt0~ END
  END

COPY ~will_to_power/data/d5_base.spl~ ~override/d5pswt1.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%r~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%t~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%q~ END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp1w~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 100 probability2 = 97 timing = 4 duration = 1 STR_VAR resource = ~d5pz101~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 96 probability2 = 93 timing = 4 duration = 1 STR_VAR resource = ~d5pz102~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 92 probability2 = 89 timing = 4 duration = 1 STR_VAR resource = ~d5pz103~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 88 probability2 = 85 timing = 4 duration = 1 STR_VAR resource = ~d5pz104~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 84 probability2 = 81 timing = 4 duration = 1 STR_VAR resource = ~d5pz105~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 80 probability2 = 77 timing = 4 duration = 1 STR_VAR resource = ~d5pz201~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 76 probability2 = 73 timing = 4 duration = 1 STR_VAR resource = ~d5pz202~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 72 probability2 = 69 timing = 4 duration = 1 STR_VAR resource = ~d5pz203~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 68 probability2 = 65 timing = 4 duration = 1 STR_VAR resource = ~d5pz204~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 64 probability2 = 61 timing = 4 duration = 1 STR_VAR resource = ~d5pz205~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 60 probability2 = 57 timing = 4 duration = 1 STR_VAR resource = ~d5pz301~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 56 probability2 = 53 timing = 4 duration = 1 STR_VAR resource = ~d5pz302~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 52 probability2 = 49 timing = 4 duration = 1 STR_VAR resource = ~d5pz303~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 48 probability2 = 45 timing = 4 duration = 1 STR_VAR resource = ~d5pz304~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 44 probability2 = 41 timing = 4 duration = 1 STR_VAR resource = ~d5pz305~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 40 probability2 = 37 timing = 4 duration = 1 STR_VAR resource = ~d5pz401~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 36 probability2 = 33 timing = 4 duration = 1 STR_VAR resource = ~d5pz402~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 32 probability2 = 29 timing = 4 duration = 1 STR_VAR resource = ~d5pz403~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 28 probability2 = 25 timing = 4 duration = 1 STR_VAR resource = ~d5pz404~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 24 probability2 = 21 timing = 4 duration = 1 STR_VAR resource = ~d5pz405~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 20 probability2 = 17 timing = 4 duration = 1 STR_VAR resource = ~d5pz501~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 16 probability2 = 13 timing = 4 duration = 1 STR_VAR resource = ~d5pz502~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 12 probability2 = 9 timing = 4 duration = 1 STR_VAR resource = ~d5pz503~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 8 probability2 = 5 timing = 4 duration = 1 STR_VAR resource = ~d5pz504~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 4 probability2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pz505~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5prptz~ END

COPY ~will_to_power/data/d5_base.spl~ ~override/d5pswt2.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 100 probability2 = 97 timing = 4 duration = 1 STR_VAR resource = ~d5pz101~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 96 probability2 = 93 timing = 4 duration = 1 STR_VAR resource = ~d5pz102~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 92 probability2 = 89 timing = 4 duration = 1 STR_VAR resource = ~d5pz103~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 88 probability2 = 85 timing = 4 duration = 1 STR_VAR resource = ~d5pz104~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 84 probability2 = 81 timing = 4 duration = 1 STR_VAR resource = ~d5pz105~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 80 probability2 = 77 timing = 4 duration = 1 STR_VAR resource = ~d5pz201~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 76 probability2 = 73 timing = 4 duration = 1 STR_VAR resource = ~d5pz202~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 72 probability2 = 69 timing = 4 duration = 1 STR_VAR resource = ~d5pz203~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 68 probability2 = 65 timing = 4 duration = 1 STR_VAR resource = ~d5pz204~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 64 probability2 = 61 timing = 4 duration = 1 STR_VAR resource = ~d5pz205~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 60 probability2 = 57 timing = 4 duration = 1 STR_VAR resource = ~d5pz301~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 56 probability2 = 53 timing = 4 duration = 1 STR_VAR resource = ~d5pz302~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 52 probability2 = 49 timing = 4 duration = 1 STR_VAR resource = ~d5pz303~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 48 probability2 = 45 timing = 4 duration = 1 STR_VAR resource = ~d5pz304~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 44 probability2 = 41 timing = 4 duration = 1 STR_VAR resource = ~d5pz305~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 40 probability2 = 37 timing = 4 duration = 1 STR_VAR resource = ~d5pz401~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 36 probability2 = 33 timing = 4 duration = 1 STR_VAR resource = ~d5pz402~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 32 probability2 = 29 timing = 4 duration = 1 STR_VAR resource = ~d5pz403~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 28 probability2 = 25 timing = 4 duration = 1 STR_VAR resource = ~d5pz404~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 24 probability2 = 21 timing = 4 duration = 1 STR_VAR resource = ~d5pz405~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 20 probability2 = 17 timing = 4 duration = 1 STR_VAR resource = ~d5pz501~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 16 probability2 = 13 timing = 4 duration = 1 STR_VAR resource = ~d5pz502~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 12 probability2 = 9 timing = 4 duration = 1 STR_VAR resource = ~d5pz503~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 8 probability2 = 5 timing = 4 duration = 1 STR_VAR resource = ~d5pz504~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 4 probability2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pz505~ END

COPY ~will_to_power/data/d5_base.spl~ ~override/d5pswt3.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%r~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%t~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%q~ END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp2w~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 100 probability2 = 94 timing = 4 duration = 1 STR_VAR resource = ~d5pz107~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 93 probability2 = 87 timing = 4 duration = 1 STR_VAR resource = ~d5pz108~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 86 probability2 = 80 timing = 4 duration = 1 STR_VAR resource = ~d5pz109~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 79 probability2 = 73 timing = 4 duration = 1 STR_VAR resource = ~d5pz207~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 72 probability2 = 66 timing = 4 duration = 1 STR_VAR resource = ~d5pz208~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 65 probability2 = 59 timing = 4 duration = 1 STR_VAR resource = ~d5pz209~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 58 probability2 = 52 timing = 4 duration = 1 STR_VAR resource = ~d5pz307~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 51 probability2 = 46 timing = 4 duration = 1 STR_VAR resource = ~d5pz308~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 45 probability2 = 40 timing = 4 duration = 1 STR_VAR resource = ~d5pz309~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 39 probability2 = 33 timing = 4 duration = 1 STR_VAR resource = ~d5pz407~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 32 probability2 = 26 timing = 4 duration = 1 STR_VAR resource = ~d5pz408~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 25 probability2 = 19 timing = 4 duration = 1 STR_VAR resource = ~d5pz409~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 18 probability2 = 13 timing = 4 duration = 1 STR_VAR resource = ~d5pz507~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 12 probability2 = 7 timing = 4 duration = 1 STR_VAR resource = ~d5pz508~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 6 probability2 = 0 timing = 4 duration = 1 STR_VAR resource = ~d5pz509~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5prptz~ END

ACTION_FOR_EACH tc_clab IN ~clabfi01~ ~clabpa01~ ~clabrn01~ ~clabth01~ ~clabba01~ ~clabpr01~ ~clabdr01~ ~clabma01~ BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~%tc_clab%.2da~) BEGIN
	APPEND ~%tc_clab%.2da~ ~WILD_TLNT   AP_D5PSWT_  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  END
END
COPY_EXISTING ~kitlist.2da~ ~override~
  COUNT_2DA_ROWS 10 rows
  FOR (row = 2 ; row < rows ; ++row) BEGIN
	READ_2DA_ENTRY %row% 5 10 modclab
	READ_2DA_ENTRY %row% 8 10 modclass
	PATCH_IF modclass = 1 || modclass = 2 || modclass = 3 || modclass = 4 || modclass = 5 || modclass = 6 || modclass = 11 || modclass = 12 || modclass = 19 || modclass = 20 || modclass = 21 BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~%modclab%.2da~) && !(~%modclab%~ STRING_EQUAL_CASE ~d5_mana~) BEGIN
		INNER_ACTION BEGIN
		  APPEND ~%modclab%.2da~ ~WILD_TLNT   AP_D5PSWT_  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
		END
	  END
	END
  END
BUT_ONLY
//____________________________________________________________________________________

//special WT spells for haer'dalis____________________________________________________
//
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pswh0.spl~
  SAY NAME1 @111
  SAY UNIDENTIFIED_DESC @112
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%z.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%disc%%abil%z~ END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%v.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%disc%%abil%v~ END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%v.spl~) BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = EVAL ~d5ps%hisci%v~ END
	END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pswh1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5pswh0~ END

COPY ~will_to_power/data/d5_base.spl~ ~override/d5pswh1.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%s~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%r~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%t~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%abil%q~ END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5psp2w~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 100 probability2 = 83 timing = 4 duration = 1 STR_VAR resource = ~d5pz104~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 82 probability2 = 65 timing = 4 duration = 1 STR_VAR resource = ~d5pz201~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 64 probability2 = 47 timing = 4 duration = 1 STR_VAR resource = ~d5pz302~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 46 probability2 = 29 timing = 4 duration = 1 STR_VAR resource = ~d5pz405~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 28 probability2 = 11 timing = 4 duration = 1 STR_VAR resource = ~d5pz504~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 10 probability2 = 6 timing = 4 duration = 1 STR_VAR resource = ~d5pz507~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 probability1 = 5 probability2 = 0 timing = 4 duration = 1 STR_VAR resource = ~d5pz509~ END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5prptz~ END

ACTION_FOR_EACH haer IN ~haer10~ ~haer13~ ~haer15~ ~haer19~ BEGIN
  COPY_EXISTING ~%haer%.cre~ ~override~
	LPF ADD_CRE_EFFECT INT_VAR opcode = 206 target = 1 timing = 9 STR_VAR resource = ~d5pswt_~ END // normal WT 00 abil
	LPF ADD_CRE_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5pswh0~ END // special HD WT0
  IF_EXISTS BUT_ONLY
END
//____________________________________________________________________________________


//recalculate PSPs____________________________________________________________________
//
// these will have 171 effects for every power, 2^(#-1) times each

COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts1.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH dev IN ~01~ ~02~ ~03~ ~04~ ~05~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH sci IN ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		END
	  END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts2.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH dev IN ~01~ ~02~ ~03~ ~04~ ~05~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH sci IN ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		END
	  END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts3.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH dev IN ~01~ ~02~ ~03~ ~04~ ~05~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  FOR (pts_count = 1; pts_count < 5; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 5; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH sci IN ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  FOR (pts_count = 1; pts_count < 5; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 5; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  FOR (pts_count = 1; pts_count < 5; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 5; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  END
		END
	  END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts4.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH dev IN ~01~ ~02~ ~03~ ~04~ ~05~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  FOR (pts_count = 1; pts_count < 9; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 9; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH sci IN ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  FOR (pts_count = 1; pts_count < 9; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 9; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  FOR (pts_count = 1; pts_count < 9; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 9; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  END
		END
	  END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts5.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH dev IN ~01~ ~02~ ~03~ ~04~ ~05~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  FOR (pts_count = 1; pts_count < 17; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 17; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH sci IN ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  FOR (pts_count = 1; pts_count < 17; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 17; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  FOR (pts_count = 1; pts_count < 17; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 17; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  END
		END
	  END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts6.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH dev IN ~01~ ~02~ ~03~ ~04~ ~05~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  FOR (pts_count = 1; pts_count < 33; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 33; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH sci IN ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  FOR (pts_count = 1; pts_count < 33; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 33; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  FOR (pts_count = 1; pts_count < 33; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 33; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  END
		END
	  END
  END
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ppts7.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH dev IN ~01~ ~02~ ~03~ ~04~ ~05~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
		  FOR (pts_count = 1; pts_count < 65; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%dev%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 65; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 5 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 6 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%dev%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH sci IN ~07~ ~08~ ~09~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
		  FOR (pts_count = 1; pts_count < 65; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%q~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%disc%%sci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 65; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 9 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%w~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 10 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%disc%%sci%u~ END
		  END
		END
	  END
	END
  END
  PATCH_FOR_EACH hisci IN ~111~ ~211~ ~311~ ~411~ ~511~ ~901~ ~902~ ~903~ ~904~ ~905~ ~906~ ~907~ ~908~ ~909~ ~910~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%s.spl~) BEGIN
	    PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 110 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = %metapsionic_state% parameter2 = 111 timing = 0 duration = 1 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  FOR (pts_count = 1; pts_count < 65; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%t~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%q~ END
		  END
		END
	    PATCH_IF !(FILE_EXISTS_IN_GAME ~d5ps%hisci%t.spl~) BEGIN
		  FOR (pts_count = 1; pts_count < 65; ++pts_count) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 19 parameter2 = %tracking_more% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%s~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 20 parameter2 = %tracking_less% timing = 9 STR_VAR resource = EVAL ~d5ps%hisci%r~ END
		  END
		END
	  END
  END

// this will have 172 effects for all powers of every type and range
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pspls2.spl~
  PATCH_FOR_EACH disc IN ~1~ ~2~ ~3~ ~4~ ~5~ BEGIN
	PATCH_FOR_EACH abil IN ~01~ ~02~ ~03~ ~04~ ~05~ ~07~ ~08~ ~09~ ~11~ BEGIN
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5ps%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~d5ps%disc%%abil%~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5pr%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~d5pr%disc%%abil%~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5pt%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~d5pt%disc%%abil%~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5pq%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~d5pq%disc%%abil%~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5pw%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~d5pw%disc%%abil%~ END
	  END
	  PATCH_IF (FILE_EXISTS_IN_GAME ~d5pu%disc%%abil%.spl~) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = EVAL ~d5pu%disc%%abil%~ END
	  END
	END
  END

// this will give the normal-range 171 spells
COPY ~will_to_power/data/d5_base.spl~ ~override/d5pspls1.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 2 parameter2 = %tracking_less% timing = 1 STR_VAR resource = ~d5ppts1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 1 parameter2 = %tracking_points% timing = 1 STR_VAR resource = ~d5ppts1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 2 parameter2 = %tracking_points% timing = 1 STR_VAR resource = ~d5ppts2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 4 parameter2 = %tracking_points% timing = 1 STR_VAR resource = ~d5ppts3~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 8 parameter2 = %tracking_points% timing = 1 STR_VAR resource = ~d5ppts4~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 16 parameter2 = %tracking_points% timing = 1 STR_VAR resource = ~d5ppts5~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 32 parameter2 = %tracking_points% timing = 1 STR_VAR resource = ~d5ppts6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 64 parameter2 = %tracking_points% timing = 1 STR_VAR resource = ~d5ppts7~ END


// every power will cast d5pspls2, then d5pspls1 a second later
// cancel abilities too

// clairvoyant channeling will cast d5pspls2, then d5psplz1 a second later

// combine these. the 172 spell should use 326 to conditionally cast either the s1 spell or the z1 spell (with timing 4/duration 1)
// then powers only have to cast the 172 spell
// and it can be applied every level to update PSP counts

// WAIT... only do this ^^ if want the clairvoyant channeling power to be maintainable
// if it is for one-shot ranged use, then every ability should cast both s2 and s1
// and the clab table should apply both (but then need a wrapper spell to apply s1 on a delay)
// and only the channeling power needs to cast z1

COPY ~will_to_power/data/d5_base.spl~ ~override/d5pspls.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END // s2
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END // s1

APPEND ~d5_psi.2da~ ~PSI_LVL     AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  AP_D5PSPLS  ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

//____________________________________________________________________________________


// PSPs refresh after rest____________________________________________________________
//
COPY ~will_to_power/data/d5_base.spl~ ~override/d5prptz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5prpts~ END

//APPEND ~d5_psi.2da~ ~REFRESH     AP_D5PRPTZ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

CREATE EFF ~d5prpts~
  WRITE_LONG 0x10 232
  WRITE_LONG 0x14 1
  WRITE_LONG 0x1c 0
  WRITE_LONG 0x20 20
  WRITE_LONG 0x24 9
  WRITE_SHORT 0x2c 100
  WRITE_ASCII 0x30 ~d5prpt~ #8
  WRITE_LONG 0x48 102

COPY ~will_to_power/data/d5_base.spl~ ~override/d5prpt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_value% timing = 1 STR_VAR resource = ~d5prfrsh~ END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5prfrsh.spl~ BEGIN
 COPY ~will_to_power/data/d5_base.spl~ ~override/d5prfrsh.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
  PATCH_FOR_EACH points IN ~1~ ~2~ ~3~ ~4~ ~5~ ~6~ ~X~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp-%points%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp_%points%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp+%points%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp&%points%~ END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
END

// restorative meditation ability
COPY ~will_to_power/data/d5prmed.bam~ ~override~
COPY ~will_to_power/data/d5_base.spl~ ~override/d5prmed.spl~
  SAY NAME1 @151
  SAY UNIDENTIFIED_DESC @152
  WRITE_ASCII 0x3a ~d5prmed~ #8
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 location = 4 STR_VAR icon = ~d5prmed~ END
  WRITE_BYTE 0x1a (THIS BOR 0b00000001) 	//	set as non-combat ability
  PATCH_FOR_EACH points IN ~1~ ~2~ ~3~ ~4~ ~5~ ~6~ ~X~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5psp_%points%~ END
  END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 duration = 0 STR_VAR resource = ~d5pspls2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5prmed~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5prmed~ END

APPEND ~d5_psi.2da~ ~RESTORE     GA_D5PRMED  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

//____________________________________________________________________________________


//PSI FEAT FILES______________________________________________________________________
//
COPY ~will_to_power/data/d5psi1.spl~ ~override~
  SAY NAME1 @99
  SAY UNIDENTIFIED_DESC @96
  WRITE_ASCII 0x3a ~d5_feat~ #8
  LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_feat~ END

COPY ~will_to_power/data/d5_feat.bam~ ~override~
COPY ~will_to_power/data/d5_psion.eff~ ~override~ 
COPY ~will_to_power/data/d5_psion.cre~ ~override~ 
COMPILE ~will_to_power/data/d5_psi.baf~ 
COMPILE ~will_to_power/data/d5_psi.d~ 

COPY_EXISTING ~d5psi1.spl~ ~override/d5psj1.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = EVAL ~d5psj%ind%~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR resource = EVAL ~d5psj%ind%~ END

OUTER_FOR (ind = 2; ind < 50; ++ind) BEGIN
  COPY_EXISTING ~d5psi1.spl~ ~override/d5psi%ind%.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = EVAL ~d5psi%ind%~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR resource = EVAL ~d5psi%ind%~ END
  COPY_EXISTING ~d5psj1.spl~ ~override/d5psj%ind%.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 172 STR_VAR resource = EVAL ~d5psj%ind%~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 206 STR_VAR resource = EVAL ~d5psj%ind%~ END
END

// MC clerics hit HLAs at level 15... 15+ = over 3 mil XP - 1 power per level plus HLAs.  You have 31 powers at level 14, so 24 more.  You can only hit level 25 with 8 mil XP, so that means 11 HLA levels.  Say, 1/level until 27, and up to 11 via HLA. 
//									1			2			3			4			5			6			7			8			9			10			11			12			13			14			15	
//APPEND ~d5_psi.2da~ ~ABILITIES   ****        GA_D5PSI2   GA_D5PSI3   GA_D5PSI4   GA_D5PSI5   GA_D5PSI6   GA_D5PSI7   GA_D5PSI8   GA_D5PSI9   GA_D5PSI10  GA_D5PSI11  GA_D5PSI12  GA_D5PSI13  GA_D5PSI14  GA_D5PSI15  GA_D5PSI16  GA_D5PSI17  GA_D5PSI18  GA_D5PSI19  GA_D5PSI20  GA_D5PSI21  GA_D5PSI22  GA_D5PSI23  GA_D5PSI24  GA_D5PSI25  GA_D5PSI26  GA_D5PSI27  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
//ABILITIES   ****        GA_D5PSJ2   GA_D5PSJ3   GA_D5PSJ4   GA_D5PSJ5   GA_D5PSJ6   GA_D5PSJ7   GA_D5PSJ8   GA_D5PSJ9   GA_D5PSJ10  GA_D5PSJ11  GA_D5PSJ12  GA_D5PSJ13  GA_D5PSJ14  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
//____________________________________________________________________________________


//make items work with psionics_______________________________________________________
//
// potion of clarity: +12 psps
COPY ~will_to_power/data/d5_base.spl~ ~override/d5ptn21.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5psp+6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5psp+6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5pspls2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
/*
COPY_EXISTING ~potn21.itm~ ~override~
  // make a single subspell: 2x d5psp+6, d5pspls2, d5pspls1
  // apply via 326, for each psi kit
  // actually, do this part with each kit
IF_EXISTS BUT_ONLY

//potion of power: +12 psps...?
COPY_EXISTING ~potn41.itm~ ~override~
IF_EXISTS BUT_ONLY
*/

// illithid brine: +30 psps (and resist psionics)
COPY ~will_to_power/data/d5_base.spl~ ~override/d5msc9y.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5psp+6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5psp+6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5pspls2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5pspls1~ END
COPY_EXISTING ~misc9y.itm~ ~override~
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 206 STR_VAR resource = ~d5ps103a~ END
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 206 STR_VAR resource = ~d5ps104a~ END
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 206 STR_VAR resource = ~d5ps107a~ END
  LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 206 STR_VAR resource = ~d5ps109a~ END
IF_EXISTS BUT_ONLY

// psion's blade: protect vs. all telepathy, maybe more
COPY_EXISTING ~sw2h21.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 STR_VAR resource = ~d5ps103~ END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 STR_VAR resource = ~d5ps104~ END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 STR_VAR resource = ~d5ps107~ END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 STR_VAR resource = ~d5ps109~ END
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 timing = 2 STR_VAR resource = ~d5ps111a~ END
IF_EXISTS BUT_ONLY

//____________________________________________________________________________________


//make creatures work with psionics___________________________________________________
//
// make these spells cast the 'a' psionic subspells

// illithid psionic blast -> ego whip or immobilize or project force (remove projectile)
COPY_EXISTING ~spin974.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
  LPF DELETE_EFFECT END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 33 probability2 = 0 STR_VAR resource = ~d5ps104a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 66 probability2 = 34 STR_VAR resource = ~d5ps203a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 100 probability2 = 67 STR_VAR resource = ~d5ps201a~ END
IF_EXISTS BUT_ONLY

// illithid domination -> domination or id insinuation (remove projectile)
COPY_EXISTING ~spin975.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
  LPF DELETE_EFFECT END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 50 probability2 = 0 STR_VAR resource = ~d5ps107a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 100 probability2 = 51 STR_VAR resource = ~d5ps103a~ END
IF_EXISTS BUT_ONLY

// find illithid .CRE files, add Inertial Barrier

// ulitharid psionic blast -> psychic crush or ego whip or detonate or generate lightning (remove projectile)
COPY_EXISTING ~spin959.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
  LPF DELETE_EFFECT END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 25 probability2 = 0 STR_VAR resource = ~d5ps109a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 50 probability2 = 26 STR_VAR resource = ~d5ps104a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 2 parameter2 = 1 timing = 1 probability1 = 75 probability2 = 51 STR_VAR resource = ~d5ps207a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 100 probability2 = 76 STR_VAR resource = ~d5ps309a~ END
IF_EXISTS BUT_ONLY

// find ulitharid .CRE files, add Inertial Barrier and Carapace

// elder brain psionic blast -> psychic crush or detonate or psychic combustion or id insinuation (remove projectile?)
COPY_EXISTING ~spin834.spl~ ~override~
//  LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
  LPF DELETE_EFFECT END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 25 probability2 = 0 STR_VAR resource = ~d5ps109a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 2 parameter2 = 1 timing = 1 probability1 = 50 probability2 = 26 STR_VAR resource = ~d5ps207a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 2 parameter2 = 1 timing = 1 probability1 = 75 probability2 = 51 STR_VAR resource = ~d5ps305a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 100 probability2 = 76 STR_VAR resource = ~d5ps103a~ END
IF_EXISTS BUT_ONLY

// halfling ego whip -> ego whip
COPY_EXISTING ~spin909.spl~ ~override~
  LPF DELETE_EFFECT END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 STR_VAR resource = ~d5ps104a~ END
IF_EXISTS BUT_ONLY

// halfling domination -> domination or id insinuation (remove projectile)
COPY_EXISTING ~spin910.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
  LPF DELETE_EFFECT END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 50 probability2 = 0 STR_VAR resource = ~d5ps107a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 100 probability2 = 51 STR_VAR resource = ~d5ps103a~ END
IF_EXISTS BUT_ONLY

// halfling ballistic attack -> project force (remove projectile)
COPY_EXISTING ~spin911.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
  LPF DELETE_EFFECT END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 STR_VAR resource = ~d5ps201a~ END
IF_EXISTS BUT_ONLY

// halfling detonate -> detonate or psychic combustion (remove projectile)
COPY_EXISTING ~spin912.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = 1 END
  LPF DELETE_EFFECT END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 parameter2 = 1 timing = 1 probability1 = 50 probability2 = 0 STR_VAR resource = ~d5ps207a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 2 parameter2 = 1 timing = 1 probability1 = 100 probability2 = 51 STR_VAR resource = ~d5ps305a~ END
IF_EXISTS BUT_ONLY

// add mind ward, inertial barrier, camouflage to Entu .CRE file

//____________________________________________________________________________________

//fix black pits______________________________________________________________________
//
COPY_EXISTING ~ohbantim.spl~ override
  LPF ALTER_EFFECT INT_VAR match_opcode = 144 match_parameter2 = 13 opcode = 145 parameter2 = 3 END
IF_EXISTS BUT_ONLY

// change BP1 to allow innates too
// EDIT - don't need to!

//____________________________________________________________________________________

END	//	end if not already installed

END	//	end function