//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								MANA POINT SORCERER
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION mana_sorcerer BEGIN


//INCLUDE ~ManaSorc/lib/qd_multiclass.tpa~

// TO DO:

// - clone all sorcerer kits via ADD_KIT_EX
// - ...give each sorcerer kit the 'change method' ability
// - ...have the script change each kit to its mana clone

// - make new Identify spell

//go________________________________________________________________________________
//
<<<<<<<< d5/d5_mana.2da
ABILITY     ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
>>>>>>>>
COPY ~d5/d5_mana.2da~ ~override/d5_mana.2da~
COPY ~d5/d5_mana.2da~ ~override/d5_zmana.2da~

//__________________________________________________________________________________


ADD_KIT ~D5_MANA_SORCERER~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10          	 		L S                     W   C           L   U             W I
//9     	       		A M             B L S   O   I   W       A   A             O N
//8     	       		R A             A O H   H   M   A       I   R C   S       R G
//7     	       		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6     	       		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5     	       		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4     	       		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3     	       		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2     	       		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1     	       		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_MANA_SORCERER     	0 0 0 0 0 0 0 0~
~D5_MANA_SORCERER       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//  	               STR DEX CON INT WIS CHR
~D5_MANA_SORCERER      0   0   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//      	           STR DEX CON INT WIS CHR
~D5_MANA_SORCERER      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//          	       STR DEX CON INT WIS CHR
~D5_MANA_SORCERER      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//              	   STR DEX CON INT WIS CHR
~D5_MANA_SORCERER      0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 	  LG LN LE NG TN NE CG CN CE
~D5_MANA_SORCERER     1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//      	           	FT CL MA TH DR RA
~D5_MANA_SORCERER       0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~override/d5_mana.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric = 3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20, FC = 8, CT = 15, CR = 18, FM = 7, CM = 14, MT = 13
~0x00020000 1~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~So0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @17081
SAY @17082
SAY @17083

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@17083)
		STR_VAR
			kit_name = D5_MANA_SORCERER   
			clswpbon = ~0 0 3~
			hpclass = ~HPWIZ~
			clsrcreq = ~0 0 0 0 0 0 0~
	END
END

//dummy kit for CharGen______________________________________________________________

/*
ADD_KIT ~D5_ZMANA_SORCERER~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                            T   S           F   Q             S S
//10          	 		L S                     W   C           L   U             W I
//9     	       		A M             B L S   O   I   W       A   A             O N
//8     	       		R A             A O H   H   M   A       I   R C   S       R G
//7     	       		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6     	       		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5     	       		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4     	       		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3     	       		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2     	       		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1     	       		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_ZMANA_SORCERER     	0 0 0 0 0 0 0 0~
~D5_ZMANA_SORCERER      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//  	               STR DEX CON INT WIS CHR
~D5_ZMANA_SORCERER      0   0   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//      	           STR DEX CON INT WIS CHR
~D5_ZMANA_SORCERER      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//          	       STR DEX CON INT WIS CHR
~D5_ZMANA_SORCERER      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//              	   STR DEX CON INT WIS CHR
~D5_ZMANA_SORCERER      0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 	  LG LN LE NG TN NE CG CN CE
~D5_ZMANA_SORCERER     1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//      	           	FT CL MA TH DR RA
~D5_ZMANA_SORCERER       0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~override/d5_zmana.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_S_E K_S_H K_S_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric = 3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20, FC = 8, CT = 15, CR = 18, FM = 7, CM = 14, MT = 13
~0x00004000 19~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~So0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @17081
SAY @17082
SAY @17083

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@17083)
		STR_VAR
			kit_name = D5_ZMANA_SORCERER   
			clswpbon = ~0 0 3~
			hpclass = ~HPWIZ~
			clsrcreq = ~1 1 1 0 0 1 0~
	END
END
*/

//class/kit switch__________________________________________________________________
//
COPY ~ManaSorc/data/mana_sorcerer/d5ymana.spl~ ~override~
COPY ~ManaSorc/data/mana_sorcerer/d5ymana.eff~ ~override~

COPY ~ManaSorc/data/mana_sorcerer/d5msplbk.bam~ ~override~
COPY ~ManaSorc/data/mana_sorcerer/d5zmana.spl~ ~override~
  SAY NAME1 @17085
  SAY UNIDENTIFIED_DESC @17085
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 location = 4 STR_VAR icon = ~d5msplbk~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5zmana~ END
COPY ~ManaSorc/data/mana_sorcerer/d5zmana.eff~ ~override~
COPY ~ManaSorc/data/mana_sorcerer/d5zmana.cre~ ~override~
COMPILE ~ManaSorc/data/mana_sorcerer/d5zmana.baf~
COMPILE ~ManaSorc/data/mana_sorcerer/d5zmana.d~

ACTION_IF (NOT FILE_EXISTS_IN_GAME ~clabma01.2da~) THEN BEGIN
  COPY ~ManaSorc/data/core/BLANKCLAB.2da~ ~override/clabma01.2da~ 		//generate undefined clab file
END 

APPEND ~clabma01.2da~ ~SWITCH      AP_D5YMANA  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


//make all spells unusable by the mage kit__________________________________________
//
// set usability to beastmaster kit above
// set flag on all wizard spells, here
//
COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
	READ_SHORT 0x1c spell_type
	READ_LONG 0x34 spell_level
	PATCH_IF (spell_type = 1) && (spell_level > 0) BEGIN
//	  READ_BYTE 0x20 exclude_3
	  WRITE_BYTE 0x20 (THIS BOR 0b00000010)
	END
  END
IF_EXISTS BUT_ONLY


//get kit identifiers_________________________________________________________________
//
OUTER_SET mana_sorcerer_code = (0x4000 + %D5_MANA_SORCERER%)

//known spells table__________________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~QD_SPLSRCKN.2da~) BEGIN
	COPY_EXISTING ~SPLSRCKN.2da~ ~override/QD_SPLSRCKN.2da~ 	//save a copy of the existing sorcerer spell progression 
END

//add spell slot stat checks to SPLPROT_______________________________________________
//
APPEND ~splprot.2da~ ~D5_MANA_PTS%TAB%109%TAB%-1%TAB%7~ UNLESS ~D5_MANA_PTS~
APPEND ~splprot.2da~ ~D5_MANA_LESS%TAB%109%TAB%-1%TAB%2~ UNLESS ~D5_MANA_LESS~
APPEND ~splprot.2da~ ~D5_FATIGUE_IS%TAB%30%TAB%-1%TAB%1~ UNLESS ~D5_FATIGUE_IS~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MANA_PTS~ BEGIN
	  SET mana_points = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MANA_LESS~ BEGIN
	  SET mana_less = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_IS~ BEGIN
	  SET fatigue_value = %row%
	END
  END
BUT_ONLY


//remove all mage spell slots_________________________________________________________
//
/* 
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d50wcst.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 145 target = 1 parameter2 = 0 timing = 9 END
BUT_ONLY

APPEND ~d5sorc.2da~ ~NO_CAST     AP_D50WCST  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
*/

COPY ~ManaSorc/lib/d5_base.spl~ ~override/d50wslt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 511 timing = 9 END
BUT_ONLY

APPEND ~d5_mana.2da~ ~NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
NOSLOTS     AP_D50WSLT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~


//create advance copies of some spells________________________________________________
//
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5ms206.spl~
//COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5ms318.spl~

ACTION_IF (FILE_EXISTS_IN_GAME ~d50wspl.2da~) BEGIN
  OUTER_SET 0wspl = 1
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d50wspl.2da~) BEGIN
 OUTER_SET 0wspl = 0
 COPY ~ManaSorc/lib/d5_base.spl~ ~override/d50wspl.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI908~ END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~16~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI110~ END
  END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI420~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI710~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI809~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI617~ END
  END
END

COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts1.spl~
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts2.spl~

/*
need to check for bit-equality, but apply the bit's underlying value in 233
1+2+4+8+16+32+64 = 7 bits to provide up to 127 points 
so 7 spells to check for bit-equality
7 patches in the big function
each with a number of .eff effects matching their value, up to 64
seems doable

OUTER_FOR (pts = 1; pts < 75; ++pts) BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts%pts%.spl~
END

COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5ssplz.spl~
  FOR (pts = 1; pts < 75; ++pts) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (%pts%) parameter2 = %mana_points% timing = 1 STR_VAR resource = EVAL ~d5mpts%pts%~ END
  END
*/

// ***** need to make these for each spell level, and add appropriate .effs to each, 

COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts1.spl~
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts2.spl~
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts3.spl~
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts4.spl~
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts5.spl~
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts6.spl~
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mpts7.spl~

COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5msplz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 1 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5mpts1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 2 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5mpts2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 4 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5mpts3~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 8 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5mpts4~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 16 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5mpts5~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 32 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5mpts6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 64 parameter2 = %mana_points% timing = 1 STR_VAR resource = ~d5mpts7~ END


//assign stats for mana points _______________________________________________________
//
// Points = (stat 109)
//
/*
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5mana1.spl~ BEGIN
  ACTION_FOR_EACH num IN ~1~ ~2~ ~3~ ~4~ ~6~ ~7~ ~8~ ~9~ BEGIN
	COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mana%num%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = %num% parameter2 = (109 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src1%let%~ END
  END
END
*/
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man3a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man3%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 3 parameter2 = (109 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5man3%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man2a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man2%let%.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = 2 parameter2 = (109 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5man2%let%~ END
  END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man-1.spl~ BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man-1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 1) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man-2.spl~ BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man-2.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 2) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man-3.spl~ BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man-3.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 3) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man-4.spl~ BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man-4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 4) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man-5.spl~ BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man-5.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 5) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man-6.spl~ BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man-6.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 6) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man-7.spl~ BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man-7.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 7) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man-8.spl~ BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man-8.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 8) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5man-9.spl~ BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5man-9.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (0 - 9) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END

APPEND ~d5_mana.2da~ ~MANA_PTS    AP_D5MAN3A  AP_D5MAN3B  AP_D5MAN3C  AP_D5MAN3D  AP_D5MAN3E  AP_D5MAN3F  AP_D5MAN3G  AP_D5MAN3H  AP_D5MAN3I  AP_D5MAN3J  AP_D5MAN3K  AP_D5MAN3L  AP_D5MAN3M  AP_D5MAN3N  AP_D5MAN3O  AP_D5MAN3P  AP_D5MAN3Q  AP_D5MAN3R  AP_D5MAN3S  AP_D5MAN3T  AP_D5MAN2A  AP_D5MAN2B  AP_D5MAN2C  AP_D5MAN2D  AP_D5MAN2E  AP_D5MAN2F  AP_D5MAN2G  AP_D5MAN2H  AP_D5MAN2I  AP_D5MAN2J  AP_D5MAN2K  AP_D5MAN2L  AP_D5MAN2M  AP_D5MAN2N  AP_D5MAN2O  AP_D5MAN2P  AP_D5MAN2Q  AP_D5MAN2R  AP_D5MAN2S  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~


//initialize ability and learn item___________________________________________________
//
COPY ~ManaSorc/data/multi_sorcerers/d5msorc.itm~ ~override/d5mana.itm~			//	learn spells .itm
  SAY NAME1 @17021
  SAY NAME2 @17021
  SAY UNIDENTIFIED_DESC @17022
  SAY IDENTIFIED_DESC @17022
  LPF ALTER_ITEM_HEADER INT_VAR target = 7 speed = 0 STR_VAR icon = ~d5msplbk~ END

COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mana.spl~
  SAY NAME1 @17050
  SAY UNIDENTIFIED_DESC @17050
  WRITE_SHORT 0x1c 4
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 location = 4 STR_VAR icon = ~d5msplbk~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5mana~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5mana~ END

APPEND ~d5_zmana.2da~ ~LEARNSPLS   GA_D5MANA   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


//clone arcane spells_________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5wclons.2da~) BEGIN
  OUTER_SET wclons = 1
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5wclons.2da~) BEGIN
  OUTER_SET wclons = 0
<<<<<<<< d5/d5wclons.2da
2DA V1.0 
SPLRES
		206		LEARN		EFF		INNATE	DISPLAY
>>>>>>>> 
COPY ~d5/d5wclons.2da~ ~override/d5wclons.2da~ 
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5msorc.2da~) BEGIN
  OUTER_SET msorc = 1
END
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5msorc.2da~) BEGIN
  OUTER_SET msorc = 0
<<<<<<<<  d5/d5msorc.2da
2DA V1.0
****
            	     ResRef   Type>>>>>>>>
COPY ~d5/d5msorc.2da~ ~override/d5msorc.2da~
END

COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
 PATCH_IF FILE_EXISTS_IN_GAME ~%SOURCE_RES%.spl~ BEGIN
//  SNPRINT 4 spell_prefix ~%SOURCE_RES%~
  READ_SHORT 0x1c spell_type 
  READ_BYTE 0x25 spell_school
  READ_LONG 0x34 spell_level
  PATCH_IF (~%SOURCE_RES%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ww][Ii][1-9][0-5][0-9]~ = 0) && (spell_type = 1) && !(spell_school = 10) && !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI908~) && !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI110~) && !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI124~) BEGIN
	SNPRINT (0 - 3) spell_num ~%SOURCE_RES%~
	SET go = 1
	PATCH_IF (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI420~) || (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI710~) || (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI809~) || (~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI617~) BEGIN
	  PATCH_IF NOT (MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
		SET go = 0
	  END
	END	
	PATCH_IF (go = 1) && !(FILE_CONTAINS_EVALUATED (~hidespl.2da~ ~%SOURCE_RES%~)) BEGIN
	  SPRINT ~spell_res~ ~%SOURCE_RES%~
	  READ_STRREF NAME1 spell_name
	  READ_STRREF UNIDENTIFIED_DESC spell_description
	  READ_ASCII 0x3a spell_icon
//	  LPF NAME_NUM_OF_SPELL_RES STR_VAR spell_res = EVAL ~%SOURCE_RES%~ RET spell_name spell_num END
	  PATCH_IF (FILE_CONTAINS_EVALUATED (~spell.ids~ ~2%spell_num%~)) BEGIN
		INNER_PATCH_SAVE 206_spell ~%SOURCE_RES%~ BEGIN
		  REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~d5m6~
		END
		INNER_PATCH_SAVE learn_spell ~%SOURCE_RES%~ BEGIN
//		  REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~d5mx~
		  REPLACE_TEXTUALLY ~%spell_res%~ ~%spell_res%M~
		END
		INNER_PATCH_SAVE spell_eff ~%SOURCE_RES%~ BEGIN
		  REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~D5MV~
		END
//		TO_UPPER ~%spell_eff%~
		INNER_PATCH_SAVE innate_spell ~%SOURCE_RES%~ BEGIN
		  REPLACE_TEXTUALLY ~^[Ss][Pp][Ww][Ii]~ ~d5m4~
		END
		TEXT_SPRINT real_spell ~%SOURCE_RES%~
		INNER_ACTION BEGIN
		  ACTION_IF wclons = 0 BEGIN
			APPEND ~d5wclons.2da~ ~%SOURCE_RES%	%206_spell%	%learn_spell%	%spell_eff%	%innate_spell%	%real_spell% ~
		  END
		  ACTION_IF msorc = 0 BEGIN
			APPEND ~d5msorc.2da~ ~sorcerer	%SOURCE_RES%	3~
		  END
// make innates with cloned spell effects
		  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%innate_spell%.spl~ BEGIN
			COPY_EXISTING ~%SOURCE_RES%.spl~ ~override/%innate_spell%.spl~
			  WRITE_SHORT 0x1c 4
			  WRITE_LONG 0x34 spell_level
			  READ_LONG 0x64 abil_offset
			  READ_SHORT 0x68 abil_number
			  READ_BYTE (%abil_offset% + 0x0c) abil_target					
			  READ_SHORT (%abil_offset% + 0x0e) abil_range
			  READ_LONG 0x6a eff_offset
			  WHILE (%abil_number% > 0) BEGIN
				SET abil_number = (%abil_number% - 1)
				WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
			  END
			  LPF DELETE_EFFECT END
			  PATCH_IF (%abil_target% = 4) BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = %spell_level% parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%real_spell%~ END
				PATCH_IF (%abil_range% < 35) BEGIN
				  PATCH_IF (%abil_range% > 4) BEGIN
					LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
				  END
				  PATCH_IF (%abil_range% < 5) BEGIN
					LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	
				  END
				END
			  END
			  ELSE BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = %spell_level% parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
			  END
			  PATCH_IF !(MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5man-%spell_level%~ END
			  END
			  PATCH_IF (MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~) BEGIN
				PATCH_IF (%spell_level% > 1) BEGIN
				  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5man-%spell_level%~ END
				END
			  END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5msplz~ END
		  END
// make .EFFs adding the arcane clone
		  CREATE EFF ~%spell_eff%~
			WRITE_LONG 0x10 171
			WRITE_LONG 0x14 1
			WRITE_LONG 0x24 0
			WRITE_LONG 0x28 1
			WRITE_SHORT 0x2c 100
			WRITE_EVALUATED_ASCII 0x30 ~%innate_spell%~ #8
			WRITE_LONG 0x90 1
			WRITE_EVALUATED_ASCII 0x94 ~%spell_eff%~ #8
// make 206 spells preventing the .EFF
		  COPY ~ManaSorc/lib/d5_base.spl~ ~override/%206_spell%.spl~
			WRITE_SHORT 0x1c 4
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
// add 206 spells to CLAB spell
		  COPY_EXISTING ~d5ms206.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
// add 318 effects to spell that populates the alilities
		  ACTION_IF (%spell_level% = 9) BEGIN
			COPY_EXISTING ~d5msplz.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 9 parameter2 = %mana_less% timing = 0 duration = 1 STR_VAR resource = EVAL ~%spell_eff%~ END
			IF_EXISTS BUT_ONLY
		  END
		  ACTION_IF (%spell_level% = 8) BEGIN
			COPY_EXISTING ~d5msplz.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 8 parameter2 = %mana_less% timing = 0 duration = 1 STR_VAR resource = EVAL ~%spell_eff%~ END
			IF_EXISTS BUT_ONLY
		  END
		  ACTION_IF (%spell_level% = 7) BEGIN
			COPY_EXISTING ~d5msplz.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 7 parameter2 = %mana_less% timing = 0 duration = 1 STR_VAR resource = EVAL ~%spell_eff%~ END
			IF_EXISTS BUT_ONLY
		  END
		  ACTION_IF (%spell_level% = 6) BEGIN
			COPY_EXISTING ~d5msplz.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 6 parameter2 = %mana_less% timing = 0 duration = 1 STR_VAR resource = EVAL ~%spell_eff%~ END
			IF_EXISTS BUT_ONLY
		  END
		  ACTION_IF (%spell_level% = 5) BEGIN
			COPY_EXISTING ~d5msplz.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 5 parameter2 = %mana_less% timing = 0 duration = 1 STR_VAR resource = EVAL ~%spell_eff%~ END
			IF_EXISTS BUT_ONLY
		  END
		  ACTION_IF (%spell_level% = 4) BEGIN
			COPY_EXISTING ~d5msplz.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 4 parameter2 = %mana_less% timing = 0 duration = 1 STR_VAR resource = EVAL ~%spell_eff%~ END
			IF_EXISTS BUT_ONLY
		  END
		  ACTION_IF (%spell_level% = 3) BEGIN
			COPY_EXISTING ~d5msplz.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 3 parameter2 = %mana_less% timing = 0 duration = 1 STR_VAR resource = EVAL ~%spell_eff%~ END
			IF_EXISTS BUT_ONLY
		  END
		  ACTION_IF (%spell_level% = 2) BEGIN
			COPY_EXISTING ~d5msplz.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 2 parameter2 = %mana_less% timing = 0 duration = 1 STR_VAR resource = EVAL ~%spell_eff%~ END
			IF_EXISTS BUT_ONLY
		  END
		  ACTION_IF (%spell_level% = 1) BEGIN
			COPY_EXISTING ~d5msplz.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 1 parameter2 = %mana_less% timing = 0 duration = 1 STR_VAR resource = EVAL ~%spell_eff%~ END
			IF_EXISTS BUT_ONLY
		  END
// make learn spells canceling the 206
		  COPY ~ManaSorc/lib/d5_base.spl~ ~override/%learn_spell%.spl~
			WRITE_EVALUATED_ASCII 0x3a ~%spell_icon%~ #8
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
//		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
		  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5msplz~ END
// make copy of learn spell for kjeron's UI system (eventually, just rename the learn spell to this name)
//		  COPY_EXISTING ~%learn_spell%.spl~ ~override/%spell_res%M.spl~
// add 172 to d5msplz#
		  COPY_EXISTING ~d5msplz.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
// generate slot#x spells
		  COPY_EXISTING ~d5mpts1.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  BUT_ONLY
		  COPY_EXISTING ~d5mpts2.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  BUT_ONLY
		  COPY_EXISTING ~d5mpts3.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  BUT_ONLY
		  COPY_EXISTING ~d5mpts4.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  BUT_ONLY
		  COPY_EXISTING ~d5mpts5.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  BUT_ONLY
		  COPY_EXISTING ~d5mpts6.spl~ ~override~
			FOR (pts_count = 1; pts_count < 32; ++pts_count) BEGIN
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			END
		  BUT_ONLY
		  COPY_EXISTING ~d5mpts7.spl~ ~override~
			FOR (pts_count = 1; pts_count < 64; ++pts_count) BEGIN
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			END
		  BUT_ONLY
// remove all known spells after chargen
		  ACTION_IF 0wspl = 0 BEGIN
			COPY_EXISTING ~d50wspl.spl~ ~override~
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
		  END
		END // end inner_action
	  END
	END
  END
 END
BUT_ONLY

//set up spell learn UI screens_______________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5msorcX.2da~) BEGIN

 INCLUDE ~ManaSorc/lib/sequencer_menu.tpa~

 LAF CREATE_SEQUENCER_MENU 
  INT_VAR 
	name = RESOLVE_STR_REF (~Spell Selection~)
	tip = RESOLVE_STR_REF (~Spell Selection~)
	desc = RESOLVE_STR_REF (~This ability allows you to learn new spells~)
  STR_VAR 
	resref = ~d5msorc~
	spelllist = ~d5msorc~
	spelltable = ~QD_SPLSRCKN~
	icon = ~spcl919b~
	title = ~Spell Selection~
	label = ~Select a spell to learn~
	subspell = ~M~
 END

 COPY_EXISTING ~d5msorc.2da~ ~override/d5msorcX.2da~

END


//remove known spells right after chargen_____________________________________________
//
APPEND ~d5_mana.2da~ ~NO_WSPLS    AP_D50WSPL  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
                                

//apply EFF protections_______________________________________________________________
//
//APPEND ~d5_mana.2da~ ~NO_RSPLS    AP_D5MS318  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
APPEND ~d5_mana.2da~ ~NO_LSPLS    AP_D5MS206  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


//daily spell slot refresh____________________________________________________________
//
COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mnptz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5mnpts~ END

APPEND ~d5_mana.2da~ ~MANA_PTS    AP_D5MNPTZ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

CREATE EFF ~d5mnpts~
  WRITE_LONG 0x10 232
  WRITE_LONG 0x14 1
  WRITE_LONG 0x1c 0
  WRITE_LONG 0x20 20
  WRITE_LONG 0x24 9
  WRITE_SHORT 0x2c 100
  WRITE_ASCII 0x30 ~d5mnpt~ #8
  WRITE_LONG 0x48 102

COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mnpt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_value% timing = 1 STR_VAR resource = ~d5mrfrsh~ END


// spell to refresh spell slots_______________________________________________________
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5mrfrsh.spl~ BEGIN
 COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5mrfrsh.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5man-1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5man-2~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5man-3~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5man-4~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5man-5~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5man-6~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5man-7~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5man-8~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5man-9~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5msplz~ END
END


/*
//make sure sequencer/contingency works if possible___________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~M_d5meta.lua~ BEGIN
	// umm... actually, maybe the metamagic component will take care of this entirely...h
END
*/


/*
//manually create versions of sequencer/contingency___________________________________
//
COPY ~ManaSorc/data/metamagic/spwi420.spl~ ~override/d5sseq1.spl~
	SAY NAME1 @6041
	SAY UNIDENTIFIED_DESC @6042
// only allow to be cast if have 1 each 1st- and 2nd-level slots
// reduce 1st- and 2nd-level slots by 1 when cast

COPY ~ManaSorc/data/metamagic/spwi710.spl~ ~override/d5sseq2.spl~
	SAY NAME1 @6043
	SAY UNIDENTIFIED_DESC @6044
// only allow to be cast if have 1 each 2nd/3rd/4th-level slots
// reduce 2nd/3rd/4th-level slots by 1 when cast

COPY ~ManaSorc/data/metamagic/spwi809.spl~ ~override/d5sseq3.spl~
	SAY NAME1 @6045
	SAY UNIDENTIFIED_DESC @6046
// only allow to be cast if have 1 each 4th/5th/6th-level slots
// reduce 4th/5th/6th-level slots by 1 when cast
*/


//make sequencer/contingency scrolls unusable by mana sorcerers_______________________
//
ACTION_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~53~) AND !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~54~) BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~scrl9q.itm~ BEGIN
	COPY_EXISTING ~scrl9q.itm~ ~override~
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %mana_sorcerer_code% parameter2 = 9 power = 0 timing = 2 END
  END
END
ACTION_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~53~) AND !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~54~) AND !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
  ACTION_FOR_EACH meta_scroll IN ~scrl6p~ ~scrl8l~ ~scrl9d~ ~scrl7u~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%meta_scroll%.itm~ BEGIN
	  COPY_EXISTING ~%meta_scroll%.itm~ ~override~
		LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %mana_sorcerer_code% parameter2 = 9 power = 0 timing = 2 END
	END
  END
END

ACTION_IF (MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~M_d5meta.lua~ BEGIN
  	APPEND ~M_d5meta.lua~ ~mageBookStrings['D5W4420'] = mageBookStrings['SPWI420'] -- Minor Sequencer clone, replace resource, keep quotes
mageBookStrings['D5W4617'] = mageBookStrings['SPWI710'] -- Spell Sequencer
mageBookStrings['D5W4710'] = mageBookStrings['SPWI809'] -- Spell Trigger
mageBookStrings['D5W4809'] = mageBookStrings['SPWI617'] -- Contingency
mageBookStrings['D5W4908'] = mageBookStrings['SPWI908'] -- Chain Contingency~
  END
END

ACTION_IF FILE_EXISTS_IN_GAME ~spwi420d.spl~ BEGIN
  COPY_EXISTING ~spwi420d.spl~ ~override/d5m4420d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5m4420~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi420p.spl~ BEGIN
  COPY_EXISTING ~spwi420p.spl~ ~override/d5m4420p.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5m4420~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi710d.spl~ BEGIN
  COPY_EXISTING ~spwi710d.spl~ ~override/d5m4710d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5m4710~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi710p.spl~ BEGIN
  COPY_EXISTING ~spwi710p.spl~ ~override/d5m4710p.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5m4710~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi809d.spl~ BEGIN
  COPY_EXISTING ~spwi809d.spl~ ~override/d5m4809d.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5m4809~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi809p.spl~ BEGIN
  COPY_EXISTING ~spwi809p.spl~ ~override/d5m4809p.spl~
	LPF ALTER_EFFECT INT_VAR silent = 1 STR_VAR resource = ~d5m4809~ END
END


//multisorc no get innate sequencers__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5adsq1m.spl~ BEGIN
 ACTION_IF !(FILE_EXISTS_IN_GAME ~d5msnsq.spl~) BEGIN
  CREATE SPL ~d5msnsq~
  COPY_EXISTING ~d5msnsq.spl~ ~override~
	LPF ADD_SPELL_HEADER INT_VAR target = 1 END 
  COPY_EXISTING ~d5msnsq.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5adsq1m~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5adsq2m~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5adsq3m~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5adcntm~ END
 END
 APPEND ~d5_mana.2da~ ~NO_META     AP_D5MSNSQ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END


//make HLA tables_____________________________________________________________________
// ...clone sorcerer HLAs as innates
//
ACTION_IF FILE_EXISTS_IN_GAME ~spwi920.spl~ BEGIN
  COPY_EXISTING ~spwi920.spl~ ~override/d5hl920.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi921.spl~ BEGIN
  COPY_EXISTING ~spwi921.spl~ ~override/d5hl921.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi922.spl~ BEGIN
  COPY_EXISTING ~spwi922.spl~ ~override/d5hl922.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi923.spl~ BEGIN
  COPY_EXISTING ~spwi923.spl~ ~override/d5hl923.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi924.spl~ BEGIN
  COPY_EXISTING ~spwi924.spl~ ~override/d5hl924.spl~
	WRITE_SHORT 0x1c 4
END
ACTION_IF FILE_EXISTS_IN_GAME ~spwi925.spl~ BEGIN
  COPY_EXISTING ~spwi925.spl~ ~override/d5hl925.spl~
	WRITE_SHORT 0x1c 4
END
/*
ACTION_IF FILE_EXISTS_IN_GAME ~spcl928.spl~ BEGIN
  COPY_EXISTING ~spcl928.spl~ ~override/d5hl928.spl~
	LPF ALTER_EFFECT INT_VAR match_opcode = 42 opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
END
ACTION_IF FILE_EXISTS_IN_GAME ~spcl929.spl~ BEGIN
  COPY_EXISTING ~spcl929.spl~ ~override/d5hl929.spl~
	LPF ALTER_EFFECT INT_VAR match_opcode = 42 opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 9 END	
END
ACTION_IF FILE_EXISTS_IN_GAME ~spcl930.spl~ BEGIN
  COPY_EXISTING ~spcl930.spl~ ~override/d5hl930.spl~
	LPF ALTER_EFFECT INT_VAR match_opcode = 42 opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
END
*/

LAF action_replace_hla STR_VAR kit_name = ~D5_MANA_SORCERER~ remove_ability = ~GA_SPWI920~ ability = ~GA_D5HL920~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_MANA_SORCERER~ remove_ability = ~GA_SPWI921~ ability = ~GA_D5HL921~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_MANA_SORCERER~ remove_ability = ~GA_SPWI922~ ability = ~GA_D5HL922~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_MANA_SORCERER~ remove_ability = ~GA_SPWI923~ ability = ~GA_D5HL923~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_MANA_SORCERER~ remove_ability = ~GA_SPWI924~ ability = ~GA_D5HL924~ END
LAF action_replace_hla STR_VAR kit_name = ~D5_MANA_SORCERER~ remove_ability = ~GA_SPWI925~ ability = ~GA_D5HL925~ END
LAF action_remove_hla STR_VAR kit_name = ~D5_MANA_SORCERER~ remove_ability = ~AP_SPWI928~ END
LAF action_remove_hla STR_VAR kit_name = ~D5_MANA_SORCERER~ remove_ability = ~AP_SPWI929~ END
LAF action_remove_hla STR_VAR kit_name = ~D5_MANA_SORCERER~ remove_ability = ~AP_SPWI930~ END


//disable quickspell buttons and scroll learning______________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5srcnq.spl~) BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5srcnq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 3 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 4 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 5 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 101 target = 1 parameter2 = 147 timing = 9 END
END

APPEND ~d5_mana.2da~ ~NO_QUICK    AP_D5SRCNQ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


/* doesn't make sense with mana points
//stat-based bonus spells_____________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb_attrbon.qd~) BEGIN

  COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols   
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_CHR_SLOTS~ BEGIN
	    SET chr_slots = %row%
	  END
	END
  BUT_ONLY

  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5nabsw.spl~) BEGIN
	COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5nabsw.spl~
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp1~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5absp1~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5abspw~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5abspw~ END
  END

/*
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5absp4.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = %mana_sorcerer_code% parameter2 = 9 timing = 9 STR_VAR resource = ~d5abspm~ END

  COPY ~ManaSorc/data/ability_bonuses/d5_slots.eff~ ~override/d5abspm.eff~
	WRITE_ASCII 0x30 ~d5abspm~ #8

  COPY_EXISTING ~d5absps.spl~ ~override/d5abspm.spl~
	PATCH_FOR_EACH let IN ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ ~u~ ~v~ ~w~ ~x~ ~y~ BEGIN
	  LPF ALTER_EFFECT INT_VAR match_opcode = 326 STR_VAR match_resource = EVAL ~d5chrs%let%~ resource = EVAL ~d5chrm%let%~ END
	END
*/

  APPEND ~d5_mana.2da~  ~STATSLOTS   AP_D5NABSW  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC1   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC1   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC2   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC2   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC3   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC3   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC4   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC4   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
STATSLOTS   AP_D5SRC5   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~

  ACTION_DEFINE_ASSOCIATIVE_ARRAY cha_nums_lets BEGIN
	13	=> m
	14	=> n
	15	=> o
	16	=> p
	17	=> q
	18	=> r
	19	=> s
	20	=> t
	21	=> u
	22	=> v
	23	=> w
	24	=> x
	25	=> y
  END

  COPY_EXISTING  ~d5sslot.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 13 parameter2 = 133 timing = 1 STR_VAR resource = ~d5chrml~ END
	PHP_EACH cha_nums_lets AS num => let BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %num% parameter2 = %chr_slots% timing = 1 STR_VAR resource = EVAL ~d5chrm%let%~ END
	END

 ACTION_IF !(FILE_EXISTS_IN_GAME ~d5chrml.spl~) BEGIN
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrml.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrml~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmm.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmn.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmo.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmp.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmq.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmr.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrms.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrms~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmt.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmu.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmv.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (134 + (0x10000 * 1)) timing = 0 duration = 7 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmw.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 0 duration = 7 END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmx.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmx~ END
  COPY ~ManaSorc/lib/d5_base.spl~ ~override/d5chrmy.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5chrmy~ END
 END
 
END
//____________________________________________________________________________________
*/


//MAKE +SPELL SLOT ITEMS WORK________________________________________________________
//
// make EFFs to increase mana points... don't remember why using EFFs!
//ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5mabn1.eff~ BEGIN
  CREATE EFF ~d5mabn1~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 (109 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5MABN1~ #8
  CREATE EFF ~d5mabn2~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 (109 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5MABN2~ #8
  CREATE EFF ~d5mabn3~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 (109 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5MABN3~ #8
  CREATE EFF ~d5mabn4~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 (109 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5MABN4~ #8
  CREATE EFF ~d5mabn5~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 (109 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5MABN5~ #8
  CREATE EFF ~d5mabn6~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 (109 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5MABN6~ #8
  CREATE EFF ~d5mabn7~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 (109 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5MABN7~ #8
  CREATE EFF ~d5mabn8~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 (109 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5MABN8~ #8
  CREATE EFF ~d5mabn9~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 (109 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5MABN9~ #8

COPY_EXISTING ~ring40.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn5~ END
IF_EXISTS BUT_ONLY
ACTION_IF GAME_IS ~bgee~ BEGIN
 COPY_EXISTING ~ring08.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn5~ END
 IF_EXISTS BUT_ONLY
END
ACTION_IF GAME_IS ~bg2ee eet iwdee~ BEGIN
 COPY_EXISTING ~ring08.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn9~ END
 IF_EXISTS BUT_ONLY
END
COPY_EXISTING ~brac25.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn5~ END
IF_EXISTS BUT_ONLY
COPY_EXISTING ~wa2dak.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn5~ END
IF_EXISTS BUT_ONLY
COPY_EXISTING ~amul16.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn2~ END
IF_EXISTS BUT_ONLY
COPY_EXISTING ~helm27.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn5~ END
IF_EXISTS BUT_ONLY
COPY_EXISTING ~helm27.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn9~ END
IF_EXISTS BUT_ONLY
COPY_EXISTING ~misc89.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn9~ END
IF_EXISTS BUT_ONLY
ACTION_FOR_EACH spells_item IN ~udagg2b~ BEGIN
 COPY_EXISTING ~%spells_item%.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn2~ END
 IF_EXISTS BUT_ONLY
END
ACTION_FOR_EACH spells_item IN ~udag3b~ BEGIN
 COPY_EXISTING ~%spells_item%.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn4~ END
 IF_EXISTS BUT_ONLY
END
ACTION_FOR_EACH spells_item IN ~udagg4b~ ~udagg5a~ BEGIN
 COPY_EXISTING ~%spells_item%.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5mabn7~ END
 IF_EXISTS BUT_ONLY
END

/* skip this... for now.  not sure how to auto-translate it
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d51l1spl.eff~ BEGIN
// make EFFs to increase traditional mem/cast slots by 1
  CREATE EFF ~d51l1spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 1
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L1SPL~ #8
  CREATE EFF ~d51l2spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 2
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L2SPL~ #8
  CREATE EFF ~d51l3spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 4
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L3SPL~ #8
  CREATE EFF ~d51l4spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 8
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L4SPL~ #8
  CREATE EFF ~d51l5spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 16
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L5SPL~ #8
  CREATE EFF ~d51l6spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 32
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L6SPL~ #8
  CREATE EFF ~d51l7spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 64
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L7SPL~ #8
  CREATE EFF ~d51l8spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 128
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L8SPL~ #8
  CREATE EFF ~d51l9spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 256
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D51L9SPL~ #8

// make EFFs to increase traditional mem/cast slots by 2
  CREATE EFF ~D52L1spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 1
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L1SPL~ #8
  CREATE EFF ~D52L2spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 2
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L2SPL~ #8
  CREATE EFF ~D52L3spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 4
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L3SPL~ #8
  CREATE EFF ~D52L4spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 8
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L4SPL~ #8
  CREATE EFF ~D52L5spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 16
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L5SPL~ #8
  CREATE EFF ~D52L6spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 32
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L6SPL~ #8
  CREATE EFF ~D52L7spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 64
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L7SPL~ #8
  CREATE EFF ~D52L8spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 128
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L8SPL~ #8
  CREATE EFF ~D52L9spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 256
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D52L9SPL~ #8

// make EFFs to double traditional mem/cast slots
  CREATE EFF ~D5XL1spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL1SPL~ #8
  CREATE EFF ~D5XL2spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 2
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL2SPL~ #8
  CREATE EFF ~D5XL3spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 3
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL3SPL~ #8
  CREATE EFF ~D5XL4spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 4
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL4SPL~ #8
  CREATE EFF ~D5XL5spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 5
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL5SPL~ #8
  CREATE EFF ~D5XL6spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 6
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL6SPL~ #8
  CREATE EFF ~D5XL7spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 7
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL7SPL~ #8
  CREATE EFF ~D5XL8spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 8
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL8SPL~ #8
  CREATE EFF ~D5XL9spl~
	WRITE_LONG 0x10 42
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 9
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5XL9SPL~ #8
END

 OUTER_SET mageslot_item_ind = 0
 OUTER_SPRINT $mage_slot_items(~%mageslot_item_ind%~) ~mage_slot_item~
 COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
  	SET plus_slots = 0
	READ_BYTE     0x2f current ELSE 0
	READ_BYTE     0x2b current2 ELSE 0
	READ_LONG 0x64 headoffset  ELSE 0
	READ_SHORT 0x68 headcount  ELSE 0
	READ_LONG 0x6a effectsoffset  ELSE 0
	FOR (headcyc = 0; headcyc < headcount ; headcyc = headcyc + 1) BEGIN
      this_head = 0
	  READ_SHORT (headoffset + (headcyc * 0x38) + 0x1e) effcount  ELSE 0
	  READ_SHORT (headoffset + (headcyc * 0x38) + 0x20) effectsindex  ELSE 0
	  FOR (effcyc = 0; effcyc < effcount; effcyc = effcyc + 1) BEGIN
		READ_SHORT (effectsoffset + (effectsindex + effcyc)* 0x30) opcode ELSE 0
		PATCH_IF (opcode = 42) AND (this_head = 0) BEGIN
		  SET plus_slots = 1
		  SET this_head = 1
		END
	  END
	END
	PATCH_IF (plus_slots = 1)BEGIN
	  SPRINT $mage_slot_items(~%mageslot_item_ind%~) ~%SOURCE_RES%~
	  SET ++mageslot_item_ind
	END
  END
 BUT_ONLY
	  
 ACTION_PHP_EACH spell_slot_items AS ind => slot_item BEGIN
  COPY_EXISTING ~%slot_item%.itm~ ~override~
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src1e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src2e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src3e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src4e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src5e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src6e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src7e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src8e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src9e~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src1f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src2f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src3f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src4f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src5f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src6f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src7f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src8f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src9f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 1   opcode = 177 parameter1 = 1 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src1f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 2   opcode = 177 parameter1 = 2 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src2f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 4   opcode = 177 parameter1 = 3 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src3f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 8   opcode = 177 parameter1 = 4 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src4f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 16  opcode = 177 parameter1 = 5 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src5f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 32  opcode = 177 parameter1 = 6 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src6f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 64  opcode = 177 parameter1 = 7 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src7f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 128 opcode = 177 parameter1 = 8 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src8f~ insert = ~first~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 256 opcode = 177 parameter1 = 9 parameter2 = 0 timing = 2 STR_VAR resource = ~d5src9f~ insert = ~first~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l1spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l2spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l3spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l4spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l5spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l6spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l7spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l8spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d51l9spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 1   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l1spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 2   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l2spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 4   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l3spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 8   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l4spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 16  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l5spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 32  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l6spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 64  opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l7spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l8spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d52l9spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl1spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl2spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 3 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl3spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 4 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl4spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 5 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl5spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 6 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl6spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 7 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl7spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 8 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl8spl~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 9 match_parameter2 = 0   opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5xl9spl~ END
	LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 318 target = 1 parameter1 = 202 parameter2 = 115 timing = 2 STR_VAR resource = EVAL ~%SOURCE_RES%~ END
  IF_EXISTS BUT_ONLY
 END

END // end if not already done
*/

END 	//	end define function
//____________________________________________________________________________________

